/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:44:17 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libnfshared.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@class NSData, NSArray;

@interface NFTLV : NSObject {

	unsigned _tag;
	NSData* _value;
	NSArray* _children;

}

@property (nonatomic,readonly) unsigned tag; 
@property (nonatomic,readonly) NSData * value; 
@property (nonatomic,readonly) NSArray * children; 
+(id)TLVsWithData:(id)arg1 ;
+(id)simpleTLVsWithTag:(unsigned)arg1 fromData:(id)arg2 ;
+(id)TLVWithData:(id)arg1 ;
+(id)TLVsWithData:(id)arg1 requireDefiniteEncoding:(BOOL)arg2 ;
+(id)TLVWithTag:(unsigned)arg1 unsignedLongValue:(unsigned)arg2 ;
+(id)TLVWithTag:(unsigned)arg1 children:(id)arg2 ;
+(id)simpleTLVsWithData:(id)arg1 ;
+(id)TLVWithTag:(unsigned)arg1 unsignedChar:(unsigned char)arg2 ;
+(id)TLVSsWithBytes:(const void*)arg1 length:(unsigned long long)arg2 requireDefiniteEncoding:(BOOL)arg3 ;
+(id)TLVWithTag:(unsigned)arg1 value:(id)arg2 ;
+(id)_parseTLVs:(const char**)arg1 end:(const char*)arg2 simple:(BOOL)arg3 definite:(BOOL)arg4 ;
+(id)_intToData:(unsigned)arg1 ;
+(id)TLVWithTag:(unsigned)arg1 fromData:(id)arg2 ;
-(NSArray *)children;
-(id)asData;
-(id)childWithTag:(unsigned)arg1 ;
-(id)valueAsHexString;
-(id)description;
-(unsigned short)valueAsUnsignedShort;
-(id)childrenWithTag:(unsigned)arg1 ;
-(unsigned)tag;
-(NSData *)value;
-(unsigned)valueAsUnsignedLong;
-(unsigned long long)valueAsUnsignedLongLong;
-(id)valueAsString;
@end

