/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:41:58 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libAppletTranslationLibrary.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@interface SlalomUtils : NSObject
+(int)isValidFelicaBlock:(id)arg1 ;
+(unsigned long long)readBitsValueFromBuffer:(char*)arg1 bitPosition:(int)arg2 length:(int)arg3 ;
+(unsigned short)readUInt16FromBytes:(char*)arg1 ;
+(unsigned long long)getBitsFrom:(unsigned long long)arg1 numberOfBits:(int)arg2 startingFrom:(int)arg3 ;
+(unsigned)readUInt24FromBytes:(char*)arg1 ;
+(unsigned long long)readNumberFromBytes:(char*)arg1 numberOfBytes:(int)arg2 ;
@end

