/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:41:58 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libAppletTranslationLibrary.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@interface SlalomWriteOperation : NSObject {

	unsigned short serviceCode;
	unsigned short blockNumber;
	unsigned short offsets;

}

@property (assign) unsigned short serviceCode; 
@property (assign) unsigned short blockNumber; 
@property (assign) unsigned short offsets; 
-(id)description;
-(unsigned short)offsets;
-(unsigned short)serviceCode;
-(unsigned short)blockNumber;
-(void)setServiceCode:(unsigned short)arg1 ;
-(void)setBlockNumber:(unsigned short)arg1 ;
-(void)setOffsets:(unsigned short)arg1 ;
@end

