/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:41:58 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libAppletTranslationLibrary.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@class NSData;

@interface WuluRecord : NSObject {

	unsigned char _sfi;
	unsigned char _number;
	unsigned short _associatedSerialNumber;
	NSData* _data;

}

@property (assign,nonatomic) unsigned char sfi;                                  //@synthesize sfi=_sfi - In the implementation block
@property (assign,nonatomic) unsigned char number;                               //@synthesize number=_number - In the implementation block
@property (nonatomic,retain) NSData * data;                                      //@synthesize data=_data - In the implementation block
@property (assign,nonatomic) unsigned short associatedSerialNumber;              //@synthesize associatedSerialNumber=_associatedSerialNumber - In the implementation block
+(id)withRecordSfi:(unsigned char)arg1 recordNumber:(unsigned char)arg2 recordData:(id)arg3 associatedSerialNumber:(unsigned short)arg4 ;
-(unsigned char)number;
-(unsigned char)sfi;
-(void)setNumber:(unsigned char)arg1 ;
-(void)setData:(NSData *)arg1 ;
-(NSData *)data;
-(void)setSfi:(unsigned char)arg1 ;
-(unsigned short)associatedSerialNumber;
-(void)setAssociatedSerialNumber:(unsigned short)arg1 ;
@end

