/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:48:32 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libFusionComponentCheck.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <libFusionComponentCheck.dylib/HSComponentCheckBase.h>

@class NSString;

@interface HSComponentCheckMesa : HSComponentCheckBase {

	NSString* currentNvSn;
	NSString* currentBBUniqueChipId;
	NSString* currentBBSerialNo;

}
+(id)sharedSingleton;
-(id)init;
-(id)querySN;
-(id)getMesaSensorSerialNumber:(id)arg1 ;
-(id)getUniqueChipId:(id*)arg1 ;
-(id)getUniqueDeviceId:(id*)arg1 ;
@end

