/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:48:32 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libFusionComponentCheck.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@interface HSComponentCheck : NSObject {

	unsigned long long currentContext;

}
+(void)setContext:(unsigned long long)arg1 ;
+(unsigned long long)getContext;
+(id)sharedSingleton;
-(id)init;
-(id)createChallenge;
-(id)generateSignedKETS:(id)arg1 status:(id)arg2 errorStr:(id)arg3 ;
-(id)calculateSHA512:(id)arg1 ;
-(int)processComponentCheckCommand:(id)arg1 response:(id*)arg2 ;
@end

