/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:35:10 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/swift/libswiftCore.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <libswiftCore.dylib/libswiftCore.dylib-Structs.h>
#import <libswiftCore.dylib/Swift.__SwiftNativeNSString.h>
#import <libobjc.A.dylib/Swift._NSCopying.h>

@interface Swift.__SharedStringStorage : Swift.__SwiftNativeNSString <Swift._NSCopying> {

	 _owner;
	 start;
	 _countAndFlags;
	 _breadcrumbs;

}

@property (readonly,nonatomic) long long length; 
@property (readonly,nonatomic) unsigned long long hash; 
@property (readonly,nonatomic) unsigned long long fastestEncoding; 
-(unsigned long long)fastestEncoding;
-(char)isEqualToString:(id)arg1 ;
-(char)getCString:(char*)arg1 maxLength:(long long)arg2 encoding:(unsigned long long)arg3 ;
-(const char*)cStringUsingEncoding:(unsigned long long)arg1 ;
-(void)getCharacters:(unsigned short*)arg1 range:(SCD_Struct_Sw1)arg2 ;
-(unsigned long long)hash;
-(unsigned short)characterAtIndex:(long long)arg1 ;
-(long long)length;
-(char)isEqual:(id)arg1 ;
-(const char*)UTF8String;
-(id)copyWithZone:(void*)arg1 ;
-(const char*)_fastCStringContents:(char)arg1 ;
-(id)init;
@end

