//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoardHome/BSDescriptionProviding-Protocol.h>
#import <SpringBoardHome/BSInvalidatable-Protocol.h>

@class NSString, SBFolderController;

@interface _SBFolderControllerPageViewControllerAppearStateOverrideAssertion : NSObject <BSInvalidatable, BSDescriptionProviding>
{
    _Bool _invalidated;
    NSString *_reason;
    SBFolderController *_folderController;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) __weak SBFolderController *folderController; // @synthesize folderController=_folderController;
@property(readonly) unsigned long long hash;
@property(nonatomic, getter=isInvalidated) _Bool invalidated; // @synthesize invalidated=_invalidated;
@property(readonly, copy, nonatomic) NSString *reason; // @synthesize reason=_reason;
@property(readonly) Class superclass;
@end

