//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface _SBFloatingDockPlatterMetrics : NSObject
{
    double _continuousCornerRadius;
    double _shadowRadius;
    double _shadowYOffset;
    struct CGRect _bounds;
}


// Remaining properties
@property(readonly, nonatomic) struct CGRect bounds; // @synthesize bounds=_bounds;
@property(readonly, nonatomic) double continuousCornerRadius; // @synthesize continuousCornerRadius=_continuousCornerRadius;
@property(readonly, nonatomic) double shadowRadius; // @synthesize shadowRadius=_shadowRadius;
@property(readonly, nonatomic) double shadowYOffset; // @synthesize shadowYOffset=_shadowYOffset;
@end

