//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBIconZoomAnimator.h>

@class SBFloatyFolderView, SBHFolderZoomSettings, SBIconView;

@interface _SBInnerFolderIconZoomAnimator : SBIconZoomAnimator
{
    SBFloatyFolderView *_folderView;
    SBIconView *_folderIconView;
    struct CGAffineTransform _folderIconViewScaleTransform;
}


// Remaining properties
@property(retain, nonatomic) SBHFolderZoomSettings *settings; // @dynamic settings;
@end

