//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ChronoServices/CHSAvocadoDescriptor.h>

#import <SpringBoardHome/SBHAddWidgetSheetGalleryItem-Protocol.h>

@class NSString;

@interface CHSAvocadoDescriptor (SpringBoardHome) <SBHAddWidgetSheetGalleryItem>

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, copy, nonatomic) NSString *sbh_appName;
@property(readonly, nonatomic) unsigned long long sbh_supportedSizeClasses;
@property(readonly, copy, nonatomic) NSString *sbh_widgetDescription;
@property(readonly, copy, nonatomic) NSString *sbh_widgetName;
@property(readonly) Class superclass;
@end

