//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/NSObject-Protocol.h>

@class NSString;
@protocol CHSWidgetPersonality;

@protocol CHSWidgetPersonality <NSObject>
@property(readonly, copy, nonatomic) NSString *kind;
@property(readonly, copy, nonatomic) NSString *extensionBundleIdentifier;
- (_Bool)matchesPersonality:(id <CHSWidgetPersonality>)arg1;
@end

