//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIWindow.h>

#import <SpringBoardHome/SBIconDragPreviewContaining-Protocol.h>

@class UIView;

@interface SBDefaultIconDragPreviewWindow : UIWindow <SBIconDragPreviewContaining>
{
}


// Remaining properties
@property(readonly, nonatomic) UIView *iconDragPreviewContainerView;
@end

