//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBLeafIcon.h>

@class NSString;
@protocol SBDownloadingIconDataSource;

@interface SBDownloadingIcon : SBLeafIcon
{
    _Bool _uninstalledByUser;
    id <SBDownloadingIconDataSource> _downloadingIconDataSource;
}


// Remaining properties
@property(readonly, nonatomic) id <SBDownloadingIconDataSource> downloadingIconDataSource; // @synthesize downloadingIconDataSource=_downloadingIconDataSource;
@property(readonly, copy, nonatomic) NSString *realDisplayName;
@property(nonatomic) _Bool uninstalledByUser; // @synthesize uninstalledByUser=_uninstalledByUser;
@end

