//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardFoundation/SBFTouchPassThroughViewController.h>

#import <SpringBoardHome/BSDescriptionProviding-Protocol.h>
#import <SpringBoardHome/SBFloatingDockViewDelegate-Protocol.h>
#import <SpringBoardHome/SBFolderControllerDelegate-Protocol.h>
#import <SpringBoardHome/SBFolderPresentingViewControllerDelegate-Protocol.h>
#import <SpringBoardHome/SBIconListModelObserver-Protocol.h>
#import <SpringBoardHome/SBIconListViewDragDelegate-Protocol.h>
#import <SpringBoardHome/SBIconLocationPresenting-Protocol.h>
#import <SpringBoardHome/SBIconViewProviding-Protocol.h>
#import <SpringBoardHome/SBIconViewQuerying-Protocol.h>
#import <SpringBoardHome/SBScaleIconZoomAnimationContaining-Protocol.h>

@class NSArray, NSHashTable, NSMutableArray, NSSet, NSString, SBFTouchPassThroughView, SBFloatingDockView, SBFolderController, SBFolderPresentingViewController, SBHFloatingDockStyleConfiguration, SBHIconManager, SBHIconModel, SBHomeScreenIconTransitionAnimator, SBIconListModel, SBIconListView, UIView, UIViewController, UIWindow, _UILegibilitySettings;
@protocol SBFloatingDockSuggestionsViewProviding, SBFloatingDockViewControllerDelegate, SBIconViewProviding;

@interface SBFloatingDockViewController : SBFTouchPassThroughViewController <SBIconListViewDragDelegate, SBIconListModelObserver, SBFolderControllerDelegate, SBFolderPresentingViewControllerDelegate, SBScaleIconZoomAnimationContaining, SBIconViewProviding, SBFloatingDockViewDelegate, SBIconViewQuerying, SBIconLocationPresenting, BSDescriptionProviding>
{
    SBFloatingDockView *_dockView;
    _UILegibilitySettings *_legibilitySettings;
    NSHashTable *_bouncedDropSessions;
    struct __CFRunLoopObserver *_resizeRunLoopObserver;
    _Bool _wantsFastIconReordering;
    _Bool _shouldIndicateImpossibleDrop;
    _Bool _transitioningUnderlyingPresentationStyleConfiguration;
    id <SBFloatingDockViewControllerDelegate> _delegate;
    UIViewController<SBFloatingDockSuggestionsViewProviding> *_suggestionsViewController;
    double _dockOffscreenProgress;
    SBHIconManager *_iconManager;
    id <SBIconViewProviding> _iconViewProvider;
    SBIconListModel *_dockListModel;
    SBFolderPresentingViewController *_folderPresentingViewController;
    SBHomeScreenIconTransitionAnimator *_currentFolderAnimator;
    NSMutableArray *_currentExpandCompletions;
    NSMutableArray *_currentCollapseCompletions;
    SBFTouchPassThroughView *_scalingView;
    double _lastDockHeight;
    SBHFloatingDockStyleConfiguration *_underlyingPresentationStyleConfiguration;
    SBHFloatingDockStyleConfiguration *_transitionTargetUnderlyingPresentationStyleConfiguration;
}


// Remaining properties
@property(readonly, nonatomic) UIWindow *animationWindow;
@property(readonly, nonatomic) UIView *containerView;
@property(readonly, nonatomic) double contentHeight;
@property(retain, nonatomic) NSMutableArray *currentCollapseCompletions; // @synthesize currentCollapseCompletions=_currentCollapseCompletions;
@property(retain, nonatomic) NSMutableArray *currentExpandCompletions; // @synthesize currentExpandCompletions=_currentExpandCompletions;
@property(retain, nonatomic) SBHomeScreenIconTransitionAnimator *currentFolderAnimator; // @synthesize currentFolderAnimator=_currentFolderAnimator;
@property(readonly, nonatomic) SBIconListView *currentIconListView;
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <SBFloatingDockViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) SBIconListView *dockIconListView;
@property(retain, nonatomic) SBIconListModel *dockListModel; // @synthesize dockListModel=_dockListModel;
@property(nonatomic) double dockOffscreenProgress; // @synthesize dockOffscreenProgress=_dockOffscreenProgress;
@property(retain, nonatomic) SBFloatingDockView *dockView;
@property(readonly, copy, nonatomic) NSArray *extraViews;
@property(readonly, copy, nonatomic) NSArray *extraViewsContainers;
@property(readonly, nonatomic) UIView *fallbackIconContainerView;
@property(readonly, nonatomic) struct CGRect floatingDockScreenFrame;
@property(readonly, nonatomic) struct CGRect floatingDockScreenPresentationFrame;
@property(retain, nonatomic) SBFolderPresentingViewController *folderPresentingViewController; // @synthesize folderPresentingViewController=_folderPresentingViewController;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) SBHIconManager *iconManager; // @synthesize iconManager=_iconManager;
@property(readonly, nonatomic) SBHIconModel *iconModel;
@property(readonly, nonatomic) __weak id <SBIconViewProviding> iconViewProvider; // @synthesize iconViewProvider=_iconViewProvider;
@property(nonatomic) double lastDockHeight; // @synthesize lastDockHeight=_lastDockHeight;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings;
@property(readonly, nonatomic) double maximumContentHeight;
@property(readonly, nonatomic) double maximumDockContinuousCornerRadius;
@property(readonly, nonatomic) double preferredVerticalMargin;
@property(readonly, nonatomic) SBFolderController *presentedFolderController;
@property(readonly, copy, nonatomic) NSSet *presentedIconLocations;
@property(readonly, nonatomic, getter=isPresentingFolder) _Bool presentingFolder;
@property(nonatomic) double requestedVerticalMargin;
@property(retain, nonatomic) SBFTouchPassThroughView *scalingView; // @synthesize scalingView=_scalingView;
@property(readonly, nonatomic) _Bool shouldAnimateFirstTwoViewsAsOne;
@property(readonly, nonatomic) _Bool shouldAnimateLastTwoViewsAsOne;
@property(nonatomic) _Bool shouldIndicateImpossibleDrop; // @synthesize shouldIndicateImpossibleDrop=_shouldIndicateImpossibleDrop;
@property(retain, nonatomic) UIViewController<SBFloatingDockSuggestionsViewProviding> *suggestionsViewController; // @synthesize suggestionsViewController=_suggestionsViewController;
@property(readonly) Class superclass;
@property(copy, nonatomic) SBHFloatingDockStyleConfiguration *transitionTargetUnderlyingPresentationStyleConfiguration; // @synthesize transitionTargetUnderlyingPresentationStyleConfiguration=_transitionTargetUnderlyingPresentationStyleConfiguration;
@property(nonatomic, getter=isTransitioningUnderlyingBackgroundStyle) _Bool transitioningUnderlyingPresentationStyleConfiguration; // @synthesize transitioningUnderlyingPresentationStyleConfiguration=_transitioningUnderlyingPresentationStyleConfiguration;
@property(readonly, nonatomic) double translationFromFullyPresentedFrame;
@property(copy, nonatomic) SBHFloatingDockStyleConfiguration *underlyingPresentationStyleConfiguration; // @synthesize underlyingPresentationStyleConfiguration=_underlyingPresentationStyleConfiguration;
@property(nonatomic) _Bool wantsFastIconReordering; // @synthesize wantsFastIconReordering=_wantsFastIconReordering;
@end

