//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class SBFolderBackgroundView, UIColor;

@protocol SBFolderBackgroundViewDelegate
- (UIColor *)accessibilityTintColorForBackgroundView:(SBFolderBackgroundView *)arg1;
@end

