//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class SBIcon, UIImage;

@protocol SBFolderIconGridCellImageProvider
- (UIImage *)gridCellImageOfSize:(struct CGSize)arg1 forIcon:(SBIcon *)arg2 iconImageInfo:(struct SBIconImageInfo)arg3;
@end

