//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoardHome/BSDescriptionProviding-Protocol.h>

@class NSArray, NSString, SBLeafIcon;

@interface SBHApplicationWidgetCollection : NSObject <BSDescriptionProviding>
{
    SBLeafIcon *_icon;
    NSArray *_avocadoDescriptors;
    NSString *_vendorName;
    NSString *_containerName;
    NSString *_iconImageApplicationBundleIdentifier;
}


// Remaining properties
@property(retain, nonatomic) NSArray *avocadoDescriptors; // @synthesize avocadoDescriptors=_avocadoDescriptors;
@property(copy, nonatomic) NSString *containerName; // @synthesize containerName=_containerName;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) SBLeafIcon *icon; // @synthesize icon=_icon;
@property(copy, nonatomic) NSString *iconImageApplicationBundleIdentifier; // @synthesize iconImageApplicationBundleIdentifier=_iconImageApplicationBundleIdentifier;
@property(readonly) Class superclass;
@property(copy, nonatomic) NSString *vendorName; // @synthesize vendorName=_vendorName;
@end

