//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UINavigationBar.h>

@class NSArray, SBHFeatherBlurView, UILabel, UINavigationBarAppearance, UINavigationItem, UIView;

@interface SBHFeatherBlurNavigationBar : UINavigationBar
{
    UINavigationBarAppearance *_barAppearance;
    UILabel *_featherBlurTitleLabel;
    UINavigationItem *_configuredForItem;
    NSArray *_maskLayers;
    UIView *_capturedLargeTextLabelContainerView;
    UIView *_capturedTinyTextLabelContainerView;
    SBHFeatherBlurView *_featherBlurBackgroundView;
    struct CGRect _gradientMaskFrame;
}


// Remaining properties
@property(retain, nonatomic) SBHFeatherBlurView *featherBlurBackgroundView; // @synthesize featherBlurBackgroundView=_featherBlurBackgroundView;
@property(readonly, nonatomic) struct CGRect gradientMaskFrame; // @synthesize gradientMaskFrame=_gradientMaskFrame;
@end

