//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoardHome/BSDescriptionProviding-Protocol.h>
#import <SpringBoardHome/NSCopying-Protocol.h>

@class NSString;

@interface SBHFolderIconVisualConfiguration : NSObject <NSCopying, BSDescriptionProviding>
{
    struct CGSize _gridCellSize;
    struct CGSize _gridCellSpacing;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) struct CGSize gridCellSize; // @synthesize gridCellSize=_gridCellSize;
@property(nonatomic) struct CGSize gridCellSpacing; // @synthesize gridCellSpacing=_gridCellSpacing;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

