//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoardHome/SBDownloadingIconDataSource-Protocol.h>

@class NSString;

@interface SBHFakeDownloadingIconDataSource : NSObject <SBDownloadingIconDataSource>
{
    _Bool isCancelable;
    _Bool isCloudDemoted;
    _Bool isPausable;
    _Bool isPrioritizable;
    _Bool _isPaused;
    NSString *_applicationBundleID;
    NSString *_applicationDisplayName;
    double _progress;
}


// Remaining properties
@property(readonly, nonatomic, getter=isActive) _Bool active;
@property(copy, nonatomic) NSString *applicationBundleID; // @synthesize applicationBundleID=_applicationBundleID;
@property(copy, nonatomic) NSString *applicationDisplayName; // @synthesize applicationDisplayName=_applicationDisplayName;
@property(readonly, nonatomic, getter=isCancelable) _Bool cancelable;
@property(readonly, nonatomic, getter=isCloudDemoted) _Bool cloudDemoted;
@property(readonly, copy, nonatomic) NSString *configurationStorageIdentifier;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic, getter=isDownloading) _Bool downloading;
@property(readonly, nonatomic, getter=isFailed) _Bool failed;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) Class iconClass;
@property(readonly, nonatomic, getter=isInstalling) _Bool installing;
@property(nonatomic) _Bool isCancelable; // @synthesize isCancelable;
@property(nonatomic) _Bool isCloudDemoted; // @synthesize isCloudDemoted;
@property(nonatomic) _Bool isPausable; // @synthesize isPausable;
@property(nonatomic) _Bool isPaused; // @synthesize isPaused=_isPaused;
@property(nonatomic) _Bool isPrioritizable; // @synthesize isPrioritizable;
@property(readonly, nonatomic, getter=isPausable) _Bool pausable;
@property(readonly, nonatomic, getter=isPaused) _Bool paused;
@property(readonly, nonatomic, getter=isPrioritizable) _Bool prioritizable;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(readonly) Class superclass;
@property(readonly, copy, nonatomic) NSString *uniqueIdentifier;
@property(readonly, nonatomic, getter=isWaiting) _Bool waiting;
@end

