//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/NSObject-Protocol.h>

@class SBIconView, UIViewController;
@protocol SBHIconViewConfigurationInteraction;

@protocol SBHIconViewConfigurationInteractionDelegate <NSObject>
- (SBIconView *)sourceIconViewForConfigurationInteraction:(id <SBHIconViewConfigurationInteraction>)arg1;
- (UIViewController *)containerViewControllerForConfigurationInteraction:(id <SBHIconViewConfigurationInteraction>)arg1;

@optional
- (void)configurationInteractionDidEnd:(id <SBHIconViewConfigurationInteraction>)arg1;
- (void)configurationInteractionWillEnd:(id <SBHIconViewConfigurationInteraction>)arg1;
- (void)configurationInteractionDidCommit:(id <SBHIconViewConfigurationInteraction>)arg1;
- (void)configurationInteractionDidBegin:(id <SBHIconViewConfigurationInteraction>)arg1;
- (void)configurationInteractionWillBegin:(id <SBHIconViewConfigurationInteraction>)arg1;
- (SBIconView *)referenceIconViewForConfigurationInteraction:(id <SBHIconViewConfigurationInteraction>)arg1;
@end

