//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBHIconAnimationSettings.h>

@interface SBHIconZoomSettings : SBHIconAnimationSettings
{
    _Bool _labelAlphaWithZoom;
}


// Remaining properties
@property(nonatomic) _Bool labelAlphaWithZoom; // @synthesize labelAlphaWithZoom=_labelAlphaWithZoom;
@end

