//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBHLegibility-Protocol.h>
#import <SpringBoardHome/SBIconLocationPresenting-Protocol.h>
#import <SpringBoardHome/SBIconViewQuerying-Protocol.h>

@class SBFolderIconImageCache, SBHIconImageCache, SBIcon, SBIconView, SBRootFolder;
@protocol SBIconListLayoutProvider;

@protocol SBHLibraryChildViewController <SBIconLocationPresenting, SBIconViewQuerying, SBHLegibility>
@property(retain, nonatomic) id <SBIconListLayoutProvider> listLayoutProvider;
@property(retain, nonatomic) SBHIconImageCache *iconImageCache;

@optional
@property(retain, nonatomic) SBRootFolder *rootFolder;
@property(retain, nonatomic) SBFolderIconImageCache *folderIconImageCache;
- (SBIconView *)folderIconViewForIcon:(SBIcon *)arg1 folderRelativeIconIndexPath:(id *)arg2;
@end

