//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/NSObject-Protocol.h>

@class NSString, SBHSearchBar;

@protocol SBHSearchBarDelegate <NSObject>

@optional
- (void)searchBarCancelButtonClicked:(SBHSearchBar *)arg1;
- (_Bool)searchBar:(SBHSearchBar *)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(NSString *)arg3;
- (void)searchBar:(SBHSearchBar *)arg1 textDidChange:(NSString *)arg2;
- (void)searchBarTextDidEndEditing:(SBHSearchBar *)arg1;
- (_Bool)searchBarShouldEndEditing:(SBHSearchBar *)arg1;
- (void)searchBarTextDidBeginEditing:(SBHSearchBar *)arg1;
- (_Bool)searchBarShouldBeginEditing:(SBHSearchBar *)arg1;
@end

