//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class NSArray, UIView;

@interface SBHTableViewController : UITableViewController
{
    long long _styleBeforeShowingNoResults;
    struct CGRect _keyboardFrame;
    NSArray *_centerNoResultsFoundLabelConstraints;
    _Bool _showNoResultsView;
    UIView *_noResultsView;
}


// Remaining properties
@property(retain, nonatomic) UIView *noResultsView; // @synthesize noResultsView=_noResultsView;
@property(nonatomic) _Bool showNoResultsView; // @synthesize showNoResultsView=_showNoResultsView;
@end

