//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSArray, NSMutableArray, UIStackView;

@interface SBHWidgetFamilySegmentedControl : UIControl
{
    NSArray *_items;
    long long _selectedSegmentIndex;
    UIStackView *_stackView;
    NSMutableArray *_buttons;
}


// Remaining properties
@property(retain, nonatomic) NSMutableArray *buttons; // @synthesize buttons=_buttons;
@property(copy, nonatomic) NSArray *items; // @synthesize items=_items;
@property(nonatomic) long long selectedSegmentIndex; // @synthesize selectedSegmentIndex=_selectedSegmentIndex;
@property(retain, nonatomic) UIStackView *stackView; // @synthesize stackView=_stackView;
@end

