//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBHWidgetDragHandlerPassing-Protocol.h>

@class SBHWidgetWrapperViewController;

@protocol SBHWidgetWrapperViewControllerDelegate <SBHWidgetDragHandlerPassing>

@optional
- (void)wrapperViewControllerSelectedSizeClassChanged:(SBHWidgetWrapperViewController *)arg1;
@end

