//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoardHome/BSDescriptionProviding-Protocol.h>
#import <SpringBoardHome/CHSWidgetPersonality-Protocol.h>
#import <SpringBoardHome/NSCopying-Protocol.h>
#import <SpringBoardHome/NSSecureCoding-Protocol.h>
#import <SpringBoardHome/SBLeafIconDataSource-Protocol.h>

@class NSString;

@interface SBHWidget : NSObject <CHSWidgetPersonality, SBLeafIconDataSource, NSCopying, NSSecureCoding, BSDescriptionProviding>
{
    NSString *_containingApplicationBundleIdentifier;
    NSString *_displayName;
    _Bool _suggestion;
    NSString *_uniqueIdentifier;
    NSString *_kind;
    NSString *_extensionBundleIdentifier;
}


// Remaining properties
@property(readonly, copy, nonatomic) NSString *configurationStorageIdentifier;
@property(readonly, copy, nonatomic) NSString *containingApplicationBundleIdentifier;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, copy, nonatomic) NSString *displayName;
@property(readonly, copy, nonatomic) NSString *extensionBundleIdentifier; // @synthesize extensionBundleIdentifier=_extensionBundleIdentifier;
@property(readonly) unsigned long long hash;
@property(readonly, copy, nonatomic) NSString *kind; // @synthesize kind=_kind;
@property(nonatomic, getter=isSuggestion) _Bool suggestion; // @synthesize suggestion=_suggestion;
@property(readonly) Class superclass;
@property(readonly, copy, nonatomic) NSString *uniqueIdentifier; // @synthesize uniqueIdentifier=_uniqueIdentifier;
@end

