//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoardHome/BSDescriptionProviding-Protocol.h>
#import <SpringBoardHome/NSSecureCoding-Protocol.h>

@class NSString, NSURL;

@interface SBIconViewDragInfo : NSObject <NSSecureCoding, BSDescriptionProviding>
{
    NSString *_bundleIdentifier;
    NSURL *_launchURL;
    long long _startLocation;
}


// Remaining properties
@property(copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(copy, nonatomic) NSURL *launchURL; // @synthesize launchURL=_launchURL;
@property(nonatomic) long long startLocation; // @synthesize startLocation=_startLocation;
@property(readonly) Class superclass;
@end

