//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <BaseBoardUI/BSUIScrollView.h>

@protocol SBIconScrollViewDelegate;

@interface SBIconScrollView : BSUIScrollView
{
    struct CGPoint _lastAnimatedScrollContentOffset;
}


// Remaining properties
@property(nonatomic) __weak id <SBIconScrollViewDelegate> delegate; // @dynamic delegate;
@property(nonatomic) struct CGPoint lastAnimatedScrollContentOffset; // @synthesize lastAnimatedScrollContentOffset=_lastAnimatedScrollContentOffset;
@end

