//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoardHome/BSDescriptionProviding-Protocol.h>

@class NSArray, NSCountedSet, NSDate, NSMapTable, NSMutableDictionary, NSMutableSet, NSSet, NSString, NSTimer, SBIconView, SBPlaceholderIcon;

@interface SBIconDragContext : NSObject <BSDescriptionProviding>
{
    NSMutableSet *_sourceIconViews;
    NSMapTable *_iconToExpandAfterDropAnimation;
    NSMutableSet *_destinationIconViews;
    NSCountedSet *_messageExpectations;
    NSMutableSet *_enteredIconListViews;
    NSMapTable *_targetsForCancellingIconViews;
    NSMapTable *_dragPreviewForIconViews;
    NSMutableSet *_appLocalContexts;
    NSMutableDictionary *_destinationFolderIconViews;
    NSMutableDictionary *_destinationStackIconViews;
    NSMutableSet *_dropAnimatingDragItems;
    NSMutableDictionary *_initialIconPaths;
    NSMapTable *_bouncedIcons;
    NSMapTable *_appDragLocalContexts;
    NSMapTable *_iconViewDropAssertions;
    _Bool _performedIconDrop;
    _Bool _cancelled;
    _Bool _notifiedDelegateForDropSession;
    long long _state;
    SBPlaceholderIcon *_iconPlaceholder;
    NSArray *_grabbedIconViews;
    NSSet *_itemIdentifiers;
    NSSet *_sourceIcons;
    SBIconView *_primaryIconView;
    SBIconView *_recipientIconView;
    NSDate *_lastUserInteractionDate;
    NSTimer *_watchdogTimer;
}


// Remaining properties
@property(readonly, copy, nonatomic) NSSet *appLocalContexts;
@property(nonatomic, getter=isCancelled) _Bool cancelled; // @synthesize cancelled=_cancelled;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, copy, nonatomic) NSSet *expectedMessages;
@property(copy, nonatomic) NSArray *grabbedIconViews; // @synthesize grabbedIconViews=_grabbedIconViews;
@property(readonly, nonatomic) _Bool hasNonDefaultSizedSourceIcons;
@property(readonly, nonatomic) _Bool hasUserDragged;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) SBPlaceholderIcon *iconPlaceholder; // @synthesize iconPlaceholder=_iconPlaceholder;
@property(copy, nonatomic) NSSet *itemIdentifiers; // @synthesize itemIdentifiers=_itemIdentifiers;
@property(copy, nonatomic) NSDate *lastUserInteractionDate; // @synthesize lastUserInteractionDate=_lastUserInteractionDate;
@property(nonatomic) _Bool notifiedDelegateForDropSession; // @synthesize notifiedDelegateForDropSession=_notifiedDelegateForDropSession;
@property(nonatomic) _Bool performedIconDrop; // @synthesize performedIconDrop=_performedIconDrop;
@property(retain, nonatomic) SBIconView *primaryIconView; // @synthesize primaryIconView=_primaryIconView;
@property(retain, nonatomic) SBIconView *recipientIconView; // @synthesize recipientIconView=_recipientIconView;
@property(copy, nonatomic) NSSet *sourceIcons; // @synthesize sourceIcons=_sourceIcons;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isUserActive) _Bool userActive;
@property(readonly, nonatomic, getter=isWaitingForMessage) _Bool waitingForMessage;
@property(retain, nonatomic) NSTimer *watchdogTimer; // @synthesize watchdogTimer=_watchdogTimer;
@end

