//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBCrossfadingIconImageSource-Protocol.h>

@class NSString, SBIcon;
@protocol BSInvalidatable;

@protocol SBIconViewCustomImageViewControlling <SBCrossfadingIconImageSource>
@property(nonatomic, getter=isEditing) _Bool editing;
@property(nonatomic) struct SBIconImageInfo iconImageInfo;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;

@optional
@property(nonatomic) unsigned long long pauseReasons;
@property(nonatomic) unsigned long long imageViewAlignment;
@property(nonatomic, getter=isPrivateModeEnabled) _Bool privateModeEnabled;
@property(nonatomic) _Bool visiblySettled;
@property(readonly, nonatomic) _Bool wantsLabelHidden;
@property(nonatomic) double brightness;
@property(copy, nonatomic) CDUnknownBlockType backgroundViewProvider;
@property(nonatomic, getter=isBackgroundBlurEnabled) _Bool backgroundBlurEnabled;
@property(nonatomic, getter=isUserInteractionEnabled) _Bool userInteractionEnabled;
@property(nonatomic, getter=isDropping) _Bool dropping;
@property(nonatomic, getter=isOverlapping) _Bool overlapping;
@property(nonatomic, getter=isShowingContextMenu) _Bool showingContextMenu;
@property(readonly, nonatomic) SBIcon *icon;
- (id <BSInvalidatable>)cancelTouchesForCurrentEventInHostedContent;
- (id <BSInvalidatable>)disableImageUpdatesForReason:(NSString *)arg1;
@end

