//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, SBIcon, SBIconView;
@protocol SBIconViewProviding;

@interface SBIconRotationContainer : UIView
{
    _Bool _offscreen;
    NSString *_location;
    long long _transitionAnimation;
    SBIconView *_startView;
    SBIconView *_endView;
    id <SBIconViewProviding> _iconViewProvider;
    struct SBIconCoordinate _coordinate;
}


// Remaining properties
@property(readonly, nonatomic) struct SBIconCoordinate coordinate; // @synthesize coordinate=_coordinate;
@property(readonly, nonatomic) SBIcon *endIcon;
@property(readonly, nonatomic) SBIconView *endView; // @synthesize endView=_endView;
@property(retain, nonatomic) id <SBIconViewProviding> iconViewProvider; // @synthesize iconViewProvider=_iconViewProvider;
@property(readonly, copy, nonatomic) NSString *location; // @synthesize location=_location;
@property(readonly, nonatomic, getter=isOffscreen) _Bool offscreen; // @synthesize offscreen=_offscreen;
@property(readonly, nonatomic) SBIcon *startIcon;
@property(readonly, nonatomic) SBIconView *startView; // @synthesize startView=_startView;
@property(readonly, nonatomic) long long transitionAnimation; // @synthesize transitionAnimation=_transitionAnimation;
@end

