//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class SBIconListPageControl;

@protocol SBIconListPageControlDelegate
- (void)pageControl:(SBIconListPageControl *)arg1 didMoveCurrentPageToPage:(long long)arg2 withScrubbing:(_Bool)arg3;
- (void)pageControlDidReceiveButtonTap:(SBIconListPageControl *)arg1;
@end

