//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoardHome/NSFastEnumeration-Protocol.h>
#import <SpringBoardHome/SBIconIndexNodeObserver-Protocol.h>

@class NSMapTable, NSMutableArray, NSString;
@protocol SBIconIndexMutableListObserver, SBIconIndexNode;

@interface SBIconIndexMutableList : NSObject <SBIconIndexNodeObserver, NSFastEnumeration>
{
    NSMutableArray *_nodes;
    NSMapTable *_index;
    id <SBIconIndexMutableListObserver> _observer;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) id <SBIconIndexNode> firstNode;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) id <SBIconIndexNode> lastNode;
@property(nonatomic) __weak id <SBIconIndexMutableListObserver> observer; // @synthesize observer=_observer;
@property(readonly) Class superclass;
@end

