//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/UIDropInteractionDelegate_Private-Protocol.h>

@class SBIconView, UIDragItem, UIDropInteraction;
@protocol UIDropSession, UIViewSpringAnimationBehaviorDescribing;

@protocol SBIconListViewDraggingPolicyHandling <UIDropInteractionDelegate_Private>
- (void)handleSpringLoadOnIconView:(SBIconView *)arg1;
- (_Bool)allowsSpringLoadForSession:(id <UIDropSession>)arg1 onIconView:(SBIconView *)arg2;

@optional
- (id <UIViewSpringAnimationBehaviorDescribing>)_dropInteraction:(UIDropInteraction *)arg1 customSpringAnimationBehaviorForDroppingItem:(UIDragItem *)arg2;
@end

