//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIGestureRecognizer.h>

@class UITouch;

@interface SBPageManagementListTapGestureRecognizer : UIGestureRecognizer
{
    UITouch *_activeTouch;
}


// Remaining properties
@property(retain, nonatomic) UITouch *activeTouch; // @synthesize activeTouch=_activeTouch;
@end

