//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/UIViewControllerAnimatedTransitioning-Protocol.h>

@class BSUIAnimationFactory;
@protocol SBViewControllerContextTransitioning;

@protocol SBViewControllerAnimatedTransitioning <UIViewControllerAnimatedTransitioning>
- (void)animateTransition:(id <SBViewControllerContextTransitioning>)arg1;
- (double)transitionDuration:(id <SBViewControllerContextTransitioning>)arg1;

@optional
- (unsigned long long)transitionAnimationOptions:(id <SBViewControllerContextTransitioning>)arg1;
- (BSUIAnimationFactory *)transitionAnimationFactory:(id <SBViewControllerContextTransitioning>)arg1;
@end

