//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBViewControllerPercentCompletionReporting-Protocol.h>
#import <SpringBoardHome/SBViewControllerReversibleTransitioning-Protocol.h>
#import <SpringBoardHome/SBViewControllerTransitionRestartedReporting-Protocol.h>
#import <SpringBoardHome/UIViewControllerContextTransitioning-Protocol.h>

@protocol SBViewControllerContextTransitioning <UIViewControllerContextTransitioning, SBViewControllerReversibleTransitioning, SBViewControllerPercentCompletionReporting, SBViewControllerTransitionRestartedReporting>
- (_Bool)wasPreviousPhaseInteractive;
- (_Bool)initiallyInteractive;
- (void)restartTransition;
- (_Bool)supportsRestarting;
- (_Bool)supportsCancelling;
- (_Bool)isTransitioning;
@end

