//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/NSObject-Protocol.h>

@class NSArray;

@protocol WGWidgetIconAnimationExtraViewsProviding <NSObject>
@property(readonly, nonatomic) _Bool shouldAnimateFirstTwoViewsAsOne;
@property(readonly, nonatomic) _Bool shouldAnimateLastTwoViewsAsOne;
@property(readonly, copy, nonatomic) NSArray *extraViews;
@property(readonly, copy, nonatomic) NSArray *extraViewsContainers;
@end

