/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:48:33 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libPPMDataModel.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

typedef struct _NSZone* NSZoneRef;

typedef struct {
	float list;
	unsigned long long count;
	unsigned long long size;
} SCD_Struct_OT1;

typedef struct {
	unsigned baselineWRdc : 1;
	unsigned mLBConfig : 1;
	unsigned maxRdcRatio : 1;
	unsigned maxRdcRatioR2Extrap : 1;
} SCD_Struct_OT2;

typedef struct {
	unsigned downstreamCommonResistance : 1;
	unsigned downstreamNorthResistance : 1;
	unsigned systemEquivalentResistance : 1;
	unsigned traceResistance25C : 1;
	unsigned traceResistanceTemperatureCoeff : 1;
} SCD_Struct_OT3;

