/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:48:33 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libPPMDataModel.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <libPPMDataModel.dylib/libPPMDataModel.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface OTAResistanceData : PBCodable <NSCopying> {

	SCD_Struct_OT1* _resistance25Cs;
	SCD_Struct_OT1* _temperatureCoeffs;

}

@property (nonatomic,readonly) unsigned long long resistance25CsCount; 
@property (nonatomic,readonly) float* resistance25Cs; 
@property (nonatomic,readonly) unsigned long long temperatureCoeffsCount; 
@property (nonatomic,readonly) float* temperatureCoeffs; 
-(void)mergeFrom:(id)arg1 ;
-(unsigned long long)hash;
-(id)dictionaryRepresentation;
-(BOOL)readFrom:(id)arg1 ;
-(id)description;
-(BOOL)isEqual:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)dealloc;
-(unsigned long long)resistance25CsCount;
-(void)clearResistance25Cs;
-(float)resistance25CAtIndex:(unsigned long long)arg1 ;
-(void)addResistance25C:(float)arg1 ;
-(unsigned long long)temperatureCoeffsCount;
-(void)clearTemperatureCoeffs;
-(float)temperatureCoeffAtIndex:(unsigned long long)arg1 ;
-(void)addTemperatureCoeff:(float)arg1 ;
-(float*)resistance25Cs;
-(void)setResistance25Cs:(float*)arg1 count:(unsigned long long)arg2 ;
-(float*)temperatureCoeffs;
-(void)setTemperatureCoeffs:(float*)arg1 count:(unsigned long long)arg2 ;
@end

