//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoardUI/SBSceneHandleObserverToken-Protocol.h>

@class NSMutableDictionary, NSString;

@interface _SBSceneHandleObserverToken : NSObject <SBSceneHandleObserverToken>
{
    NSMutableDictionary *_owner;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) __weak NSMutableDictionary *owner; // @synthesize owner=_owner;
@property(readonly) Class superclass;
@end

