//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import <SpringBoardUI/SBUILegibility-Protocol.h>

@class NSString, SBUILegibilityView, _UILegibilitySettings;

@interface SBLockScreenTimerDialView : UIView <SBUILegibility>
{
    double _strength;
    _UILegibilitySettings *_legibilitySettings;
    SBUILegibilityView *_dialView;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
@property(nonatomic) double strength; // @synthesize strength=_strength;
@property(readonly) Class superclass;
@end

