//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoardUI/BSInvalidatable-Protocol.h>
#import <SpringBoardUI/SBSceneHandleObserver-Protocol.h>

@class NSMutableDictionary, NSString;

@interface SBSceneHandleBlockObserver : NSObject <BSInvalidatable, SBSceneHandleObserver>
{
    NSMutableDictionary *_createBlocks;
    NSMutableDictionary *_destroyBlocks;
    NSMutableDictionary *_didUpdateContentStateBlocks;
    NSMutableDictionary *_didUpdateSettingsBlocks;
    NSMutableDictionary *_didUpdateClientSettingsBlocks;
    NSMutableDictionary *_didUpdatePairingStatusBlocks;
    _Bool _invalidated;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

