/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:48:37 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/swift/libswiftAppleArchive.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@interface _TtCC12AppleArchive13ArchiveStreamP33_4438800270C24D4D260353A75D774C7225CustomArchiveStreamBridge : _UKNOWN_SUPERCLASS_ {

	 instance;
	 yaaStream;

}
@end

