//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSExtensionContext.h>

@protocol _SBSUICFUserNotificationContentExtensionHostInterface;

@interface _SBSUICFUserNotificationContentExtensionContext : NSExtensionContext
{
    id <_SBSUICFUserNotificationContentExtensionHostInterface> _hostService;
}


// Remaining properties
@property(nonatomic) __weak id <_SBSUICFUserNotificationContentExtensionHostInterface> hostService; // @synthesize hostService=_hostService;
@end

