//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TelephonyUI/TPNumberPad.h>

@protocol SBNumberPadDelegate;

@interface SBNumberPadWithDelegate : TPNumberPad
{
    id <SBNumberPadDelegate> _delegate;
}


// Remaining properties
@property(nonatomic) __weak id <SBNumberPadDelegate> delegate; // @synthesize delegate=_delegate;
@end

