//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/_UIKeyboardAnimator.h>

@class BSAnimationSettings;
@protocol SBPasscodeKeyboardAnimatorDelegate;

@interface SBPasscodeKeyboardAnimator : _UIKeyboardAnimator
{
    BSAnimationSettings *_animationSettings;
    id <SBPasscodeKeyboardAnimatorDelegate> _delegate;
}


// Remaining properties
@property(retain, nonatomic) BSAnimationSettings *animationSettings; // @synthesize animationSettings=_animationSettings;
@property(nonatomic) __weak id <SBPasscodeKeyboardAnimatorDelegate> delegate; // @synthesize delegate=_delegate;
@end

