//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBSUIInCallWindowSceneDeviceLockEvent : NSObject
{
    long long _sourceType;
}


// Remaining properties
@property(readonly, nonatomic) long long sourceType; // @synthesize sourceType=_sourceType;
@end

