//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIApplicationSceneClientSettings.h>

@interface SBSUIInCallSceneClientSettings : UIApplicationSceneClientSettings
{
}


// Remaining properties
@property(readonly, nonatomic, getter=isCallConnected) _Bool callConnected;
@property(readonly, nonatomic) unsigned long long preferredHardwareButtonEventTypes;
@property(readonly, nonatomic) int preferredStatusBarStyleOverridesToSuppress;
@property(readonly, nonatomic) _Bool shouldBecomeVisibleWhenWakingDisplay;
@property(readonly, nonatomic) _Bool supportsDeviceLockActions;
@property(readonly, nonatomic) _Bool transientOverlayHomeIndicatorAutoHidden;
@end

