//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardUIServices/NSObject-Protocol.h>

@class NSString, UIColor;

@protocol SBUIPasscodeNumberPadButton <NSObject>
- (void)setReduceTransparencyButtonColor:(UIColor *)arg1;
- (NSString *)stringCharacter;
- (int)characterType;
@end

