//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoardUIServices/NSSecureCoding-Protocol.h>

@interface SBUIRemoteAlertIdleTimerSettings : NSObject <NSSecureCoding>
{
    _Bool _disablesWarn;
    _Bool _usesLockScreenRules;
    double _autoLockTimeout;
}


// Remaining properties
@property(nonatomic) double autoLockTimeout; // @synthesize autoLockTimeout=_autoLockTimeout;
@property(nonatomic) _Bool disablesWarn; // @synthesize disablesWarn=_disablesWarn;
@property(nonatomic) _Bool usesLockScreenRules; // @synthesize usesLockScreenRules=_usesLockScreenRules;
@end

