//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <SpringBoardUIServices/_SBUIPopoverExtensionRemoteInterface-Protocol.h>

@protocol SBUIPopoverExtension, _SBUIPopoverExtensionHostInterface;

@interface SBUIPopoverExtensionRemoteViewController : UIViewController <_SBUIPopoverExtensionRemoteInterface>
{
    id <_SBUIPopoverExtensionHostInterface> _hostService;
    UIViewController<SBUIPopoverExtension> *_extensionViewController;
}


// Remaining properties
@property(retain, nonatomic) UIViewController<SBUIPopoverExtension> *extensionViewController; // @synthesize extensionViewController=_extensionViewController;
@property(retain, nonatomic) id <_SBUIPopoverExtensionHostInterface> hostService; // @synthesize hostService=_hostService;
@end

