//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardFoundation/SBFTouchPassThroughView.h>

@class CALayer, SBUILegibilityLabel, UIView, _UILegibilitySettings, _UILegibilityView;

@interface SBUIFaceIDCameraGlyphView : SBFTouchPassThroughView
{
    _UILegibilitySettings *_legibilitySettings;
    UIView *_arrowContainer;
    SBUILegibilityLabel *_callToActionLabel;
    unsigned long long _state;
    _UILegibilityView *_arrowHead;
    _UILegibilityView *_arrowTail;
    CALayer *_maskContainerLayer;
    CALayer *_maskTopLayer;
    CALayer *_maskLeftLayer;
    CALayer *_maskRightLayer;
    UIView *_localRotationView;
    struct CGAffineTransform _localTransform;
}


// Remaining properties
@property(retain, nonatomic) UIView *arrowContainer; // @synthesize arrowContainer=_arrowContainer;
@property(retain, nonatomic) _UILegibilityView *arrowHead; // @synthesize arrowHead=_arrowHead;
@property(retain, nonatomic) _UILegibilityView *arrowTail; // @synthesize arrowTail=_arrowTail;
@property(retain, nonatomic) SBUILegibilityLabel *callToActionLabel; // @synthesize callToActionLabel=_callToActionLabel;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
@property(retain, nonatomic) UIView *localRotationView; // @synthesize localRotationView=_localRotationView;
@property(nonatomic) struct CGAffineTransform localTransform; // @synthesize localTransform=_localTransform;
@property(retain, nonatomic) CALayer *maskContainerLayer; // @synthesize maskContainerLayer=_maskContainerLayer;
@property(retain, nonatomic) CALayer *maskLeftLayer; // @synthesize maskLeftLayer=_maskLeftLayer;
@property(retain, nonatomic) CALayer *maskRightLayer; // @synthesize maskRightLayer=_maskRightLayer;
@property(retain, nonatomic) CALayer *maskTopLayer; // @synthesize maskTopLayer=_maskTopLayer;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@end

