/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:48:34 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libacmobileshim.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@protocol ACMSignInDialogDelegate <NSObject>
@required
-(void)onIForgot:(id)arg1;
-(void)onSignIn:(id)arg1;
-(void)onSignInCancel:(id)arg1;
-(void)signInDialogWillBecomeEnabled;
-(void)signInDialogDidBecomeEnabled;
-(void)signInDialogWillBecomeDisabled;
-(void)signInDialogDidBecomeDisabled;

@end

