/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:44:07 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libcoreroutine.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@protocol MapsSync.MapsSyncDataQueryDelegate
@optional
-(void)queryIsReadyWithQuery:(id)arg1;
-(void)queryContentsWillChangeWithQuery:(id)arg1;
-(void)queryContentsDidChangeObjectWithQuery:(id)arg1 object:(id)arg2 indexPath:(id)arg3 changeType:(unsigned long long)arg4 newIndexPath:(id)arg5;
-(void)queryContentsDidLoadWithQuery:(id)arg1;

@required
-(void)queryContentsDidChangeWithQuery:(id)arg1;

@end

