/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:44:08 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libcoreroutine.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@interface RTLaunchServices : NSObject
+(void)createProcessAssertionForPid:(int)arg1 timeout:(double)arg2 queue:(id)arg3 timeoutHandler:(/*^block*/id)arg4 ;
+(void)launchClientWithBundleIdentifier:(id)arg1 restorationIdentifier:(id)arg2 eventAgentManager:(id)arg3 handler:(/*^block*/id)arg4 ;
+(BOOL)canOpenApplication:(id)arg1 ;
@end

