/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:44:07 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libcoreroutine.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <libcoreroutine.dylib/RTManagedConfiguration.h>

@interface RTManagedConfiguration_Embedded : RTManagedConfiguration
-(BOOL)effectiveBoolValueForSetting:(id)arg1 ;
-(void)profileConnectionDidReceiveEffectiveSettingsChangedNotification:(id)arg1 userInfo:(id)arg2 ;
-(BOOL)isDiagnosticsAndUsageAllowed;
-(id)stringToManagedConfigurationKey:(id)arg1 ;
-(void)setDelegate:(id)arg1 ;
-(BOOL)isFindMyCarAllowed;
-(void)dealloc;
@end

