/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:44:08 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libcoreroutine.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <libcoreroutine.dylib/libcoreroutine.dylib-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class RTTokenBucket;

@interface RTPersistenceMirroringPolicy : NSObject <NSCopying> {

	long long _qualityOfService;
	RTTokenBucket* _tokenBucket;

}

@property (nonatomic,retain) RTTokenBucket * tokenBucket;                    //@synthesize tokenBucket=_tokenBucket - In the implementation block
@property (nonatomic,readonly) long long qualityOfService;                   //@synthesize qualityOfService=_qualityOfService - In the implementation block
@property (nonatomic,readonly) BOOL allowsMirroringViaCellular; 
@property (nonatomic,readonly) BOOL mirroringOperationAllowed; 
-(id)init;
-(long long)qualityOfService;
-(id)initWithQualityOfService:(long long)arg1 ;
-(double)timeIntervalUntilOperationAllowed;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(BOOL)mirroringOperationAllowed;
-(BOOL)allowsMirroringViaCellular;
-(id)initWithQualityOfService:(long long)arg1 tokenBucket:(id)arg2 ;
-(RTTokenBucket *)tokenBucket;
-(id)qualityOfServiceToString:(long long)arg1 ;
-(void)setTokenBucket:(RTTokenBucket *)arg1 ;
@end

