/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:44:08 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libcoreroutine.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@class RTMapItem;

@interface RTPinnedPlace : NSObject {

	unsigned long long _type;
	RTMapItem* _mapItem;

}

@property (nonatomic,readonly) unsigned long long type;              //@synthesize type=_type - In the implementation block
@property (nonatomic,readonly) RTMapItem * mapItem;                  //@synthesize mapItem=_mapItem - In the implementation block
-(id)init;
-(id)description;
-(RTMapItem *)mapItem;
-(unsigned long long)type;
-(id)initWithType:(unsigned long long)arg1 mapItem:(id)arg2 ;
@end

