/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:44:07 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libcoreroutine.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@interface RTRuntime : NSObject
+(id)classesFromImages:(id)arg1 ;
+(id)subclassesOfClass:(Class)arg1 images:(id)arg2 includeParentClass:(BOOL)arg3 ;
+(id)routineImageNames;
+(id)directSubclassesOfClass:(Class)arg1 images:(id)arg2 includeParentClass:(BOOL)arg3 ;
+(id)routineClassStrings;
+(id)routineSubclassesOfClass:(Class)arg1 ;
+(id)routineClasses;
@end

