/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:44:07 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libcoreroutine.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSMutableDictionary;

@interface RTStateModelLegacy : NSObject <NSSecureCoding> {

	long long _version;
	NSMutableDictionary* _stateModelLut;

}

@property (assign,nonatomic) long long version;                                //@synthesize version=_version - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * stateModelLut;              //@synthesize stateModelLut=_stateModelLut - In the implementation block
+(BOOL)supportsSecureCoding;
-(void)setVersion:(long long)arg1 ;
-(long long)version;
-(void)encodeWithCoder:(id)arg1 ;
-(id)description;
-(void)setStateModelLut:(NSMutableDictionary *)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(NSMutableDictionary *)stateModelLut;
@end

