/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:44:08 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libcoreroutine.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <Foundation/NSProxy.h>

@protocol RTTransientObjectProtocol;
@class RTTimer, RTTimerManager, NSRecursiveLock;

@interface RTTransientObject : NSProxy {

	id<RTTransientObjectProtocol> _transientObjectDelegate;
	/*^block*/id _backingObjectCreationBlock;
	id _backingObject;
	double _backingObjectExpirationTimeInterval;
	RTTimer* _backingObjectExpirationTimer;
	RTTimerManager* _timerManager;
	NSRecursiveLock* _lock;
	double _lastForwardedMessageTimeInterval;

}

@property (nonatomic,copy) id backingObjectCreationBlock;                                               //@synthesize backingObjectCreationBlock=_backingObjectCreationBlock - In the implementation block
@property (nonatomic,retain) id backingObject;                                                          //@synthesize backingObject=_backingObject - In the implementation block
@property (assign,nonatomic) double backingObjectExpirationTimeInterval;                                //@synthesize backingObjectExpirationTimeInterval=_backingObjectExpirationTimeInterval - In the implementation block
@property (nonatomic,retain) RTTimer * backingObjectExpirationTimer;                                    //@synthesize backingObjectExpirationTimer=_backingObjectExpirationTimer - In the implementation block
@property (nonatomic,retain) RTTimerManager * timerManager;                                             //@synthesize timerManager=_timerManager - In the implementation block
@property (nonatomic,retain) NSRecursiveLock * lock;                                                    //@synthesize lock=_lock - In the implementation block
@property (assign,nonatomic) double lastForwardedMessageTimeInterval;                                   //@synthesize lastForwardedMessageTimeInterval=_lastForwardedMessageTimeInterval - In the implementation block
@property (assign,nonatomic,__weak) id<RTTransientObjectProtocol> transientObjectDelegate;              //@synthesize transientObjectDelegate=_transientObjectDelegate - In the implementation block
-(NSRecursiveLock *)lock;
-(void)setTimerManager:(RTTimerManager *)arg1 ;
-(RTTimerManager *)timerManager;
-(void)__handleBackingObjectTimerExpired;
-(void)setTransientObjectDelegate:(id<RTTransientObjectProtocol>)arg1 ;
-(double)lastForwardedMessageTimeInterval;
-(void)setLastForwardedMessageTimeInterval:(double)arg1 ;
-(void)setBackingObject:(id)arg1 ;
-(id)initWithCreationBlock:(/*^block*/id)arg1 timeout:(double)arg2 ;
-(void)setLock:(NSRecursiveLock *)arg1 ;
-(id)backingObjectCreationBlock;
-(void)setBackingObjectExpirationTimeInterval:(double)arg1 ;
-(void)touch;
-(void)setBackingObjectCreationBlock:(id)arg1 ;
-(void)__createTimerAssociatedWithBackingObject;
-(id)methodSignatureForSelector:(SEL)arg1 ;
-(RTTimer *)backingObjectExpirationTimer;
-(id)__createBackingObject;
-(void)setBackingObjectExpirationTimer:(RTTimer *)arg1 ;
-(id)backingObject;
-(void)__invalidateBackingObject;
-(id<RTTransientObjectProtocol>)transientObjectDelegate;
-(void)forwardInvocation:(id)arg1 ;
-(void)dealloc;
-(double)backingObjectExpirationTimeInterval;
-(id)initWithCreationBlock:(/*^block*/id)arg1 timeout:(double)arg2 timerManager:(id)arg3 ;
@end

