/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:44:07 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libcoreroutine.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@class UNUserNotificationCenter;

@interface RTUserNotifications : NSObject {

	UNUserNotificationCenter* _notificationCenter;

}

@property (nonatomic,retain) UNUserNotificationCenter * notificationCenter;              //@synthesize notificationCenter=_notificationCenter - In the implementation block
-(UNUserNotificationCenter *)notificationCenter;
-(id)init;
-(void)setNotificationCenter:(UNUserNotificationCenter *)arg1 ;
-(id)initWithBundleIdentifier:(id)arg1 ;
-(void)postNotificationWithTitle:(id)arg1 message:(id)arg2 ;
@end

