/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:44:07 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libcoreroutine.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <libcoreroutine.dylib/libcoreroutine.dylib-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface RTVisitMonitorStatus : NSObject <NSCopying> {

	BOOL _monitoringVisitIncidents;
	BOOL _monitoringLeechedVisitIncidents;
	BOOL _monitoringLowConfidenceVisitIncidents;
	unsigned long long _feedBufferReferenceCounter;

}

@property (assign,nonatomic) BOOL monitoringVisitIncidents;                              //@synthesize monitoringVisitIncidents=_monitoringVisitIncidents - In the implementation block
@property (assign,nonatomic) BOOL monitoringLeechedVisitIncidents;                       //@synthesize monitoringLeechedVisitIncidents=_monitoringLeechedVisitIncidents - In the implementation block
@property (assign,nonatomic) BOOL monitoringLowConfidenceVisitIncidents;                 //@synthesize monitoringLowConfidenceVisitIncidents=_monitoringLowConfidenceVisitIncidents - In the implementation block
@property (assign,nonatomic) unsigned long long feedBufferReferenceCounter;              //@synthesize feedBufferReferenceCounter=_feedBufferReferenceCounter - In the implementation block
-(BOOL)invalid;
-(void)setMonitoringLowConfidenceVisitIncidents:(BOOL)arg1 ;
-(BOOL)monitoringLeechedVisitIncidents;
-(id)description;
-(unsigned long long)feedBufferReferenceCounter;
-(BOOL)monitoringVisitIncidents;
-(void)setMonitoringLeechedVisitIncidents:(BOOL)arg1 ;
-(void)setFeedBufferReferenceCounter:(unsigned long long)arg1 ;
-(BOOL)monitoringLowConfidenceVisitIncidents;
-(void)setMonitoringVisitIncidents:(BOOL)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)initWithMonitoringVisitIncidents:(BOOL)arg1 monitoringLeechedVisitIncidents:(BOOL)arg2 monitoringLowConfidenceVisitIncidents:(BOOL)arg3 feedBufferReferenceCounter:(unsigned long long)arg4 ;
@end

