/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:44:08 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libcoreroutine.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@class RTLocation, NSArray;

@interface RTVisitLocationPoints : NSObject {

	RTLocation* _centroid;
	NSArray* _locations;

}

@property (nonatomic,readonly) NSArray * locations;                //@synthesize locations=_locations - In the implementation block
@property (nonatomic,readonly) RTLocation * centroid;              //@synthesize centroid=_centroid - In the implementation block
-(id)init;
-(id)initWithLocations:(id)arg1 ;
-(id)description;
-(id)firstDate;
-(void)enumerateLowSpeedSegementsUsingBlock:(id)arg1 block:(/*^block*/id)arg2 ;
-(RTLocation *)centroid;
-(id)lastDate;
-(double)duration;
-(NSArray *)locations;
@end

