//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class BSServiceConnection;
@protocol SBSAccessibilityWindowHostingClientToServerInterface;

@interface _SBAccessibilityWindowHostingControllerServerTarget : NSObject
{
    BSServiceConnection *_connection;
    id <SBSAccessibilityWindowHostingClientToServerInterface> _proxyInterface;
}


// Remaining properties
@property(readonly, nonatomic) __weak BSServiceConnection *connection; // @synthesize connection=_connection;
@property(nonatomic) __weak id <SBSAccessibilityWindowHostingClientToServerInterface> proxyInterface; // @synthesize proxyInterface=_proxyInterface;
@end

