//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/NSCopying-Protocol.h>

@class SBAppLayout, SBDisplayItem;

@interface _SBAppSwitcherSnapshotCacheKey : NSObject <NSCopying>
{
    unsigned long long _hash;
    SBAppLayout *_appLayout;
    SBDisplayItem *_displayItem;
}


// Remaining properties
@property(readonly, nonatomic) SBAppLayout *appLayout; // @synthesize appLayout=_appLayout;
@property(readonly, nonatomic) SBDisplayItem *displayItem; // @synthesize displayItem=_displayItem;
@end

