//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class SBFluidSwitcherGestureExclusionCompositeShape;

@interface _SBFluidSwitcherGestureExclusionCompositeShapeDebugView : UIView
{
    SBFluidSwitcherGestureExclusionCompositeShape *_compositeShape;
}


// Remaining properties
@property(retain, nonatomic) SBFluidSwitcherGestureExclusionCompositeShape *compositeShape; // @synthesize compositeShape=_compositeShape;
@end

