//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIImage;

@interface _SBUserNotificationImageDescriptor : NSObject
{
    NSString *_imagePath;
    NSString *_catalogPath;
    NSString *_catalogKey;
    UIImage *_lazy_image;
}


// Remaining properties
@property(readonly, nonatomic) UIImage *image;
@end

