//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/BSInvalidatable-Protocol.h>

@class NSDate, NSString, SBApplication;
@protocol BSTimer, SBApplicationWakeLifecycleHandling;

@interface SBApplicationWakeScheduler : NSObject <BSInvalidatable>
{
    id <SBApplicationWakeLifecycleHandling> _lifecycleTracker;
    SBApplication *_application;
    _Bool _invalidated;
    id <BSTimer> _wakeTimer;
    id <BSTimer> _wakeSuspendTimer;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSDate *scheduledDate;
@property(readonly) Class superclass;
@property(retain, nonatomic) id <BSTimer> wakeSuspendTimer; // @synthesize wakeSuspendTimer=_wakeSuspendTimer;
@property(retain, nonatomic) id <BSTimer> wakeTimer; // @synthesize wakeTimer=_wakeTimer;
@end

