//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <SpringBoard/BSInvalidatable-Protocol.h>
#import <SpringBoard/SBApplicationHosting-Protocol.h>
#import <SpringBoard/SBApplicationSceneViewControlling-Protocol.h>
#import <SpringBoard/SBDeviceApplicationSceneHandleObserver-Protocol.h>

@class NSMutableSet, NSSet, NSString, SBActivationSettings, SBApplicationSceneHandle, SBApplicationSceneView, SBDeviceApplicationSceneHandle, SBDeviceApplicationSceneViewController, UIView;
@protocol SBAppViewControllerDelegate, SBApplicationSceneViewControllingStatusBarDelegate, SBScenePlaceholderContentContext;

@interface SBAppViewController : UIViewController <SBDeviceApplicationSceneHandleObserver, SBApplicationHosting, SBApplicationSceneViewControlling, BSInvalidatable>
{
    NSString *_identifier;
    SBDeviceApplicationSceneHandle *_sceneHandle;
    SBDeviceApplicationSceneViewController *_deviceAppViewController;
    SBActivationSettings *_activationSettings;
    id <SBScenePlaceholderContentContext> _placeholderContentContext;
    NSMutableSet *_activeTransitions;
    NSSet *_actionsToDeliver;
    long long _requestedMode;
    long long _currentMode;
    _Bool _sceneContentIsReady;
    _Bool _ignoresOcclusions;
    _Bool _invalidated;
    _Bool _automatesLifecycle;
    _Bool _placeholderContentEnabled;
    _Bool _wantsSecureRendering;
    id <SBApplicationSceneViewControllingStatusBarDelegate> applicationSceneStatusBarDelegate;
    id <SBAppViewControllerDelegate> _delegate;
    SBActivationSettings *_supplementalActivationSettings;
}


// Remaining properties
@property(retain, nonatomic) NSSet *actionsToDeliver; // @synthesize actionsToDeliver=_actionsToDeliver;
@property(readonly, nonatomic) SBApplicationSceneView *appView;
@property(nonatomic) __weak id <SBApplicationSceneViewControllingStatusBarDelegate> applicationSceneStatusBarDelegate; // @synthesize applicationSceneStatusBarDelegate;
@property(nonatomic) _Bool automatesLifecycle; // @synthesize automatesLifecycle=_automatesLifecycle;
@property(readonly, nonatomic) long long contentInterfaceOrientation;
@property(readonly, nonatomic) struct CGSize contentReferenceSize;
@property(readonly, nonatomic) long long currentMode; // @synthesize currentMode=_currentMode;
@property(retain, nonatomic) UIView *customContentView;
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <SBAppViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) long long displayMode;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool ignoresOcclusions; // @synthesize ignoresOcclusions=_ignoresOcclusions;
@property(readonly, nonatomic) long long overrideStatusBarStyle;
@property(retain, nonatomic) id <SBScenePlaceholderContentContext> placeholderContentContext; // @synthesize placeholderContentContext=_placeholderContentContext;
@property(nonatomic) _Bool placeholderContentEnabled; // @synthesize placeholderContentEnabled=_placeholderContentEnabled;
@property(nonatomic) long long requestedMode; // @synthesize requestedMode=_requestedMode;
@property(readonly, nonatomic) SBApplicationSceneHandle *sceneHandle; // @synthesize sceneHandle=_sceneHandle;
@property(readonly, nonatomic) double statusBarAlpha;
@property(readonly) Class superclass;
@property(retain, nonatomic) SBActivationSettings *supplementalActivationSettings; // @synthesize supplementalActivationSettings=_supplementalActivationSettings;
@property(nonatomic) _Bool wantsSecureRendering; // @synthesize wantsSecureRendering=_wantsSecureRendering;
@end

