//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardUI/SBSceneHandle.h>

@class NSHashTable, NSString, SBApplication;

@interface SBApplicationSceneHandle : SBSceneHandle
{
    SBApplication *_application;
    NSString *_persistenceIdentifier;
    _Bool _isSecure;
    NSHashTable *_sceneUpdateContributers;
    unsigned long long _userLaunchSignpostID;
    double _userLaunchEventTime;
    long long _layoutRole;
}


// Remaining properties
@property(readonly, nonatomic) SBApplication *application; // @synthesize application=_application;
@property(nonatomic) long long layoutRole; // @synthesize layoutRole=_layoutRole;
@property(readonly, nonatomic) NSString *persistenceIdentifier; // @synthesize persistenceIdentifier=_persistenceIdentifier;
@property(readonly, nonatomic, getter=isSecure) _Bool secure; // @synthesize secure=_isSecure;
@end

