//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBWorkspaceEntity.h>

#import <SpringBoard/SBProcessSettings-Protocol.h>

@class NSMutableSet, NSSet, NSString, SBApplication, SBApplicationSceneHandle, SBProcessSettings;

@interface SBApplicationSceneEntity : SBWorkspaceEntity <SBProcessSettings>
{
    SBApplicationSceneHandle *_sceneHandle;
    NSMutableSet *_actions;
    SBProcessSettings *_processSettings;
}


// Remaining properties
@property(readonly, copy, nonatomic) NSSet *actions; // @synthesize actions=_actions;
@property(readonly, nonatomic) SBApplication *application;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) SBProcessSettings *processSettings; // @synthesize processSettings=_processSettings;
@property(readonly, nonatomic) SBApplicationSceneHandle *sceneHandle; // @synthesize sceneHandle=_sceneHandle;
@property(readonly) Class superclass;
@end

