//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSHashTable, SBHIDUILockAssertion, SBIdleTimerDefaults;

@interface SBBacklightController : NSObject
{
    SBIdleTimerDefaults *_idleTimerDefaults;
    _Bool _isPendingScreenUnblankAfterCACommit;
    NSHashTable *_observers;
    NSHashTable *_informers;
    long long _lastBacklightChangeSource;
    SBHIDUILockAssertion *_currentHIDUILockAssertion;
}


// Remaining properties
@property(readonly, nonatomic) double backlightFactor;
@property(retain, nonatomic) SBHIDUILockAssertion *currentHIDUILockAssertion; // @synthesize currentHIDUILockAssertion=_currentHIDUILockAssertion;
@property(readonly, nonatomic) _Bool isPendingScreenUnblankAfterCACommit; // @synthesize isPendingScreenUnblankAfterCACommit=_isPendingScreenUnblankAfterCACommit;
@property(readonly, nonatomic) long long lastBacklightChangeSource; // @synthesize lastBacklightChangeSource=_lastBacklightChangeSource;
@property(readonly, nonatomic) _Bool screenIsDim;
@property(readonly, nonatomic) _Bool screenIsOn;
@end

