//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/NSCopying-Protocol.h>
#import <SpringBoard/NSMutableCopying-Protocol.h>

@interface SBBannerUnfurlSourceContext : NSObject <NSCopying, NSMutableCopying>
{
    double _cornerRadius;
    struct CGRect _referenceCoordinateSpaceBounds;
    struct CGRect _referenceFrame;
    struct CGPoint _referenceVelocity;
}


// Remaining properties
@property(readonly, nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(readonly, nonatomic) struct CGRect referenceCoordinateSpaceBounds; // @synthesize referenceCoordinateSpaceBounds=_referenceCoordinateSpaceBounds;
@property(readonly, nonatomic) struct CGRect referenceFrame; // @synthesize referenceFrame=_referenceFrame;
@property(readonly, nonatomic) struct CGPoint referenceVelocity; // @synthesize referenceVelocity=_referenceVelocity;
@end

