//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBIconContinuityInfo-Protocol.h>

@class NSDate, NSString, NSURL, NSUUID;

@interface SBBestAppSuggestion : NSObject <SBIconContinuityInfo>
{
}


// Remaining properties
@property(readonly, copy, nonatomic) NSString *activityType;
@property(readonly, copy, nonatomic) NSString *bundleIdentifier;
@property(readonly, copy, nonatomic) NSDate *lastUpdateTime;
@property(readonly, copy, nonatomic) NSURL *launchURL;
@property(readonly, copy, nonatomic) NSString *originatingBundleIdentifier;
@property(readonly, copy, nonatomic) NSString *originatingDeviceIdentifier;
@property(readonly, copy, nonatomic) NSString *originatingDeviceName;
@property(readonly, copy, nonatomic) NSString *originatingDeviceType;
@property(readonly, copy, nonatomic) NSString *suggestedLocationName;
@property(readonly, copy, nonatomic) NSUUID *uniqueIdentifier;
@end

