//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardHome/SBLeafIcon.h>

@class NSURL, SBBookmark, UIWebClip;

@interface SBBookmarkIcon : SBLeafIcon
{
    SBBookmark *_bookmark;
}


// Remaining properties
@property(retain, nonatomic) SBBookmark *bookmark; // @synthesize bookmark=_bookmark;
@property(readonly, nonatomic) _Bool displaysShareBookmarkShortcutItem;
@property(readonly, nonatomic) NSURL *launchURL;
@property(readonly, nonatomic) _Bool representsWebApp;
@property(readonly, nonatomic) UIWebClip *webClip;
@end

