//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <SpringBoard/SBIconViewDelegate-Protocol.h>

@class MTMaterialShadowView, NSLayoutConstraint, NSMutableArray, NSMutableOrderedSet, NSString, SBIconController, SBIconModel, SBIconView, UIHoverGestureRecognizer, UILabel, UIPanGestureRecognizer, UIStackView, UITapGestureRecognizer, UIView;
@protocol SBCommandTabViewControllerDelegate;

@interface SBCommandTabViewController : UIViewController <SBIconViewDelegate>
{
    NSMutableOrderedSet *_recentDisplayItems;
    unsigned long long _selectedIndex;
    SBIconController *_iconController;
    SBIconModel *_iconModel;
    NSMutableArray *_iconViews;
    MTMaterialShadowView *_backgroundMaterialView;
    UIView *_blurredBackgroundView;
    UIView *_selectionSquareView;
    SBIconView *_selectedIconView;
    UILabel *_selectedIconLabel;
    NSLayoutConstraint *_selectionXLayoutConstraint;
    NSLayoutConstraint *_selectedLabelXConstraint;
    NSLayoutConstraint *_selectedLabelBottomConstraint;
    UIStackView *_stackView;
    SBIconView *_homeIconView;
    UIPanGestureRecognizer *_panGestureRecognizer;
    UITapGestureRecognizer *_tapDismissGestureRecognizer;
    UIHoverGestureRecognizer *_hoverGestureRecognizer;
    struct CGPoint _lastHoverLocation;
    _Bool _isTouchDown;
    _Bool _isIconSelected;
    id <SBCommandTabViewControllerDelegate> _delegate;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <SBCommandTabViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

