//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/NSObject-Protocol.h>

@protocol SBCoverSheetGrabberDelegate <NSObject>
- (void)updateVisibilityForGrabberVisible:(_Bool)arg1;
- (unsigned long long)screenEdgesDeferringSystemGestures;
- (_Bool)hasFirstSwipeShowGrabberOverride;
@end

