//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBDataPlanAlertItem.h>

#import <SpringBoard/SBDataPlanAlertActions-Protocol.h>

@class NSURL;

@interface SBDataPlanAccountAlertItem : SBDataPlanAlertItem <SBDataPlanAlertActions>
{
    NSURL *_accountURL;
}


// Remaining properties
@property(copy, nonatomic) NSURL *accountURL; // @synthesize accountURL=_accountURL;
@end

