//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/CSStatusBarControlling-Protocol.h>

@class NSCountedSet, NSNumber, NSString, SBAppStatusBarSettingsAssertion, SBMainStatusBarContentAssertion, SBMainStatusBarStateProvider, _UILegibilitySettings;

@interface SBDashBoardStatusBarController : NSObject <CSStatusBarControlling>
{
    NSCountedSet *_statusBarHiddenReasons;
    SBAppStatusBarSettingsAssertion *_hideStatusBarAssertion;
    SBAppStatusBarSettingsAssertion *_statusBarParametersAssertion;
    SBMainStatusBarContentAssertion *_statusBarContentAssertion;
    SBMainStatusBarStateProvider *_lazy_stateProvider;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSNumber *statusBarAlpha;
@property(readonly, nonatomic) _UILegibilitySettings *statusBarLegibilitySettings;
@property(readonly, nonatomic) long long statusBarStyle;
@property(readonly) Class superclass;
@end

