//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/CSModalHomeAffordanceControlling-Protocol.h>

@class NSString, SBHomeGestureArbiter, SBHomeGestureParticipant, UIScreenEdgePanGestureRecognizer;

@interface SBDashBoardModalHomeAffordanceController : NSObject <CSModalHomeAffordanceControlling>
{
    SBHomeGestureArbiter *_homeGestureArbiter;
    SBHomeGestureParticipant *_participant;
    UIScreenEdgePanGestureRecognizer *_homeGestureRecognizer;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) UIScreenEdgePanGestureRecognizer *homeGestureRecognizer; // @synthesize homeGestureRecognizer=_homeGestureRecognizer;
@property(readonly) Class superclass;
@end

