//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SBDeviceApplicationSceneHandle, SBIsolatedSceneOrientationFollowingWrapperViewController, UIViewController;
@protocol SBDeviceApplicationSceneOverlayViewProviderDelegate;

@interface SBDeviceApplicationSceneOverlayViewProvider : NSObject
{
    SBIsolatedSceneOrientationFollowingWrapperViewController *_orientationWrapperViewController;
    id <SBDeviceApplicationSceneOverlayViewProviderDelegate> _delegate;
    SBDeviceApplicationSceneHandle *_sceneHandle;
}


// Remaining properties
@property(readonly, nonatomic) __weak id <SBDeviceApplicationSceneOverlayViewProviderDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) UIViewController *overlayViewController;
@property(readonly, nonatomic) long long preferredStatusBarStyle;
@property(readonly, nonatomic) long long priority;
@property(retain, nonatomic) SBDeviceApplicationSceneHandle *sceneHandle; // @synthesize sceneHandle=_sceneHandle;
@property(readonly, nonatomic) _Bool wantsResignActiveAssertion;
@end

