//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/BSInvalidatable-Protocol.h>

@class NSString, SBDeviceOrientationUpdateManager;

@interface SBDeviceOrientationUpdateDeferralAssertion : NSObject <BSInvalidatable>
{
    _Bool _invalidated;
    NSString *_reason;
    SBDeviceOrientationUpdateManager *_hackyBackReference;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic, setter=_setHackyBackReference:) __weak SBDeviceOrientationUpdateManager *hackyBackReference; // @synthesize hackyBackReference=_hackyBackReference;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic, getter=isInvalidated) _Bool invalidated; // @synthesize invalidated=_invalidated;
@property(readonly, copy, nonatomic) NSString *reason; // @synthesize reason=_reason;
@property(readonly) Class superclass;
@end

