//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/BSInvalidatable-Protocol.h>
#import <SpringBoard/SBDeviceApplicationSceneHandleObserver-Protocol.h>
#import <SpringBoard/SBSceneViewPresentationConfiguring-Protocol.h>
#import <SpringBoard/SBSwitcherLiveContentOverlay-Protocol.h>

@class NSString, SBDeviceApplicationSceneHandle, SBDeviceApplicationSceneView, SBOrientationTransformWrapperView, UIApplicationSceneSettingsDiffInspector, UIView;

@interface SBDeviceApplicationSceneViewLiveContentOverlay : NSObject <BSInvalidatable, SBDeviceApplicationSceneHandleObserver, SBSceneViewPresentationConfiguring, SBSwitcherLiveContentOverlay>
{
    SBOrientationTransformWrapperView *_transformWrapperView;
    SBDeviceApplicationSceneHandle *_sceneHandle;
    UIApplicationSceneSettingsDiffInspector *_sceneSettingsInspector;
    SBDeviceApplicationSceneView *_sceneView;
    long long _containerOrientation;
}


// Remaining properties
@property(nonatomic) long long containerOrientation; // @synthesize containerOrientation=_containerOrientation;
@property(readonly, nonatomic) UIView *contentOverlayView;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

