//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBApplicationSceneHandle.h>

#import <SpringBoard/FBApplicationProcessObserver-Protocol.h>
#import <SpringBoard/SBIdleTimerProviding-Protocol.h>

@class NSData, NSDictionary, NSMutableSet, NSString, SBDeviceApplicationSceneStatusBarBreadcrumbProvider, SBDeviceApplicationSceneStatusBarStateProvider, SBModalAlertPresenter, _UIStatusBarData;
@protocol SBIdleTimerCoordinating;

@interface SBDeviceApplicationSceneHandle : SBApplicationSceneHandle <FBApplicationProcessObserver, SBIdleTimerProviding>
{
    long long _lastActivationSource;
    SBModalAlertPresenter *_modalAlertPresenter;
    int _statusBarStyleOverridesToSuppress;
    long long _whitePointAdaptivityStyle;
    NSMutableSet *_statusBarForcedHiddenReasons;
    _Bool _hasMainSceneBeenForegroundAtLeastOnce;
    _Bool _isEffectivelyForeground;
    unsigned long long _keyboardLayerMaskStyle;
    long long _statusBarParts;
    NSDictionary *_alertSuppressionContextsBySectionIdentifier;
    id <SBIdleTimerCoordinating> _idleTimerCoordinator;
    SBDeviceApplicationSceneStatusBarBreadcrumbProvider *_breadcrumbProvider;
    SBDeviceApplicationSceneStatusBarStateProvider *_statusBarStateProvider;
    NSString *_lastActivationIconLeafIdentifier;
    struct CGRect _statusBarAvoidanceFrame;
}


// Remaining properties
@property(readonly, nonatomic) long long activationBias;
@property(readonly, copy, nonatomic) NSData *activationConditionsData;
@property(readonly, nonatomic) long long backgroundStyle;
@property(readonly, nonatomic) SBDeviceApplicationSceneStatusBarBreadcrumbProvider *breadcrumbProvider; // @synthesize breadcrumbProvider=_breadcrumbProvider;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic, getter=isEffectivelyForeground) _Bool effectivelyForeground; // @synthesize effectivelyForeground=_isEffectivelyForeground;
@property(nonatomic) _Bool hasMainSceneBeenForegroundAtLeastOnce; // @synthesize hasMainSceneBeenForegroundAtLeastOnce=_hasMainSceneBeenForegroundAtLeastOnce;
@property(readonly) unsigned long long hash;
@property(nonatomic, getter=_idleTimerCoordinator, setter=_setIdleTimerCoordinator:) __weak id <SBIdleTimerCoordinating> idleTimerCoordinator; // @synthesize idleTimerCoordinator=_idleTimerCoordinator;
@property(copy, nonatomic) NSString *lastActivationIconLeafIdentifier; // @synthesize lastActivationIconLeafIdentifier=_lastActivationIconLeafIdentifier;
@property(nonatomic) long long lastActivationSource; // @synthesize lastActivationSource=_lastActivationSource;
@property(readonly, copy, nonatomic) _UIStatusBarData *overlayStatusBarData;
@property(readonly, nonatomic, getter=isReachabilitySupported) _Bool reachabilitySupported;
@property(readonly, copy, nonatomic) NSString *sceneTitle;
@property(readonly, nonatomic) unsigned long long screenEdgesDeferringSystemGestures;
@property(readonly, nonatomic, getter=isShowingModalAlert) _Bool showingModalAlert;
@property(nonatomic) struct CGRect statusBarAvoidanceFrame; // @synthesize statusBarAvoidanceFrame=_statusBarAvoidanceFrame;
@property(nonatomic) long long statusBarParts;
@property(readonly, nonatomic) SBDeviceApplicationSceneStatusBarStateProvider *statusBarStateProvider;
@property(nonatomic) int statusBarStyleOverridesToSuppress; // @synthesize statusBarStyleOverridesToSuppress=_statusBarStyleOverridesToSuppress;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isTranslucent) _Bool translucent;
@property(readonly, nonatomic) long long wallpaperStyle;
@property(nonatomic) long long whitePointAdaptivityStyle; // @synthesize whitePointAdaptivityStyle=_whitePointAdaptivityStyle;
@end

