//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBAVSystemControllerDirectToAirPlayObserver-Protocol.h>
#import <SpringBoard/SBControlCenterObserver-Protocol.h>
#import <SpringBoard/SBMainDisplaySceneManagerObserver-Protocol.h>

@class AVExternalPlaybackMonitor, AVRoutingSessionDestination, AVRoutingSessionManager, MPMediaControlsStatusBarStyleOverridesCoordinator, NSArray, NSMutableDictionary, NSMutableSet, NSString, SBSStatusBarStyleOverridesAssertion, _SBDirectToAirPlayPolicyState;

@interface SBDirectToAirPlayController : NSObject <SBMainDisplaySceneManagerObserver, SBAVSystemControllerDirectToAirPlayObserver, SBControlCenterObserver>
{
    SBSStatusBarStyleOverridesAssertion *_directToAirPlayStatusBarStyleOverrideAssertion;
    NSString *_directToAirPlayStatusBarStyleOverrideAssertionCorrespondingBundleID;
    NSMutableDictionary *_directToAirPlayPlayingBundleIDsToRouteNames;
    NSMutableDictionary *_directToAirPlayReadyBundleIDsToRouteNames;
    NSMutableSet *_directToAirPlayIneligibleBundleIDs;
    NSMutableSet *_directToAirPlayEligibleBundleIDs;
    _Bool _controlCenterReportsItselfAsPresented;
    _Bool _currentRoutingSessionEstablishedAutomaticallyFromLikelyDestination;
    _Bool _externalPlaybackIsActive;
    _Bool _externalPlaybackIsPlaying;
    MPMediaControlsStatusBarStyleOverridesCoordinator *_mediaControlsCoordinator;
    AVExternalPlaybackMonitor *_externalPlaybackMonitor;
    AVRoutingSessionManager *_routingSessionManager;
    AVRoutingSessionDestination *_currentRoutingSessionDestination;
    NSArray *_likelyExternalPlaybackDestinations;
    _SBDirectToAirPlayPolicyState *_currentState;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

