//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString;

@interface SBDistanceFieldView : UIView
{
}


// Remaining properties
@property struct CGColor *foregroundColor;
@property _Bool invertsShape;
@property double lineWidth;
@property double offset;
@property(copy, nonatomic) NSString *renderMode;
@property double sharpness;
@end

