//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBGestureSwitcherModifierEvent.h>

@class NSString;

@interface SBDragAndDropGestureSwitcherModifierEvent : SBGestureSwitcherModifierEvent
{
    long long _dropAction;
    NSString *_draggedSceneIdentifier;
    double _platterScale;
    struct CGRect _platterViewFrame;
}


// Remaining properties
@property(retain, nonatomic) NSString *draggedSceneIdentifier; // @synthesize draggedSceneIdentifier=_draggedSceneIdentifier;
@property(nonatomic) long long dropAction; // @synthesize dropAction=_dropAction;
@property(nonatomic) double platterScale; // @synthesize platterScale=_platterScale;
@property(nonatomic) struct CGRect platterViewFrame; // @synthesize platterViewFrame=_platterViewFrame;
@end

