//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/BSInvalidatable-Protocol.h>
#import <SpringBoard/SBSceneHandleObserver-Protocol.h>

@class BSAtomicSignal, CADisplay, CADisplayMode, FBSDisplayConfiguration, FBSDisplayIdentity, FBSDisplayLayoutPublisher, FBScene, NSString, SBApplication, SBApplicationSceneHandle, SBSExternalDisplayLayoutElement, _UIRootWindow;
@protocol BSInvalidatable, OS_dispatch_queue;

@interface SBExternalDisplayPresenter : NSObject <SBSceneHandleObserver, BSInvalidatable>
{
    FBSDisplayLayoutPublisher *_layoutPublisher;
    FBSDisplayIdentity *_identity;
    CADisplay *_caDisplay;
    _Bool _invalidated;
    FBSDisplayConfiguration *_currentConfiguration;
    FBSDisplayConfiguration *_currentReportedConfiguration;
    SBApplication *_foregroundApp;
    SBApplicationSceneHandle *_foregroundAppSceneHandle;
    FBScene *_foregroundAppScene;
    BSAtomicSignal *_foregroundAppSceneTransactionInvalidator;
    NSObject<OS_dispatch_queue> *_displayMutationQueue;
    unsigned long long _displayMutationEnqueuedCount;
    unsigned long long _displayMutationCompletedCount;
    CADisplayMode *_requestedMode;
    NSString *_requestedOverscanAdjustment;
    _UIRootWindow *_rootWindow;
    FBSDisplayConfiguration *_rootWindowConfiguration;
    SBApplicationSceneHandle *_presentationSceneHandle;
    FBScene *_presentationScene;
    BSAtomicSignal *_presentationSceneActivationInvalidator;
    _Bool _hasEnqueuedPresentationUpdate;
    _Bool _presentationSceneHasActivated;
    SBSExternalDisplayLayoutElement *_presentedLayoutElement;
    id <BSInvalidatable> _presentedLayoutElementAssertion;
    NSString *_preventIdleSleepReason;
    SBApplication *_preventIdleSleepApp;
    _Bool _preventIdleSleepPresenting;
    long long _powerMode;
    BSAtomicSignal *_idleOffTimerInvalidation;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

