//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/BSDescriptionProviding-Protocol.h>
#import <SpringBoard/SBAssistantObserver-Protocol.h>
#import <SpringBoard/SBFloatingDockRootViewControllerDelegate-Protocol.h>
#import <SpringBoard/SBFolderPresentationObserver-Protocol.h>
#import <SpringBoard/SBHomeGestureParticipantDelegate-Protocol.h>
#import <SpringBoard/SBIconLocationPresenting-Protocol.h>
#import <SpringBoard/SBIconViewProviding-Protocol.h>
#import <SpringBoard/SBIconViewQuerying-Protocol.h>
#import <SpringBoard/SBLayoutStateTransitionObserver-Protocol.h>
#import <SpringBoard/SBReusableViewMapDelegate-Protocol.h>
#import <SpringBoard/SBRootFolderPageStateObserver-Protocol.h>
#import <SpringBoard/SBSystemGestureRecognizerDelegate-Protocol.h>

@class NSPointerArray, NSSet, NSString, PTToggleTestRecipe, SBApplication, SBDeviceOrientationUpdateDeferralAssertion, SBFAnalyticsClient, SBFailingSystemGestureRecognizer, SBFloatingDockBehaviorAssertion, SBFloatingDockRootViewController, SBFloatingDockViewController, SBFolderController, SBHomeGestureParticipant, SBIconController, SBIconListView, SBIndirectPanGestureRecognizer, SBLayoutStateTransitionCoordinator, SBMainScreenActiveInterfaceOrientationWindow, SBReusableViewMap, UIHoverGestureRecognizer, UIViewController, _UILegibilitySettings;
@protocol BSInvalidatable, SBFloatingDockControllerDelegate;

@interface SBFloatingDockController : NSObject <SBFloatingDockRootViewControllerDelegate, SBFolderPresentationObserver, SBSystemGestureRecognizerDelegate, SBRootFolderPageStateObserver, SBAssistantObserver, BSDescriptionProviding, SBReusableViewMapDelegate, SBLayoutStateTransitionObserver, SBHomeGestureParticipantDelegate, SBIconViewQuerying, SBIconLocationPresenting, SBIconViewProviding>
{
    SBFloatingDockRootViewController *_viewController;
    _Bool _homeScreenTransitioningToTodayView;
    _Bool _homeScreenTodayViewTransitioning;
    NSPointerArray *_floatingDockBehaviorAssertionsByLevel[13];
    NSPointerArray *_floatingDockWindowLevelAssertionsByPriority[5];
    SBFAnalyticsClient *_analyticsClient;
    SBFloatingDockBehaviorAssertion *_inAppFloatingDockBehaviorAssertion;
    SBFloatingDockBehaviorAssertion *_todayViewFloatingDockBehaviorAssertion;
    SBFloatingDockBehaviorAssertion *_iconPullSearchGestureShowingFloatingDockBehaviorAssertion;
    SBFloatingDockBehaviorAssertion *_openFolderOverHomeScreenFloatingDockBehaviorAssertion;
    SBFloatingDockBehaviorAssertion *_openFolderOverSceneLayoutFloatingDockBehaviorAssertion;
    SBFloatingDockBehaviorAssertion *_activeGestureFloatingDockBehaviorAssertion;
    SBFloatingDockBehaviorAssertion *_assistantFloatingDockBehaviorAssertion;
    SBDeviceOrientationUpdateDeferralAssertion *_deferOrientationUpdatesAssertion;
    SBReusableViewMap *_iconViewMap;
    id <BSInvalidatable> _floatingDockStateDumpHandle;
    PTToggleTestRecipe *_testRecipe;
    _Bool _wasFloatingDockPresentedByPointer;
    SBMainScreenActiveInterfaceOrientationWindow *_floatingDockWindow;
    id <SBFloatingDockControllerDelegate> _delegate;
    SBIndirectPanGestureRecognizer *_presentFloatingDockIndirectPanGestureRecognizer;
    UIHoverGestureRecognizer *_dismissFloatingDockHoverGestureRecognizer;
    SBFailingSystemGestureRecognizer *_dismissFloatingDockSystemGestureRecognizer;
    SBIconController *_iconController;
    SBFloatingDockBehaviorAssertion *_activeAssertion;
    SBLayoutStateTransitionCoordinator *_transitionCoordinator;
    SBHomeGestureParticipant *_homeGestureParticipant;
}


// Remaining properties
@property(nonatomic) __weak SBFloatingDockBehaviorAssertion *activeAssertion; // @synthesize activeAssertion=_activeAssertion;
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <SBFloatingDockControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) UIHoverGestureRecognizer *dismissFloatingDockHoverGestureRecognizer; // @synthesize dismissFloatingDockHoverGestureRecognizer=_dismissFloatingDockHoverGestureRecognizer;
@property(readonly, nonatomic) SBFailingSystemGestureRecognizer *dismissFloatingDockSystemGestureRecognizer; // @synthesize dismissFloatingDockSystemGestureRecognizer=_dismissFloatingDockSystemGestureRecognizer;
@property(readonly, nonatomic) double effectiveFloatingDockHeight;
@property(readonly, nonatomic, getter=isFloatingDockFullyPresented) _Bool floatingDockFullyPresented;
@property(readonly, nonatomic) double floatingDockHeight;
@property(readonly, nonatomic, getter=isFloatingDockPresented) _Bool floatingDockPresented;
@property(readonly, nonatomic) struct CGRect floatingDockScreenFrame;
@property(readonly, nonatomic) struct CGRect floatingDockScreenPresentationFrame;
@property(readonly, nonatomic) SBFloatingDockViewController *floatingDockViewController;
@property(readonly, nonatomic) double floatingDockViewTopMargin;
@property(readonly, nonatomic) SBMainScreenActiveInterfaceOrientationWindow *floatingDockWindow; // @synthesize floatingDockWindow=_floatingDockWindow;
@property(readonly, nonatomic, getter=isGesturePossible) _Bool gesturePossible;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) SBHomeGestureParticipant *homeGestureParticipant; // @synthesize homeGestureParticipant=_homeGestureParticipant;
@property(readonly, nonatomic) SBIconController *iconController; // @synthesize iconController=_iconController;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings;
@property(readonly, nonatomic) double maximumDockContinuousCornerRadius;
@property(readonly, nonatomic) double maximumFloatingDockHeight;
@property(readonly, nonatomic) double preferredVerticalMargin;
@property(readonly, nonatomic) SBIndirectPanGestureRecognizer *presentFloatingDockIndirectPanGestureRecognizer; // @synthesize presentFloatingDockIndirectPanGestureRecognizer=_presentFloatingDockIndirectPanGestureRecognizer;
@property(readonly, nonatomic) SBFolderController *presentedFolderController;
@property(readonly, copy, nonatomic) NSSet *presentedIconLocations;
@property(readonly, nonatomic, getter=isPresentingFolder) _Bool presentingFolder;
@property(retain, nonatomic) SBApplication *requestedSuggestedApplication;
@property(readonly, nonatomic) SBIconListView *suggestionsIconListView;
@property(readonly) Class superclass;
@property(nonatomic) __weak SBLayoutStateTransitionCoordinator *transitionCoordinator; // @synthesize transitionCoordinator=_transitionCoordinator;
@property(readonly, nonatomic) double translationFromFullyPresentedFrame;
@property(readonly, nonatomic) SBIconListView *userIconListView;
@property(readonly, nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;
@property(nonatomic) _Bool wasFloatingDockPresentedByPointer; // @synthesize wasFloatingDockPresentedByPointer=_wasFloatingDockPresentedByPointer;
@end

