//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBWindow.h>

@class UIView, UIViewController;

@interface SBFloatingApplicationLiveContentWindow : SBWindow
{
    UIViewController *_deviceApplicationSceneViewController;
    UIView *_effectiveCoordinateSpace;
}


// Remaining properties
@property(nonatomic) __weak UIViewController *deviceApplicationSceneViewController; // @synthesize deviceApplicationSceneViewController=_deviceApplicationSceneViewController;
@property(nonatomic) __weak UIView *effectiveCoordinateSpace; // @synthesize effectiveCoordinateSpace=_effectiveCoordinateSpace;
@end

