//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBIconListModelObserver-Protocol.h>
#import <SpringBoard/SBRecentDisplayItemsControllerDelegate-Protocol.h>
#import <SpringBoard/SBRecentDisplayItemsPersistenceDelegate-Protocol.h>

@class NSMutableOrderedSet, NSMutableSet, NSOrderedSet, NSString, PTSingleTestRecipe, SBAppSuggestionManager, SBApplication, SBApplicationController, SBBestAppSuggestion, SBFAnalyticsClient, SBFloatingDockDefaults, SBIconController, SBIconListModel, SBIconModel, SBRecentDisplayItemsController, SBRecentDisplayItemsDataStore, SBRecentDisplayItemsDefaults;
@protocol SBFloatingDockSuggestionsModelDelegate;

@interface SBFloatingDockSuggestionsModel : NSObject <SBRecentDisplayItemsPersistenceDelegate, SBRecentDisplayItemsControllerDelegate, SBIconListModelObserver>
{
    _Bool _recentsEnabled;
    NSOrderedSet *_currentDisplayItems;
    SBBestAppSuggestion *_currentAppSuggestion;
    SBApplication *_requestedSuggestedApplication;
    id <SBFloatingDockSuggestionsModelDelegate> _delegate;
    unsigned long long _maxSuggestions;
    SBAppSuggestionManager *_appSuggestionManager;
    SBRecentDisplayItemsController *_recentsController;
    SBRecentDisplayItemsDataStore *_recentsDataStore;
    SBRecentDisplayItemsDefaults *_recentsDefaults;
    SBIconListModel *_userDockListModel;
    SBIconController *_iconController;
    SBApplicationController *_applicationController;
    SBIconModel *_iconModel;
    SBFloatingDockDefaults *_floatingDockDefaults;
    SBFAnalyticsClient *_analyticsClient;
    NSMutableSet *_pendingSuggestionUpdateReasons;
    NSMutableOrderedSet *_currentRecentDisplayItems;
    NSMutableOrderedSet *_currentRecentDisplayItemsSortedByRecency;
    PTSingleTestRecipe *_stressTestRecipe;
}


// Remaining properties
@property(retain, nonatomic) SBFAnalyticsClient *analyticsClient; // @synthesize analyticsClient=_analyticsClient;
@property(readonly, nonatomic) SBAppSuggestionManager *appSuggestionManager; // @synthesize appSuggestionManager=_appSuggestionManager;
@property(readonly, nonatomic) SBApplicationController *applicationController; // @synthesize applicationController=_applicationController;
@property(readonly, nonatomic) SBBestAppSuggestion *currentAppSuggestion; // @synthesize currentAppSuggestion=_currentAppSuggestion;
@property(copy, nonatomic) NSOrderedSet *currentDisplayItems; // @synthesize currentDisplayItems=_currentDisplayItems;
@property(readonly, nonatomic) NSMutableOrderedSet *currentRecentDisplayItems; // @synthesize currentRecentDisplayItems=_currentRecentDisplayItems;
@property(readonly, nonatomic) NSMutableOrderedSet *currentRecentDisplayItemsSortedByRecency; // @synthesize currentRecentDisplayItemsSortedByRecency=_currentRecentDisplayItemsSortedByRecency;
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <SBFloatingDockSuggestionsModelDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) SBFloatingDockDefaults *floatingDockDefaults; // @synthesize floatingDockDefaults=_floatingDockDefaults;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) SBIconController *iconController; // @synthesize iconController=_iconController;
@property(retain, nonatomic) SBIconModel *iconModel; // @synthesize iconModel=_iconModel;
@property(readonly, nonatomic) unsigned long long maxSuggestions; // @synthesize maxSuggestions=_maxSuggestions;
@property(readonly, nonatomic) NSMutableSet *pendingSuggestionUpdateReasons; // @synthesize pendingSuggestionUpdateReasons=_pendingSuggestionUpdateReasons;
@property(readonly, nonatomic) SBRecentDisplayItemsController *recentsController; // @synthesize recentsController=_recentsController;
@property(readonly, nonatomic) SBRecentDisplayItemsDataStore *recentsDataStore; // @synthesize recentsDataStore=_recentsDataStore;
@property(readonly, nonatomic) SBRecentDisplayItemsDefaults *recentsDefaults; // @synthesize recentsDefaults=_recentsDefaults;
@property(nonatomic) _Bool recentsEnabled; // @synthesize recentsEnabled=_recentsEnabled;
@property(retain, nonatomic) SBApplication *requestedSuggestedApplication; // @synthesize requestedSuggestedApplication=_requestedSuggestedApplication;
@property(readonly, nonatomic) PTSingleTestRecipe *stressTestRecipe; // @synthesize stressTestRecipe=_stressTestRecipe;
@property(readonly) Class superclass;
@property(retain, nonatomic) SBIconListModel *userDockListModel; // @synthesize userDockListModel=_userDockListModel;
@end

