//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBSwitcherModifier.h>

@class SBAppLayout;

@interface SBForcePressGestureStateTrackingSwitcherModifier : SBSwitcherModifier
{
    SBAppLayout *_selectedAppLayout;
    _Bool _didBeginPanning;
    _Bool _didPop;
    double _panTranslationThreshold;
    double _panProgress;
    double _forceProgress;
    struct CGPoint _velocity;
    struct CGPoint _averageVelocity;
}


// Remaining properties
@property(readonly, nonatomic) struct CGPoint averageVelocity; // @synthesize averageVelocity=_averageVelocity;
@property(readonly, nonatomic) _Bool didBeginPanning; // @synthesize didBeginPanning=_didBeginPanning;
@property(readonly, nonatomic) _Bool didPop; // @synthesize didPop=_didPop;
@property(readonly, nonatomic) double forceProgress; // @synthesize forceProgress=_forceProgress;
@property(readonly, nonatomic) double panProgress; // @synthesize panProgress=_panProgress;
@property(readonly, nonatomic) double panTranslationThreshold; // @synthesize panTranslationThreshold=_panTranslationThreshold;
@property(readonly, nonatomic) struct CGPoint velocity; // @synthesize velocity=_velocity;
@end

