//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/NSObject-Protocol.h>

@class UIView;

@protocol SBGestureRecognizerPanGestureProviding <NSObject>
- (struct CGPoint)velocityInView:(UIView *)arg1;
- (struct CGPoint)translationInView:(UIView *)arg1;
- (struct CGPoint)locationInView:(UIView *)arg1;
@end

