//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBSwitcherModifier.h>

#import <SpringBoard/PTSettingsKeyObserver-Protocol.h>

@class NSString;

@interface SBGridLayoutSwitcherModifier : SBSwitcherModifier <PTSettingsKeyObserver>
{
    struct CGPoint _previousContentOffset;
    _Bool _isScrollingForward;
    _Bool _usesFixedCardSize;
    double _unroundedCardScale;
    unsigned long long _scrollAxis;
    unsigned long long _fixedGroupingSize;
    unsigned long long _alignment;
    unsigned long long _layoutDirection;
    struct CGSize _fixedCardSize;
}


// Remaining properties
@property(nonatomic) unsigned long long alignment; // @synthesize alignment=_alignment;
@property(nonatomic) double cardScale; // @synthesize cardScale=_unroundedCardScale;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) struct CGSize fixedCardSize; // @synthesize fixedCardSize=_fixedCardSize;
@property(nonatomic) unsigned long long fixedGroupingSize; // @synthesize fixedGroupingSize=_fixedGroupingSize;
@property(readonly) unsigned long long hash;
@property(nonatomic) unsigned long long layoutDirection; // @synthesize layoutDirection=_layoutDirection;
@property(nonatomic) unsigned long long scrollAxis; // @synthesize scrollAxis=_scrollAxis;
@property(readonly) Class superclass;
@property(nonatomic, getter=isUsingFixedCardSize) _Bool usesFixedCardSize; // @synthesize usesFixedCardSize=_usesFixedCardSize;
@end

