//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardUI/SBAlertItem.h>

@class NSString, SBIcon;

@interface SBHideAppIconAlertItem : SBAlertItem
{
    SBIcon *_icon;
    NSString *_iconLocation;
}


// Remaining properties
@property(readonly, nonatomic) SBIcon *icon; // @synthesize icon=_icon;
@property(readonly, copy, nonatomic) NSString *iconLocation; // @synthesize iconLocation=_iconLocation;
@end

