//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <SpringBoard/SBHAddWidgetSheetViewControllerPresenter-Protocol.h>
#import <SpringBoard/WGWidgetGroupViewControllerDelegate-Protocol.h>

@class MTMaterialView, NSLayoutConstraint, NSString, SBFTodayGestureSettings, SBHRootFolderVisualConfiguration, SBHRootSidebarController, SBTitledHomeScreenButton;
@protocol SBHomeScreenOverlayViewControllerDelegate;

@interface SBHomeScreenOverlayViewController : UIViewController <WGWidgetGroupViewControllerDelegate, SBHAddWidgetSheetViewControllerPresenter>
{
    _Bool _fromLeading;
    _Bool _suppressesExtraEditingButtons;
    _Bool _showsDoneButton;
    _Bool _showsAddWidgetButton;
    double _titledButtonsAlpha;
    id <SBHomeScreenOverlayViewControllerDelegate> _delegate;
    double _presentationProgress;
    SBHRootSidebarController *_contentViewController;
    UIViewController *_leftSidebarViewController;
    UIViewController *_rightSidebarViewController;
    MTMaterialView *_backgroundView;
    SBHRootFolderVisualConfiguration *_rootFolderVisualConfiguration;
    NSLayoutConstraint *_contentLeadingConstraint;
    NSLayoutConstraint *_contentWidthConstraint;
    SBTitledHomeScreenButton *_doneButton;
    SBTitledHomeScreenButton *_widgetButton;
    SBFTodayGestureSettings *_gestureSettings;
}


// Remaining properties
@property(readonly, nonatomic) MTMaterialView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) NSLayoutConstraint *contentLeadingConstraint; // @synthesize contentLeadingConstraint=_contentLeadingConstraint;
@property(readonly, nonatomic) struct CGRect contentRect;
@property(readonly, nonatomic) SBHRootSidebarController *contentViewController; // @synthesize contentViewController=_contentViewController;
@property(readonly, nonatomic) double contentWidth;
@property(retain, nonatomic) NSLayoutConstraint *contentWidthConstraint; // @synthesize contentWidthConstraint=_contentWidthConstraint;
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <SBHomeScreenOverlayViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) SBTitledHomeScreenButton *doneButton; // @synthesize doneButton=_doneButton;
@property(nonatomic, getter=isFromLeading) _Bool fromLeading; // @synthesize fromLeading=_fromLeading;
@property(retain, nonatomic) SBFTodayGestureSettings *gestureSettings; // @synthesize gestureSettings=_gestureSettings;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic, getter=isHeaderVisible) _Bool headerVisible;
@property(retain, nonatomic) UIViewController *leftSidebarViewController; // @synthesize leftSidebarViewController=_leftSidebarViewController;
@property(nonatomic) double presentationProgress; // @synthesize presentationProgress=_presentationProgress;
@property(retain, nonatomic) UIViewController *rightSidebarViewController; // @synthesize rightSidebarViewController=_rightSidebarViewController;
@property(readonly, nonatomic) SBHRootFolderVisualConfiguration *rootFolderVisualConfiguration; // @synthesize rootFolderVisualConfiguration=_rootFolderVisualConfiguration;
@property(nonatomic) _Bool showsAddWidgetButton; // @synthesize showsAddWidgetButton=_showsAddWidgetButton;
@property(nonatomic) _Bool showsDoneButton; // @synthesize showsDoneButton=_showsDoneButton;
@property(readonly) Class superclass;
@property(nonatomic) _Bool suppressesExtraEditingButtons; // @synthesize suppressesExtraEditingButtons=_suppressesExtraEditingButtons;
@property(nonatomic) double titledButtonsAlpha; // @synthesize titledButtonsAlpha=_titledButtonsAlpha;
@property(retain, nonatomic) SBTitledHomeScreenButton *widgetButton; // @synthesize widgetButton=_widgetButton;
@end

