//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/NSObject-Protocol.h>

@class SBHomeGrabberView;

@protocol SBHomeGrabberDelegate <NSObject>
- (_Bool)shouldAllowAutoHideForHomeGrabberView:(SBHomeGrabberView *)arg1;
- (_Bool)shouldAllowThinStyleForHomeGrabberView:(SBHomeGrabberView *)arg1;
- (double)additionalEdgeSpacingForHomeGrabberView:(SBHomeGrabberView *)arg1;
@end

