//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/NSObject-Protocol.h>

@protocol SBHomeButtonShowPasscodeRecognizer;

@protocol SBHomeButtonShowPasscodeRecognizerDelegate <NSObject>
- (void)homeButtonShowPasscodeRecognizerDidFailToRecognize:(id <SBHomeButtonShowPasscodeRecognizer>)arg1;
- (void)homeButtonShowPasscodeRecognizerRequestsPasscodeUIToBeShown:(id <SBHomeButtonShowPasscodeRecognizer>)arg1;
@end

