//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/NSObject-Protocol.h>

@class SBHSidebarWidgetBootstrappingAdvisor;

@protocol SBHSidebarWidgetLearningObserver <NSObject>
- (void)sidebarWidgetLearningAdvisorDidUpdate:(SBHSidebarWidgetBootstrappingAdvisor *)arg1;
@end

