//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardFoundation/SBFTouchPassThroughViewController.h>

#import <SpringBoard/SBHUDViewControlling-Protocol.h>
#import <SpringBoard/UIViewControllerTransitioningDelegate-Protocol.h>

@class NSString, UIImage, UIImageView, UIView, _UIBackdropView;

@interface SBHUDViewController : SBFTouchPassThroughViewController <UIViewControllerTransitioningDelegate, SBHUDViewControlling>
{
    _Bool _showsProgress;
    UIImage *_image;
    double _progress;
    NSString *_title;
    NSString *_subtitle;
    double _visibilityProgress;
    UIView *_hudView;
    UIView *_blockView;
    _UIBackdropView *_backdropView;
    UIImageView *_backdropMaskImageView;
}


// Remaining properties
@property(readonly, nonatomic) UIImageView *backdropMaskImageView; // @synthesize backdropMaskImageView=_backdropMaskImageView;
@property(readonly, nonatomic) _UIBackdropView *backdropView; // @synthesize backdropView=_backdropView;
@property(readonly, nonatomic) UIView *blockView; // @synthesize blockView=_blockView;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) UIView *hudView; // @synthesize hudView=_hudView;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(nonatomic) _Bool showsProgress; // @synthesize showsProgress=_showsProgress;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly) Class superclass;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) double visibilityProgress; // @synthesize visibilityProgress=_visibilityProgress;
@end

