//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBWorkspaceEntity.h>

@class NSString;

@interface SBInlineAppExposeWorkspaceEntity : SBWorkspaceEntity
{
    NSString *_bundleIdentifier;
}


// Remaining properties
@property(readonly, copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@end

