//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBMainWorkspaceTransaction.h>

@class SBApplicationSceneEntity;

@interface SBInCallSceneUpdateWorkspaceTransaction : SBMainWorkspaceTransaction
{
    SBApplicationSceneEntity *_applicationSceneEntity;
    CDUnknownBlockType _postSceneUpdateHandler;
}


// Remaining properties
@property(copy, nonatomic) CDUnknownBlockType postSceneUpdateHandler; // @synthesize postSceneUpdateHandler=_postSceneUpdateHandler;
@end

