//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBSwitcherLiveContentOverlayCoordinating-Protocol.h>

@class NSString, SBAppLayout, SBDeviceApplicationSceneViewController, SBInlineAppExposeLiveContentOverlayView;
@protocol SBSwitcherLiveContentOverlayCoordinatorDelegate;

@interface SBInlineAppExposeLiveContentOverlayCoordinator : NSObject <SBSwitcherLiveContentOverlayCoordinating>
{
    SBDeviceApplicationSceneViewController *_deviceApplicationSceneViewController;
    long long _environment;
    long long _layoutRole;
    _Bool _overlay;
    SBAppLayout *_liveContentAppLayout;
    SBInlineAppExposeLiveContentOverlayView *_liveContentOverlayView;
    _Bool _liveContentOverlayUpdatesSuspended;
    long long _containerOrientation;
    id <SBSwitcherLiveContentOverlayCoordinatorDelegate> _delegate;
}


// Remaining properties
@property(nonatomic) long long containerOrientation; // @synthesize containerOrientation=_containerOrientation;
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <SBSwitcherLiveContentOverlayCoordinatorDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic, getter=areLiveContentOverlayUpdatesSuspended) _Bool liveContentOverlayUpdatesSuspended; // @synthesize liveContentOverlayUpdatesSuspended=_liveContentOverlayUpdatesSuspended;
@property(readonly) Class superclass;
@end

