//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <SpringBoard/SBDeviceApplicationSceneHandleObserver-Protocol.h>

@class NSString, SBDeviceApplicationSceneHandle, SBIsolatedSceneOrientationFollowingContainerView, SBIsolatedSceneOrientationFollowingWindow, SBWindowSelfHostWrapper, UIApplicationSceneClientSettingsDiffInspector, UIApplicationSceneSettingsDiffInspector;
@protocol SBIsolatedSceneOrientationFollowingWrapperOrientationDelegate;

@interface SBIsolatedSceneOrientationFollowingWrapperViewController : UIViewController <SBDeviceApplicationSceneHandleObserver>
{
    SBDeviceApplicationSceneHandle *_sceneHandle;
    UIViewController *_contentViewController;
    SBIsolatedSceneOrientationFollowingWindow *_appOverlayWindow;
    SBWindowSelfHostWrapper *_appOverlayHostWrapper;
    SBIsolatedSceneOrientationFollowingContainerView *_containerView;
    UIApplicationSceneSettingsDiffInspector *_sceneSettingsDiffInspector;
    UIApplicationSceneClientSettingsDiffInspector *_clientSettingsDiffInspector;
    _Bool _sceneWantsDeviceOrientationEvents;
    _Bool _rendersWhileLocked;
    id <SBIsolatedSceneOrientationFollowingWrapperOrientationDelegate> _orientationDelegate;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

