//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/BSDescriptionProviding-Protocol.h>

@class NSSet, NSString;

@interface SBLayoutState : NSObject <BSDescriptionProviding>
{
    long long _interfaceOrientation;
    long long _elementInterfaceOrientation;
    NSSet *_elements;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) long long elementInterfaceOrientation;
@property(readonly, nonatomic) NSSet *elements; // @synthesize elements=_elements;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) long long interfaceOrientation;
@property(readonly) Class superclass;
@end

