//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSError, SBLayoutState, SBWorkspaceApplicationSceneTransitionContext, SBWorkspaceTransaction;

@interface SBLayoutStateTransitionContext : NSObject
{
    _Bool _complete;
    _Bool _animationsDisabled;
    SBLayoutState *_fromLayoutState;
    SBLayoutState *_toLayoutState;
    NSError *_error;
    SBWorkspaceTransaction *_workspaceTransaction;
    SBWorkspaceApplicationSceneTransitionContext *_applicationTransitionContext;
}


// Remaining properties
@property(readonly, nonatomic) _Bool animationsDisabled; // @synthesize animationsDisabled=_animationsDisabled;
@property(readonly, nonatomic) __weak SBWorkspaceApplicationSceneTransitionContext *applicationTransitionContext; // @synthesize applicationTransitionContext=_applicationTransitionContext;
@property(readonly, nonatomic, getter=isComplete) _Bool complete; // @synthesize complete=_complete;
@property(readonly, nonatomic) NSError *error; // @synthesize error=_error;
@property(readonly, nonatomic) SBLayoutState *fromLayoutState; // @synthesize fromLayoutState=_fromLayoutState;
@property(readonly, nonatomic, getter=isInterrupted) _Bool interrupted;
@property(readonly, nonatomic) SBLayoutState *toLayoutState; // @synthesize toLayoutState=_toLayoutState;
@property(readonly, nonatomic) __weak SBWorkspaceTransaction *workspaceTransaction; // @synthesize workspaceTransaction=_workspaceTransaction;
@end

