//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/CMWakeGestureDelegate-Protocol.h>

@class CMWakeGestureManager, NSHashTable, NSString, SBIdleTimerDefaults;

@interface SBLiftToWakeController : NSObject <CMWakeGestureDelegate>
{
    CMWakeGestureManager *_wakeGestureManager;
    long long _wakeGestureState;
    NSHashTable *_observers;
    SBIdleTimerDefaults *_idleTimerDefaults;
    _Bool _screenOn;
    _Bool _isEnabled;
    _Bool _observingCMWakeGestureManager;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_isEnabled;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic, getter=_idleTimerDefaults, setter=_setIdleTimerDefaults:) SBIdleTimerDefaults *idleTimerDefaults; // @synthesize idleTimerDefaults=_idleTimerDefaults;
@property(readonly) Class superclass;
@end

