//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <SpringBoard/UITableViewDataSource-Protocol.h>
#import <SpringBoard/UITableViewDelegate-Protocol.h>

@class NSArray, NSDictionary, NSString;

@interface SBLogoutDebugBlockingViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
{
    NSDictionary *_debugBlockingTasks;
    NSArray *_applicationKeys;
}


// Remaining properties
@property(retain, nonatomic) NSDictionary *debugBlockingTasks; // @synthesize debugBlockingTasks=_debugBlockingTasks;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

