//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/NSObject-Protocol.h>

@class NSError, SBLockScreenEmergencyCallViewController;

@protocol SBLockScreenEmergencyCallViewControllerDelegate <NSObject>
- (void)emergencyCallViewController:(SBLockScreenEmergencyCallViewController *)arg1 didExitWithError:(NSError *)arg2;
- (void)dismissEmergencyCallViewController:(SBLockScreenEmergencyCallViewController *)arg1;
@end

