//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface SBLockScreenActionManager : NSObject
{
    NSMutableDictionary *_actionProviders;
}


// Remaining properties
@property(retain, nonatomic) NSMutableDictionary *actionProviders; // @synthesize actionProviders=_actionProviders;
@end

