//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/PTSettingsKeyObserver-Protocol.h>

@class CSLockScreenSettings, NSString, PCPersistentTimer, PTToggleTestRecipe, SBMediaController;
@protocol SBLockScreenNowPlayingControllerDelegate;

@interface SBLockScreenNowPlayingController : NSObject <PTSettingsKeyObserver>
{
    SBMediaController *_mediaController;
    PCPersistentTimer *_disableTimer;
    CSLockScreenSettings *_testSettings;
    PTToggleTestRecipe *_testRecipe;
    _Bool _enabled;
    long long _currentState;
    id <SBLockScreenNowPlayingControllerDelegate> _delegate;
}


// Remaining properties
@property(readonly, nonatomic) long long currentState; // @synthesize currentState=_currentState;
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <SBLockScreenNowPlayingControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

