//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBLockScreenEmergencyCallViewControllerDelegate-Protocol.h>

@class NSString, SBLockScreenEmergencyCallViewController, UIViewController;
@protocol SBLockScreenEmergencyDialerDelegate;

@interface SBLockScreenEmergencyDialerController : NSObject <SBLockScreenEmergencyCallViewControllerDelegate>
{
    SBLockScreenEmergencyCallViewController *_viewController;
    _Bool _active;
    id <SBLockScreenEmergencyDialerDelegate> _delegate;
}


// Remaining properties
@property(readonly, nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <SBLockScreenEmergencyDialerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;
@end

