//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBLockOverlayViewController.h>

@class NSString, SBLockScreenTemperatureWarningView;

@interface SBLockScreenTemperatureWarningViewController : SBLockOverlayViewController
{
    SBLockScreenTemperatureWarningView *_warningView;
}


// Remaining properties
@property(readonly, nonatomic) __weak NSString *slideToUnlockText;
@end

