//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <SpringBoard/PTSettingsKeyObserver-Protocol.h>
#import <SpringBoard/SBAppSwitcherModelDelegate-Protocol.h>
#import <SpringBoard/SBButtonEventsHandler-Protocol.h>
#import <SpringBoard/SBFluidSwitcherGestureManagerDelegate-Protocol.h>
#import <SpringBoard/SBLayoutStateTransitionObserver-Protocol.h>
#import <SpringBoard/SBLayoutStateTransitionSceneEntityFrameProvider-Protocol.h>
#import <SpringBoard/SBMainDisplayWorkspaceAppInteractionEventSourceObserving-Protocol.h>
#import <SpringBoard/SBSwitcherContentViewControllerDataSource-Protocol.h>
#import <SpringBoard/SBSwitcherContentViewControllerDelegate-Protocol.h>
#import <SpringBoard/SBSwitcherDemoFilteringControllerObserver-Protocol.h>
#import <SpringBoard/SBWorkspaceKeyboardFocusControllerObserver-Protocol.h>

@class BSAnimationSettings, BSSimpleAssertion, BSTimer, FBDisplayLayoutElement, NSArray, NSDictionary, NSHashTable, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, SBAppLayout, SBAppStatusBarSettingsAssertion, SBAppSwitcherModel, SBAppSwitcherServiceSet, SBAppSwitcherSettings, SBApplicationUserQuitMonitorServer, SBFluidSwitcherGestureManager, SBMainDisplaySceneLayoutViewController, SBOrientationTransformWrapperView, SBPIPStashAssertion, SBSwitcherDemoCommandsServer, SBSwitcherDemoFilteringController, SBSwitcherModelRemovalResults, SBWindow, SBWorkspaceKeyboardFocusController, SiriContinuitySource, UIApplicationSceneDeactivationAssertion;
@protocol BSInvalidatable, SBSwitcherContentViewControlling;

@interface SBMainSwitcherViewController : UIViewController <SBSwitcherContentViewControllerDataSource, SBSwitcherContentViewControllerDelegate, SBSwitcherDemoFilteringControllerObserver, PTSettingsKeyObserver, SBLayoutStateTransitionObserver, SBLayoutStateTransitionSceneEntityFrameProvider, SBFluidSwitcherGestureManagerDelegate, SBWorkspaceKeyboardFocusControllerObserver, SBAppSwitcherModelDelegate, SBMainDisplayWorkspaceAppInteractionEventSourceObserving, SBButtonEventsHandler>
{
    NSArray *_appLayouts;
    SBAppSwitcherServiceSet *_switcherServices;
    NSMutableDictionary *_appLayoutToAcquiredTransientOverlayViewController;
    NSMutableDictionary *_appLayoutToEligibleTransientOverlayViewController;
    SBWindow *_window;
    UIViewController<SBSwitcherContentViewControlling> *_contentViewController;
    SBOrientationTransformWrapperView *_contentWrapperView;
    SBFluidSwitcherGestureManager *_gestureManager;
    NSMutableSet *_windowDragSceneIdentifiers;
    SBAppLayout *_activeAppLayoutWhenActivatingMainSwitcher;
    SBSwitcherModelRemovalResults *_activeTransitionModelRemovalResults;
    NSDictionary *_activeTransitionModelRemovalAppLayoutToRemovalContext;
    SBAppSwitcherSettings *_settings;
    Class _contentViewControllerClass;
    NSMutableArray *_servicesRemovedWhileAwayFromSwitcher;
    NSMutableDictionary *_liveAppsBeingTerminated;
    _Bool _ignoreModelUpdates;
    id <BSInvalidatable> _deferRotationForAppSwitcherAssertion;
    id <BSInvalidatable> _lockKeyboardFocusAssertion;
    SBPIPStashAssertion *_pipStashOverrideAssertion;
    SBMainDisplaySceneLayoutViewController *_sceneLayoutViewController;
    FBDisplayLayoutElement *_displayLayoutElement;
    SBAppLayout *_testItemForInsertion;
    unsigned long long _testItemInsertionIndex;
    SBAppSwitcherModel *_mainSwitcherModel;
    SBSwitcherDemoCommandsServer *_demoCommandsServer;
    SBSwitcherDemoFilteringController *_demoFilteringController;
    NSArray *_demoFilteringHiddenAppLayouts;
    SBApplicationUserQuitMonitorServer *_userQuitMonitorServer;
    SiriContinuitySource *_siriSource;
    SBWorkspaceKeyboardFocusController *_keyboardFocusController;
    UIApplicationSceneDeactivationAssertion *_deactivatingScenesResignActiveAssertion;
    SBAppStatusBarSettingsAssertion *_mainStatusBarAssertion;
    SBAppStatusBarSettingsAssertion *_floatingStatusBarAssertion;
    BSSimpleAssertion *_preventAdditionalMedusaSnapshotsAssertion;
    BSTimer *_preventAdditionalMedusaSnapshotsInvalidationTimer;
    NSMutableSet *_asynchronousRenderingAssertions;
    NSHashTable *_asynchronousRenderingCachedSurfacesReasons;
    BSTimer *_disableCachingAsynchronousRenderingSurfacesTimer;
    NSMutableDictionary *_recentSwipeUpToKillTimestampsForAppLayouts;
    NSHashTable *__hideStatusBarAssertions;
    id <BSInvalidatable> _suspendWallpaperAnimationAssertion;
}


// Remaining properties
@property(retain, nonatomic, setter=_setHideStatusBarAssertions:) NSHashTable *_hideStatusBarAssertions; // @synthesize _hideStatusBarAssertions=__hideStatusBarAssertions;
@property(readonly, nonatomic) SBAppLayout *activeTransientOverlayPresentedAppLayout;
@property(readonly, nonatomic) _Bool canInterruptActiveTransition;
@property(readonly, nonatomic) UIViewController<SBSwitcherContentViewControlling> *contentViewController; // @synthesize contentViewController=_contentViewController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy, nonatomic) BSAnimationSettings *defaultTransitionAnimationSettings;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) _Bool hasTransientOverlayAppLayouts;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) id <BSInvalidatable> suspendWallpaperAnimationAssertion; // @synthesize suspendWallpaperAnimationAssertion=_suspendWallpaperAnimationAssertion;
@end

