//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBStatusBarStateProvider.h>

#import <SpringBoard/UIStatusBarStateObserver-Protocol.h>

@class NSCountedSet, NSHashTable, NSString, SBSStatusBarStyleOverridesAssertion;

@interface SBMainStatusBarStateProvider : SBStatusBarStateProvider <UIStatusBarStateObserver>
{
    _Bool _overridePercent;
    _Bool _killActivity;
    _Bool _simulateInCallStatusBar;
    SBSStatusBarStyleOverridesAssertion *_inCallStatusBarStyleOverrideAssertion;
    _Bool _itemIsDisabled[43];
    _Bool _itemWasDisabled[43];
    NSCountedSet *_itemDisabledRequests[43];
    NSCountedSet *_dataUpdateAnimationsDisabledRequests;
    _Bool _timeEnabled;
    _Bool _statusBarTimeRequiresUpdate;
    _Bool _timeCloaked;
    _Bool _allButBatteryCloaked;
    _Bool _telephonyAndBluetoothCloaked;
    NSHashTable *_contentAssertions;
}


// Remaining properties
@property(retain, nonatomic) NSHashTable *contentAssertions; // @synthesize contentAssertions=_contentAssertions;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

