//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/BSInvalidatable-Protocol.h>

@class NSString;

@interface SBMedusaHostedKeyboardWindowLevelAssertion : NSObject <BSInvalidatable>
{
    CDUnknownBlockType _invalidationHandler;
    unsigned long long _priority;
    double _windowLevel;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) unsigned long long priority; // @synthesize priority=_priority;
@property(readonly) Class superclass;
@property(readonly, nonatomic) double windowLevel; // @synthesize windowLevel=_windowLevel;
@end

