//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import <SpringBoard/SBSwitcherContentViewControlling-Protocol.h>

@class BSAnimationSettings, NSString, SBApplicationSceneView, SBBestAppSuggestion;
@protocol SBSwitcherContentViewControllerDataSource, SBSwitcherContentViewControllerDelegate;

@interface SBMinimumViableSwitcherTableViewController : UITableViewController <SBSwitcherContentViewControlling>
{
    id <SBSwitcherContentViewControllerDelegate> _delegate;
    SBApplicationSceneView *_temporaryAppView;
    SBApplicationSceneView *_temporarySideAppView;
    SBBestAppSuggestion *_bestAppSuggestion;
    _Bool _liveContentRasterizationDisabled;
    id <SBSwitcherContentViewControllerDataSource> _dataSource;
    long long _contentOrientation;
}


// Remaining properties
@property(retain, nonatomic) SBBestAppSuggestion *bestAppSuggestion; // @synthesize bestAppSuggestion=_bestAppSuggestion;
@property(readonly, nonatomic) _Bool canInterruptActiveTransition;
@property(nonatomic) long long contentOrientation; // @synthesize contentOrientation=_contentOrientation;
@property(nonatomic) __weak id <SBSwitcherContentViewControllerDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy, nonatomic) BSAnimationSettings *defaultTransitionAnimationSettings;
@property(nonatomic) __weak id <SBSwitcherContentViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic, getter=isLiveContentRasterizationDisabled) _Bool liveContentRasterizationDisabled; // @synthesize liveContentRasterizationDisabled=_liveContentRasterizationDisabled;
@property(nonatomic, getter=isShowingModifierTimeline) _Bool showModifierTimeline;
@property(readonly) Class superclass;
@end

