//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBGestureRootSwitcherModifier.h>

@interface SBMoveGestureRootFloatingSwitcherModifier : SBGestureRootSwitcherModifier
{
    long long _currentFloatingConfiguration;
    long long _interfaceOrientation;
}


// Remaining properties
@property(nonatomic) long long currentFloatingConfiguration; // @synthesize currentFloatingConfiguration=_currentFloatingConfiguration;
@property(nonatomic) long long interfaceOrientation; // @synthesize interfaceOrientation=_interfaceOrientation;
@end

