//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBSystemGestureWorkspaceTransaction.h>

@class SBAppStatusBarSettingsAssertion, SBAppSwitcherSettings, SBAssistantController, SBAssistantRootViewController, SBMainWorkspaceTransaction, SBTransientOverlayPresentationManager, SBTransientOverlayViewController, UINotificationFeedbackGenerator;

@interface SBModalUIFluidDismissGestureWorkspaceTransaction : SBSystemGestureWorkspaceTransaction
{
    SBAppSwitcherSettings *_settings;
    SBAppStatusBarSettingsAssertion *_statusBarAssertion;
    UINotificationFeedbackGenerator *_dismissalFeedbackGenerator;
    SBAssistantRootViewController *_assistantRootViewController;
    SBTransientOverlayPresentationManager *_transientOverlayPresentationManager;
    SBTransientOverlayViewController *_transientOverlayViewController;
    struct CGPoint _dismissingViewTouchOffset;
    struct CGRect _originalBounds;
    struct CGPoint _originalCenter;
    _Bool _hasPreservedInputViews;
    _Bool _isDismissing;
    SBAssistantController *_assistantController;
    long long _dismissalType;
    SBMainWorkspaceTransaction *_currentTransaction;
}


// Remaining properties
@property(retain, nonatomic) SBAssistantController *assistantController; // @synthesize assistantController=_assistantController;
@property(retain, nonatomic) SBMainWorkspaceTransaction *currentTransaction; // @synthesize currentTransaction=_currentTransaction;
@property(readonly, nonatomic) long long dismissalType; // @synthesize dismissalType=_dismissalType;
@end

