//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBBannerUnfurlSourceContext.h>

@interface SBMutableBannerUnfurlSourceContext : SBBannerUnfurlSourceContext
{
}


// Remaining properties
@property(nonatomic) double cornerRadius; // @dynamic cornerRadius;
@property(nonatomic) struct CGRect referenceCoordinateSpaceBounds; // @dynamic referenceCoordinateSpaceBounds;
@property(nonatomic) struct CGRect referenceFrame; // @dynamic referenceFrame;
@property(nonatomic) struct CGPoint referenceVelocity; // @dynamic referenceVelocity;
@end

