//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/XBSnapshotDataProvider-Protocol.h>

@class NSString, UIImage, XBSnapshotDataProviderContext;
@protocol XBSnapshotDataProvider;

@interface SBNestedSnapshotDataProvider : NSObject <XBSnapshotDataProvider>
{
    id <XBSnapshotDataProvider> _sourceProvider;
    id <XBSnapshotDataProvider> _fallbackProvider;
    double _scaleFactor;
    UIImage *_cachedImage;
    XBSnapshotDataProviderContext *_context;
}


// Remaining properties
@property(readonly, retain, nonatomic) XBSnapshotDataProviderContext *context; // @synthesize context=_context;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

