//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/BSInvalidatable-Protocol.h>
#import <SpringBoard/SBAppStatusBarAssertionManagerObserver-Protocol.h>
#import <SpringBoard/SBDeviceApplicationSceneHandleObserver-Protocol.h>
#import <SpringBoard/SBMainDisplaySceneManagerObserver-Protocol.h>
#import <SpringBoard/SBUIActiveOrientationObserver-Protocol.h>
#import <SpringBoard/UIStatusBarServerClient-Protocol.h>

@class NSString, SBAppStatusBarAssertionManager, SBMainDisplaySceneManager, SpringBoard, UIApplicationSceneSettingsDiffInspector, UIStatusBarServer;
@protocol SBNotchedStatusBarProximityBacklightPolicyEnablementConditionDelegate;

@interface SBNotchedStatusBarProximityBacklightPolicyEnablementCondition : NSObject <SBAppStatusBarAssertionManagerObserver, SBMainDisplaySceneManagerObserver, SBDeviceApplicationSceneHandleObserver, UIStatusBarServerClient, SBUIActiveOrientationObserver, BSInvalidatable>
{
    SpringBoard *_orientationProvider;
    UIStatusBarServer *_statusBarConnection;
    SBAppStatusBarAssertionManager *_statusBarAssertionManager;
    SBMainDisplaySceneManager *_mainDisplaySceneManager;
    UIApplicationSceneSettingsDiffInspector *_applicationSceneSettingsDiffInspector;
    int _currentStyleOverrides;
    id <SBNotchedStatusBarProximityBacklightPolicyEnablementConditionDelegate> _delegate;
    double _statusBarHeight;
    _Bool _isEnabled;
    _Bool _invalidated;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <SBNotchedStatusBarProximityBacklightPolicyEnablementConditionDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_isEnabled;
@property(readonly, nonatomic) double enabledStatusBarHeight; // @synthesize enabledStatusBarHeight=_statusBarHeight;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

