//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <SpringBoard/NSCopying-Protocol.h>

@class NSMutableArray;

@interface SBPBAppLayoutList : PBCodable <NSCopying>
{
    NSMutableArray *_applayouts;
}


// Remaining properties
@property(retain, nonatomic) NSMutableArray *applayouts; // @synthesize applayouts=_applayouts;
@end

