//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBPIPAnalyticsAssistant.h>

@interface SBPIPAnalyticsSourceSummaryAssistant : SBPIPAnalyticsAssistant
{
    _Bool _PIPBecameActive;
    double _possibleDuration;
    double _possibleTimestamp;
}

@end

