//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SBPIPAnalyticsAssistant : NSObject
{
    NSString *_bundleIdentifier;
    long long _contentType;
    _Bool _isAutoPIPEnabled;
    double _activateDuration;
    double _activationTimestamp;
    CDUnknownBlockType _invalidationBlock;
    NSString *_analyticsIdentifier;
}


// Remaining properties
@property(readonly, nonatomic) NSString *analyticsIdentifier; // @synthesize analyticsIdentifier=_analyticsIdentifier;
@end

