//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBPressGestureStateInfo : NSObject
{
    _Bool _isCoalescing;
    long long _state;
    double _expirationTime;
    long long _stateUponExpiration;
}


// Remaining properties
@property(nonatomic) double expirationTime; // @synthesize expirationTime=_expirationTime;
@property(nonatomic) _Bool isCoalescing; // @synthesize isCoalescing=_isCoalescing;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(nonatomic) long long stateUponExpiration; // @synthesize stateUponExpiration=_stateUponExpiration;
@end

