//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBSwitcherModifier.h>

@class NSSet, SBAppLayout;

@interface SBRemovalSwitcherModifier : SBSwitcherModifier
{
    SBAppLayout *_appLayout;
    long long _reason;
    SBSwitcherModifier *_multitaskingModifier;
    _Bool _simulatingPostRemovalState;
    unsigned long long _indexToScrollToAfterRemoval;
    unsigned long long _indexOfAppLayoutPriorToRemoval;
    NSSet *_visibleAppLayoutsPriorToRemoval;
    unsigned long long _phase;
}

@end

