//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBRemoteTransientOverlaySessionObserver-Protocol.h>
#import <SpringBoard/SBSRemoteAlertHandleClient-Protocol.h>

@class NSMutableDictionary, NSString, SBRemoteTransientOverlaySessionManager;
@protocol OS_dispatch_queue;

@interface SBRemoteAlertHandleLocalClient : NSObject <SBRemoteTransientOverlaySessionObserver, SBSRemoteAlertHandleClient>
{
    NSObject<OS_dispatch_queue> *_accessSerialQueue;
    SBRemoteTransientOverlaySessionManager *_sessionManager;
    NSMutableDictionary *_sessionIDToRemoteAlertHandle;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

