//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBAnalyticsStateMachineEventHandler.h>

@class PETDistributionEventTracker;

@interface SBReachabilityMetric : SBAnalyticsStateMachineEventHandler
{
    double _activateTimestamp;
    PETDistributionEventTracker *_tracker;
    unsigned long long _activateLocation;
    unsigned long long _deactivationReason;
}

@end

