//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/BSDescriptionProviding-Protocol.h>
#import <SpringBoard/BSInvalidatable-Protocol.h>
#import <SpringBoard/FBSceneDelegate-Protocol.h>
#import <SpringBoard/FBSceneManagerDelegate_Private-Protocol.h>
#import <SpringBoard/FBSceneManagerObserver-Protocol.h>
#import <SpringBoard/SBApplicationSceneHandleProviding-Protocol.h>
#import <SpringBoard/SBSceneLayoutSlaveTransactionProviding-Protocol.h>
#import <SpringBoard/SBSceneLayoutViewControllerDelegate-Protocol.h>

@class BSCopyingCacheSet, FBSDisplayIdentity, FBSceneManager, NSCountedSet, NSHashTable, NSMapTable, NSMutableSet, NSString, SBLayoutState, SBLayoutStateManager, SBLayoutStateTransitionCoordinator, SBPolicyAggregator, SBSceneLayoutViewController, SBSceneLayoutWindow, SBSceneManagerReference, UIRootWindowScenePresentationBinder;

@interface SBSceneManager : NSObject <SBSceneLayoutViewControllerDelegate, FBSceneManagerObserver, FBSceneDelegate, FBSceneManagerDelegate_Private, BSDescriptionProviding, BSInvalidatable, SBApplicationSceneHandleProviding, SBSceneLayoutSlaveTransactionProviding>
{
    long long _state;
    UIRootWindowScenePresentationBinder *_rootWindowScenePresentationBinder;
    FBSceneManager *_sceneManager;
    SBSceneManagerReference *_selfReference;
    _Bool _hidden;
    SBSceneLayoutWindow *_window;
    SBSceneLayoutViewController *_sceneLayoutViewController;
    _Bool _layoutControllerHasVisibleElements;
    SBPolicyAggregator *_policyAggregator;
    SBLayoutStateManager *_layoutStateManager;
    SBLayoutStateTransitionCoordinator *_layoutStateTransitionCoordinator;
    NSMapTable *_persistentMapSceneIdentityToSceneHandle;
    NSMapTable *_transientMapSceneIdentityToSceneHandle;
    BSCopyingCacheSet *_allScenes;
    BSCopyingCacheSet *_daemonScenes;
    BSCopyingCacheSet *_workspaceScenes;
    BSCopyingCacheSet *_externalApplicationSceneHandles;
    BSCopyingCacheSet *_externalForegroundApplicationSceneHandles;
    BSCopyingCacheSet *_reportedExternalForegroundApplicationSceneHandles;
    NSCountedSet *_assertedBackgroundScenes;
    NSMutableSet *_outgoingSnapshots;
    NSMutableSet *_incomingSnapshots;
    NSHashTable *_observers;
    _Bool _layoutControllerCreationReentrancyGuard;
    NSMutableSet *_slaveTransactionProviders;
    SBLayoutState *_currentLayoutState;
}


// Remaining properties
@property(readonly, nonatomic) SBLayoutStateManager *_layoutStateManager;
@property(readonly, nonatomic) SBLayoutStateTransitionCoordinator *_layoutStateTransitionCoordinator;
@property(retain, nonatomic) SBLayoutState *currentLayoutState; // @synthesize currentLayoutState=_currentLayoutState;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) FBSDisplayIdentity *displayIdentity;
@property(readonly) unsigned long long hash;
@property(nonatomic, getter=isHidden) _Bool hidden;
@property(readonly, nonatomic) SBPolicyAggregator *policyAggregator;
@property(readonly, nonatomic) SBSceneLayoutViewController *sceneLayoutViewController;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) _Bool valid;
@property(readonly, nonatomic) SBSceneLayoutWindow *window;
@end

