//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class SBIsolatedSceneOrientationFollowingWrapperViewController, UIView;

@interface SBSceneOrientationFollowingWindowRootViewController : UIViewController
{
    SBIsolatedSceneOrientationFollowingWrapperViewController *_hostingViewController;
    UIView *_overlayContentView;
}


// Remaining properties
@property(nonatomic) __weak SBIsolatedSceneOrientationFollowingWrapperViewController *hostingViewController; // @synthesize hostingViewController=_hostingViewController;
@property(retain, nonatomic) UIView *overlayContentView; // @synthesize overlayContentView=_overlayContentView;
@end

