//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableDictionary, NSString;

@interface SBSceneDataStore : NSObject
{
    NSString *_identifier;
    NSMutableDictionary *_data;
    NSMutableDictionary *_archivedObjectCache;
    CDUnknownBlockType _handler;
    _Bool _invalidated;
}


// Remaining properties
@property(readonly, nonatomic, getter=_data) NSDictionary *data; // @synthesize data=_data;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(readonly, nonatomic, getter=_isInvalidated) _Bool invalidated; // @synthesize invalidated=_invalidated;
@end

