//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/CSCoverSheetViewControllerObserver-Protocol.h>
#import <SpringBoard/CSExternalLockProviding-Protocol.h>

@class NSString, SBLockScreenManager;
@protocol BSInvalidatable, SBSoftLockoutControllerDelegate;

@interface SBSoftLockoutController : NSObject <CSExternalLockProviding, CSCoverSheetViewControllerObserver>
{
    SBLockScreenManager *_lockScreenManager;
    unsigned long long _desiredBiometricLockoutState;
    id <BSInvalidatable> _passcodeRequiredAssertion;
    id <SBSoftLockoutControllerDelegate> _delegate;
}


// Remaining properties
@property(readonly, copy, nonatomic) NSString *coverSheetIdentifier;
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <SBSoftLockoutControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic, getter=isLocked) _Bool locked;
@property(readonly, nonatomic) long long participantState;
@property(readonly, nonatomic) _Bool showPasscode;
@property(readonly) Class superclass;
@end

