//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/NSObject-Protocol.h>

@class SBSpotlightTransientOverlayViewController;

@protocol SBSpotlightTransientOverlayViewControllerDelegate <NSObject>

@optional
- (void)spotlightTransientOverlayViewControllerWillDismiss:(SBSpotlightTransientOverlayViewController *)arg1;
- (void)spotlightTransientOverlayViewControllerDidPresent:(SBSpotlightTransientOverlayViewController *)arg1;
- (void)spotlightTransientOverlayViewControllerRequestsDismissal:(SBSpotlightTransientOverlayViewController *)arg1;
@end

