//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PrototypeTools/PTSettings.h>

@class SBFFluidBehaviorSettings;

@interface SBSpotlightSettings : PTSettings
{
    SBFFluidBehaviorSettings *_opacityAnimationSettings;
    SBFFluidBehaviorSettings *_snappyOpacityAnimationSettings;
    SBFFluidBehaviorSettings *_scaleAnimationSettings;
    SBFFluidBehaviorSettings *_snappyScaleAnimationSettings;
    double _anchorPointY;
    double _hiddenScale;
    double _hiddenBlurRadius;
    double _minTranslationToShowSpotlight;
    double _maxTranslationForSpotlightScale;
    double _spotlightScaleRubberbandingMin;
    double _spotlightScaleRubberbandingMax;
    double _spotlightScaleRubberbandingRange;
    double _maxTranslationForHomeScreenScale;
    double _homeScreenScaleRubberbandingMin;
    double _homeScreenScaleRubberbandingMax;
    double _homeScreenScaleRubberbandingRange;
    double _maxTranslationForHomeScreenDimming;
    double _homeScreenDimmingRubberbandingMin;
    double _homeScreenDimmingRubberbandingMax;
    double _homeScreenDimmingRubberbandingRange;
}


// Remaining properties
@property(nonatomic) double anchorPointY; // @synthesize anchorPointY=_anchorPointY;
@property(nonatomic) double hiddenBlurRadius; // @synthesize hiddenBlurRadius=_hiddenBlurRadius;
@property(nonatomic) double hiddenScale; // @synthesize hiddenScale=_hiddenScale;
@property(nonatomic) double homeScreenDimmingRubberbandingMax; // @synthesize homeScreenDimmingRubberbandingMax=_homeScreenDimmingRubberbandingMax;
@property(nonatomic) double homeScreenDimmingRubberbandingMin; // @synthesize homeScreenDimmingRubberbandingMin=_homeScreenDimmingRubberbandingMin;
@property(nonatomic) double homeScreenDimmingRubberbandingRange; // @synthesize homeScreenDimmingRubberbandingRange=_homeScreenDimmingRubberbandingRange;
@property(nonatomic) double homeScreenScaleRubberbandingMax; // @synthesize homeScreenScaleRubberbandingMax=_homeScreenScaleRubberbandingMax;
@property(nonatomic) double homeScreenScaleRubberbandingMin; // @synthesize homeScreenScaleRubberbandingMin=_homeScreenScaleRubberbandingMin;
@property(nonatomic) double homeScreenScaleRubberbandingRange; // @synthesize homeScreenScaleRubberbandingRange=_homeScreenScaleRubberbandingRange;
@property(nonatomic) double maxTranslationForHomeScreenDimming; // @synthesize maxTranslationForHomeScreenDimming=_maxTranslationForHomeScreenDimming;
@property(nonatomic) double maxTranslationForHomeScreenScale; // @synthesize maxTranslationForHomeScreenScale=_maxTranslationForHomeScreenScale;
@property(nonatomic) double maxTranslationForSpotlightScale; // @synthesize maxTranslationForSpotlightScale=_maxTranslationForSpotlightScale;
@property(nonatomic) double minTranslationToShowSpotlight; // @synthesize minTranslationToShowSpotlight=_minTranslationToShowSpotlight;
@property(retain, nonatomic) SBFFluidBehaviorSettings *opacityAnimationSettings; // @synthesize opacityAnimationSettings=_opacityAnimationSettings;
@property(retain, nonatomic) SBFFluidBehaviorSettings *scaleAnimationSettings; // @synthesize scaleAnimationSettings=_scaleAnimationSettings;
@property(retain, nonatomic) SBFFluidBehaviorSettings *snappyOpacityAnimationSettings; // @synthesize snappyOpacityAnimationSettings=_snappyOpacityAnimationSettings;
@property(retain, nonatomic) SBFFluidBehaviorSettings *snappyScaleAnimationSettings; // @synthesize snappyScaleAnimationSettings=_snappyScaleAnimationSettings;
@property(nonatomic) double spotlightScaleRubberbandingMax; // @synthesize spotlightScaleRubberbandingMax=_spotlightScaleRubberbandingMax;
@property(nonatomic) double spotlightScaleRubberbandingMin; // @synthesize spotlightScaleRubberbandingMin=_spotlightScaleRubberbandingMin;
@property(nonatomic) double spotlightScaleRubberbandingRange; // @synthesize spotlightScaleRubberbandingRange=_spotlightScaleRubberbandingRange;
@end

