//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBBaseStartupTransition.h>

@class SBApplicationController, SBBannerManager, SBFUserAuthenticationController, SBInitialRestartState, SBLockScreenManager, SBSetupManager;

@interface SBStartupTransitionToSetup : SBBaseStartupTransition
{
    SBBannerManager *_bannerManager;
    SBFUserAuthenticationController *_authController;
    SBApplicationController *_appController;
    SBSetupManager *_setupManager;
    SBLockScreenManager *_lockScreenManager;
    SBInitialRestartState *_initialRestartState;
}

@end

