//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/BSDescriptionProviding-Protocol.h>
#import <SpringBoard/BSTransactionObserver-Protocol.h>

@class BSTransaction, BSTransactionBlockObserver, NSSet, NSString, SBInitialRestartState, SBStartupTransitionContextPersistence, SBStartupTransitionFactory;
@protocol SBStartupTransition;

@interface SBStartupTransitionController : NSObject <BSTransactionObserver, BSDescriptionProviding>
{
    SBInitialRestartState *_initialRestartState;
    SBStartupTransitionContextPersistence *_transitionContextPersistence;
    SBStartupTransitionFactory *_transitionFactory;
    BSTransaction<SBStartupTransition> *_transition;
    BSTransactionBlockObserver *_transitionObserver;
    _Bool _ranOnce;
    NSSet *_renderOverlayDismissActions;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) BSTransaction<SBStartupTransition> *startupTransition; // @synthesize startupTransition=_transition;
@property(readonly) Class superclass;
@property(retain, nonatomic, getter=_transitionContextPersistence, setter=_setTransitionContextPersistence:) SBStartupTransitionContextPersistence *transitionContextPersistence; // @synthesize transitionContextPersistence=_transitionContextPersistence;
@property(retain, nonatomic, getter=_transitionFactory, setter=_setTransitionFactory:) SBStartupTransitionFactory *transitionFactory; // @synthesize transitionFactory=_transitionFactory;
@end

