//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBLayoutStateTransitionObserver-Protocol.h>

@class NSString, SBAppLayout, SBMainWorkspaceTransitionRequest, SBUIAnimationController;
@protocol SBSwitcherLiveContentOverlayCoordinatorDelegate;

@protocol SBSwitcherLiveContentOverlayCoordinating <SBLayoutStateTransitionObserver>
@property(nonatomic) __weak id <SBSwitcherLiveContentOverlayCoordinatorDelegate> delegate;
@property(nonatomic) long long containerOrientation;
@property(nonatomic, getter=areLiveContentOverlayUpdatesSuspended) _Bool liveContentOverlayUpdatesSuspended;
- (void)appLayoutDidBecomeHidden:(SBAppLayout *)arg1;
- (void)appLayoutWillBecomeVisible:(SBAppLayout *)arg1;
- (void)noteKeyboardFocusDidChangeToSceneID:(NSString *)arg1;
- (SBUIAnimationController *)animationControllerForTransitionRequest:(SBMainWorkspaceTransitionRequest *)arg1;
@end

