//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/BSInvalidatable-Protocol.h>

@class NSString, STWifiStatusDomainPublisher;

@interface SBSystemStatusWifiDataProvider : NSObject <BSInvalidatable>
{
    _Bool _wifiActive;
    _Bool _fallingBackToCellular;
    STWifiStatusDomainPublisher *_wifiDataPublisher;
    void *_cellularFallbackWatcher;
}


// Remaining properties
@property(nonatomic) void *cellularFallbackWatcher; // @synthesize cellularFallbackWatcher=_cellularFallbackWatcher;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic, getter=isFallingBackToCellular) _Bool fallingBackToCellular; // @synthesize fallingBackToCellular=_fallingBackToCellular;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic, getter=isWifiActive) _Bool wifiActive; // @synthesize wifiActive=_wifiActive;
@property(readonly, nonatomic) STWifiStatusDomainPublisher *wifiDataPublisher; // @synthesize wifiDataPublisher=_wifiDataPublisher;
@end

