//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardUI/SBAlertItem.h>

@class NSString;

@interface SBTestAlertItem : SBAlertItem
{
    _Bool _shouldShowInLockScreen;
    _Bool _forcesModalAlertAppearance;
    _Bool _behavesSuperModally;
    _Bool _allowMenuButtonDismissal;
    _Bool _allowLockScreenDismissal;
    _Bool _reappearsAfterUnlock;
    _Bool _reappearsAfterLock;
    NSString *_title;
}


// Remaining properties
@property(nonatomic) _Bool allowLockScreenDismissal; // @synthesize allowLockScreenDismissal=_allowLockScreenDismissal;
@property(nonatomic) _Bool allowMenuButtonDismissal; // @synthesize allowMenuButtonDismissal=_allowMenuButtonDismissal;
@property(nonatomic) _Bool behavesSuperModally; // @synthesize behavesSuperModally=_behavesSuperModally;
@property(nonatomic) _Bool forcesModalAlertAppearance; // @synthesize forcesModalAlertAppearance=_forcesModalAlertAppearance;
@property(nonatomic) _Bool reappearsAfterLock; // @synthesize reappearsAfterLock=_reappearsAfterLock;
@property(nonatomic) _Bool reappearsAfterUnlock; // @synthesize reappearsAfterUnlock=_reappearsAfterUnlock;
@property(nonatomic) _Bool shouldShowInLockScreen; // @synthesize shouldShowInLockScreen=_shouldShowInLockScreen;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@end

