//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBMainWorkspaceTransaction.h>

#import <SpringBoard/FBSynchronizedTransactionDelegate-Protocol.h>
#import <SpringBoard/SBSceneLayoutWorkspaceTransactionDelegate-Protocol.h>
#import <SpringBoard/SBUIAnimationControllerObserver-Protocol.h>

@class NSCountedSet, NSSet, NSString, SBAppRepairTransaction, SBFloatingDockBehaviorAssertion, SBSceneLayoutWorkspaceTransaction, SBUIAnimationController, UIApplicationSceneDeactivationAssertion;

@interface SBToAppsWorkspaceTransaction : SBMainWorkspaceTransaction <SBSceneLayoutWorkspaceTransactionDelegate, FBSynchronizedTransactionDelegate, SBUIAnimationControllerObserver>
{
    CDUnknownBlockType _transitionCompletion;
    UIApplicationSceneDeactivationAssertion *_resignActiveAssertion;
    CDUnknownBlockType _layoutTransitionContinuation;
    SBAppRepairTransaction *_appRepairTransaction;
    SBUIAnimationController *_animationController;
    NSCountedSet *_completionDelayRequesters;
    _Bool _underLockScreenInForeground;
    _Bool _gestureInitiated;
    unsigned long long _preactivationForegroundRunningApplicationCount;
    _Bool _toAndFromApplicationsDiffer;
    _Bool _retriedAfterVoluntaryExit;
    _Bool _applicationStateNeedsCapture;
    _Bool _dismissedOverlays;
    _Bool _shouldSerialDismissOverlays;
    _Bool _touchCancellationDisabled;
    SBSceneLayoutWorkspaceTransaction *_layoutTransaction;
    SBFloatingDockBehaviorAssertion *_floatingDockBehaviorAssertion;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) SBFloatingDockBehaviorAssertion *floatingDockBehaviorAssertion; // @synthesize floatingDockBehaviorAssertion=_floatingDockBehaviorAssertion;
@property(readonly, nonatomic) NSSet *fromApplicationSceneEntities;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) SBSceneLayoutWorkspaceTransaction *layoutTransaction; // @synthesize layoutTransaction=_layoutTransaction;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSSet *toApplicationSceneEntities;
@end

