//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <SpringBoard/CSExternalBehaviorProviding-Protocol.h>
#import <SpringBoard/PTSettingsKeyObserver-Protocol.h>
#import <SpringBoard/SBFIdleTimerBehaviorProviding-Protocol.h>
#import <SpringBoard/SBHLegibility-Protocol.h>
#import <SpringBoard/SBIconListLayoutObserver-Protocol.h>
#import <SpringBoard/SBIconListModelObserver-Protocol.h>
#import <SpringBoard/SBIconListViewDragDelegate-Protocol.h>
#import <SpringBoard/SBIconLocationPresenting-Protocol.h>
#import <SpringBoard/SBIconViewObserver-Protocol.h>
#import <SpringBoard/SBIconViewQuerying-Protocol.h>
#import <SpringBoard/SBTodayViewSpotlightPresenterDelegate-Protocol.h>
#import <SpringBoard/SBUICoronaAnimationControllerParticipant-Protocol.h>
#import <SpringBoard/SBUISpotlightInitiating-Protocol.h>
#import <SpringBoard/UIScrollViewDelegate-Protocol.h>
#import <SpringBoard/WGMajorListViewControllerDelegate-Protocol.h>
#import <SpringBoard/WGWidgetIconAnimationExtraViewsProviding-Protocol.h>

@class MTMaterialView, NSArray, NSHashTable, NSLayoutConstraint, NSMutableDictionary, NSMutableSet, NSSet, NSString, SBFTouchPassThroughView, SBHDateHeaderViewController, SBHIconManager, SBHWidgetSettings, SBIconListView, SBRootFolder, SBTodayIconListLayoutDelegate, SBTodayKeepOnHomeScreenPlatterView, SBTodayViewSpotlightPresenter, SBViewControllerTransitionContext, UILabel, UIScrollView, UIStackView, UIView, WGMajorListViewController, WGWidgetListHeaderView, _UILegibilitySettings;
@protocol SBIconListLayoutProvider, SBIconViewProviding, SBTodayViewControllerDelegate;

@interface SBTodayViewController : UIViewController <SBUICoronaAnimationControllerParticipant, SBIconListLayoutObserver, SBIconViewObserver, UIScrollViewDelegate, SBIconListModelObserver, SBIconListViewDragDelegate, WGMajorListViewControllerDelegate, WGWidgetIconAnimationExtraViewsProviding, PTSettingsKeyObserver, SBTodayViewSpotlightPresenterDelegate, CSExternalBehaviorProviding, SBUISpotlightInitiating, SBHLegibility, SBIconViewQuerying, SBIconLocationPresenting, SBFIdleTimerBehaviorProviding>
{
    _Bool _suppressesEditingStateForListViews;
    _Bool _headerVisible;
    _Bool _spotlightVisible;
    _Bool _visuallyRevealedPriorToEditingIcons;
    _UILegibilitySettings *_legibilitySettings;
    SBViewControllerTransitionContext *_transitionContext;
    SBRootFolder *_rootFolder;
    SBHIconManager *_iconManager;
    id <SBTodayViewControllerDelegate> _delegate;
    UIViewController *_containerViewController;
    WGMajorListViewController *_legacyWidgetListViewController;
    id <SBIconListLayoutProvider> _defaultListLayoutProvider;
    id <SBIconViewProviding> _iconViewProvider;
    long long _location;
    SBHWidgetSettings *_widgetSettings;
    UIScrollView *_scrollView;
    UIStackView *_stackView;
    UIView *_fixedContentSizeView;
    SBIconListView *_listView;
    UIView *_favoriteListContainerView;
    MTMaterialView *_favoriteListPlatterView;
    UILabel *_favoriteListInstructionLabel;
    SBIconListView *_favoriteListView;
    NSLayoutConstraint *_favoriteListWithLargeWidgetMinimumHeightConstraint;
    NSLayoutConstraint *_favoriteListWithSmallOrMediumWidgetsMinimumHeightConstraint;
    SBTodayIconListLayoutDelegate *_listLayoutDelegate;
    SBTodayIconListLayoutDelegate *_favoriteListLayoutDelegate;
    UIView *_carouselReferenceForLegacyWidgetListView;
    UIView *_headerContainerView;
    SBTodayKeepOnHomeScreenPlatterView *_keepOnHomeScreenPlatterView;
    WGWidgetListHeaderView *_dateHeaderView;
    SBHDateHeaderViewController *_dateHeaderViewController;
    NSMutableDictionary *_cancelTouchesAssertionsByLegacyWidgetID;
    NSMutableDictionary *_cancelTouchesAssertionsByWidgetID;
    SBTodayViewSpotlightPresenter *_spotlightPresenter;
    SBFTouchPassThroughView *_spotlightContainerView;
    NSLayoutConstraint *_stackViewToScrollViewTopConstraint;
    NSLayoutConstraint *_stackViewToScrollViewBottomConstraint;
    NSMutableSet *_suspendVisibleRowRangeUpdatesReasons;
    NSMutableSet *_widgetHitTestingDisabledReasons;
    double _searchBarTopOffset;
    NSHashTable *_viewControllerAppearStateOverrideAssertions;
}


// Remaining properties
@property(retain, nonatomic) NSMutableDictionary *cancelTouchesAssertionsByLegacyWidgetID; // @synthesize cancelTouchesAssertionsByLegacyWidgetID=_cancelTouchesAssertionsByLegacyWidgetID;
@property(retain, nonatomic) NSMutableDictionary *cancelTouchesAssertionsByWidgetID; // @synthesize cancelTouchesAssertionsByWidgetID=_cancelTouchesAssertionsByWidgetID;
@property(retain, nonatomic) UIView *carouselReferenceForLegacyWidgetListView; // @synthesize carouselReferenceForLegacyWidgetListView=_carouselReferenceForLegacyWidgetListView;
@property(nonatomic) __weak UIViewController *containerViewController; // @synthesize containerViewController=_containerViewController;
@property(readonly, copy, nonatomic) NSString *coverSheetIdentifier;
@property(readonly, nonatomic) double customIdleExpirationTimeout;
@property(readonly, nonatomic) double customIdleWarningTimeout;
@property(retain, nonatomic) WGWidgetListHeaderView *dateHeaderView; // @synthesize dateHeaderView=_dateHeaderView;
@property(retain, nonatomic) SBHDateHeaderViewController *dateHeaderViewController; // @synthesize dateHeaderViewController=_dateHeaderViewController;
@property(readonly, copy) NSString *debugDescription;
@property(retain, nonatomic) id <SBIconListLayoutProvider> defaultListLayoutProvider; // @synthesize defaultListLayoutProvider=_defaultListLayoutProvider;
@property(nonatomic) __weak id <SBTodayViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
@property(readonly, copy, nonatomic) NSArray *extraViews;
@property(readonly, copy, nonatomic) NSArray *extraViewsContainers;
@property(retain, nonatomic) UIView *favoriteListContainerView; // @synthesize favoriteListContainerView=_favoriteListContainerView;
@property(retain, nonatomic) UILabel *favoriteListInstructionLabel; // @synthesize favoriteListInstructionLabel=_favoriteListInstructionLabel;
@property(retain, nonatomic) SBTodayIconListLayoutDelegate *favoriteListLayoutDelegate; // @synthesize favoriteListLayoutDelegate=_favoriteListLayoutDelegate;
@property(retain, nonatomic) MTMaterialView *favoriteListPlatterView; // @synthesize favoriteListPlatterView=_favoriteListPlatterView;
@property(retain, nonatomic) SBIconListView *favoriteListView; // @synthesize favoriteListView=_favoriteListView;
@property(retain, nonatomic) NSLayoutConstraint *favoriteListWithLargeWidgetMinimumHeightConstraint; // @synthesize favoriteListWithLargeWidgetMinimumHeightConstraint=_favoriteListWithLargeWidgetMinimumHeightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *favoriteListWithSmallOrMediumWidgetsMinimumHeightConstraint; // @synthesize favoriteListWithSmallOrMediumWidgetsMinimumHeightConstraint=_favoriteListWithSmallOrMediumWidgetsMinimumHeightConstraint;
@property(retain, nonatomic) UIView *fixedContentSizeView; // @synthesize fixedContentSizeView=_fixedContentSizeView;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) UIView *headerContainerView; // @synthesize headerContainerView=_headerContainerView;
@property(nonatomic, getter=isHeaderVisible) _Bool headerVisible; // @synthesize headerVisible=_headerVisible;
@property(nonatomic) __weak SBHIconManager *iconManager; // @synthesize iconManager=_iconManager;
@property(retain, nonatomic) id <SBIconViewProviding> iconViewProvider; // @synthesize iconViewProvider=_iconViewProvider;
@property(readonly, nonatomic) long long idleTimerDuration;
@property(readonly, nonatomic) long long idleTimerMode;
@property(readonly, nonatomic) long long idleWarnMode;
@property(retain, nonatomic) SBTodayKeepOnHomeScreenPlatterView *keepOnHomeScreenPlatterView; // @synthesize keepOnHomeScreenPlatterView=_keepOnHomeScreenPlatterView;
@property(readonly, nonatomic) WGMajorListViewController *legacyWidgetListViewController; // @synthesize legacyWidgetListViewController=_legacyWidgetListViewController;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
@property(retain, nonatomic) SBTodayIconListLayoutDelegate *listLayoutDelegate; // @synthesize listLayoutDelegate=_listLayoutDelegate;
@property(retain, nonatomic) SBIconListView *listView; // @synthesize listView=_listView;
@property(nonatomic) long long location; // @synthesize location=_location;
@property(readonly, nonatomic) long long notificationBehavior;
@property(readonly, nonatomic) long long participantState;
@property(readonly, copy, nonatomic) NSSet *presentedIconLocations;
@property(readonly, nonatomic) long long proximityDetectionMode;
@property(readonly, nonatomic) unsigned long long restrictedCapabilities;
@property(retain, nonatomic) SBRootFolder *rootFolder; // @synthesize rootFolder=_rootFolder;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(readonly, nonatomic) long long scrollingStrategy;
@property(readonly, nonatomic) double searchBarTopOffset; // @synthesize searchBarTopOffset=_searchBarTopOffset;
@property(readonly, nonatomic) _Bool shouldAnimateFirstTwoViewsAsOne;
@property(readonly, nonatomic) _Bool shouldAnimateLastTwoViewsAsOne;
@property(retain, nonatomic) SBFTouchPassThroughView *spotlightContainerView; // @synthesize spotlightContainerView=_spotlightContainerView;
@property(retain, nonatomic) SBTodayViewSpotlightPresenter *spotlightPresenter; // @synthesize spotlightPresenter=_spotlightPresenter;
@property(nonatomic, getter=isSpotlightVisible) _Bool spotlightVisible; // @synthesize spotlightVisible=_spotlightVisible;
@property(retain, nonatomic) UIStackView *stackView; // @synthesize stackView=_stackView;
@property(readonly, nonatomic) NSLayoutConstraint *stackViewToScrollViewBottomConstraint; // @synthesize stackViewToScrollViewBottomConstraint=_stackViewToScrollViewBottomConstraint;
@property(readonly, nonatomic) NSLayoutConstraint *stackViewToScrollViewTopConstraint; // @synthesize stackViewToScrollViewTopConstraint=_stackViewToScrollViewTopConstraint;
@property(readonly) Class superclass;
@property(nonatomic) _Bool suppressesEditingStateForListViews; // @synthesize suppressesEditingStateForListViews=_suppressesEditingStateForListViews;
@property(retain, nonatomic) NSMutableSet *suspendVisibleRowRangeUpdatesReasons; // @synthesize suspendVisibleRowRangeUpdatesReasons=_suspendVisibleRowRangeUpdatesReasons;
@property(retain, nonatomic) SBViewControllerTransitionContext *transitionContext; // @synthesize transitionContext=_transitionContext;
@property(retain, nonatomic) NSHashTable *viewControllerAppearStateOverrideAssertions; // @synthesize viewControllerAppearStateOverrideAssertions=_viewControllerAppearStateOverrideAssertions;
@property(nonatomic) _Bool visuallyRevealedPriorToEditingIcons; // @synthesize visuallyRevealedPriorToEditingIcons=_visuallyRevealedPriorToEditingIcons;
@property(retain, nonatomic) NSMutableSet *widgetHitTestingDisabledReasons; // @synthesize widgetHitTestingDisabledReasons=_widgetHitTestingDisabledReasons;
@property(retain, nonatomic) SBHWidgetSettings *widgetSettings; // @synthesize widgetSettings=_widgetSettings;
@end

