//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <SpringBoard/BSDescriptionProviding-Protocol.h>
#import <SpringBoard/SBButtonEventsHandler-Protocol.h>
#import <SpringBoard/SBFIdleTimerBehaviorProviding-Protocol.h>
#import <SpringBoard/SBHomeGrabberDelegate-Protocol.h>
#import <SpringBoard/SBIdleTimerProviding-Protocol.h>

@class FBDisplayLayoutElement, NSNumber, NSString, SBDisplayItem, SBFHomeGrabberSettings, SBHomeGrabberView, SBKeyboardHomeAffordanceAssertion, UIStatusBar, UIStatusBarStyleRequest, UIView, UIWindow, _UILegibilitySettings;
@protocol SBIdleTimerCoordinating, SBTransientOverlayViewControllerDelegate;

@interface SBTransientOverlayViewController : UIViewController <SBHomeGrabberDelegate, BSDescriptionProviding, SBButtonEventsHandler, SBFIdleTimerBehaviorProviding, SBIdleTimerProviding>
{
    long long _appearanceUpdateIgnoreCount;
    UIView *_contentContainerView;
    UIView *_homeGrabberContainerView;
    long long _contentOverlayInsetUpdateIgnoreCount;
    SBFHomeGrabberSettings *_grabberSettings;
    _Bool _hasPreservedInputViews;
    _Bool _isDisplayLayoutElementActive;
    SBKeyboardHomeAffordanceAssertion *_keyboardHomeAffordanceAssertion;
    UIWindow *_keyboardHomeAffordanceAssertionWindow;
    UIView *_presentationBackgroundView;
    long long _presentationPrefersHomeGrabberHidden;
    UIStatusBar *_statusBar;
    long long _keyboardVisible;
    _Bool _allowsStackingOverlayContentAbove;
    _Bool _contentOpaque;
    _Bool _prefersProximityDetectionEnabled;
    _Bool _prefersStatusBarActivityItemVisible;
    _Bool _shouldDisableBanners;
    _Bool _shouldDisableControlCenter;
    _Bool _shouldDisableReachability;
    _Bool _shouldDisableInteractiveScreenshotGesture;
    _Bool _shouldDisableSiri;
    _Bool _shouldPendAlertItems;
    _Bool _shouldDisableOrientationUpdates;
    _Bool _prefersWindowHitTestingDisabled;
    _Bool _presentationAllowsHomeGrabberAutoHide;
    _Bool _presentationPrefersStatusBarHidden;
    _Bool _dismissesForCoverSheetPresentation;
    int _preferredStatusBarStyleOverridesToCancel;
    int _pictureInPictureProcessIdentifier;
    UIView *_contentView;
    UIView *_backgroundView;
    id <SBIdleTimerCoordinating> _idleTimerCoordinator;
    long long _containerOrientation;
    long long _preferredLockedGestureDismissalStyle;
    long long _preferredUnlockedGestureDismissalStyle;
    SBDisplayItem *_representedDisplayItem;
    FBDisplayLayoutElement *_displayLayoutElement;
    id <SBTransientOverlayViewControllerDelegate> _transientOverlayDelegate;
    UIStatusBarStyleRequest *_currentStatusBarStyleRequest;
    SBHomeGrabberView *_grabberView;
    double _presentationContentCornerRadius;
    double _presentationHomeGrabberAlpha;
    double _presentationHomeGrabberAdditionalEdgeSpacing;
    struct CGAffineTransform _presentationContentTransform;
    struct CGAffineTransform _presentationHomeGrabberTransform;
}


// Remaining properties
@property(readonly, nonatomic) _Bool allowsStackingOverlayContentAbove; // @synthesize allowsStackingOverlayContentAbove=_allowsStackingOverlayContentAbove;
@property(readonly, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) long long containerOrientation; // @synthesize containerOrientation=_containerOrientation;
@property(readonly, nonatomic, getter=isContentOpaque) _Bool contentOpaque; // @synthesize contentOpaque=_contentOpaque;
@property(readonly, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(readonly, copy, nonatomic) UIStatusBarStyleRequest *currentStatusBarStyleRequest; // @synthesize currentStatusBarStyleRequest=_currentStatusBarStyleRequest;
@property(readonly, nonatomic) double customIdleExpirationTimeout;
@property(readonly, nonatomic) double customIdleWarningTimeout;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) _Bool dismissesForCoverSheetPresentation; // @synthesize dismissesForCoverSheetPresentation=_dismissesForCoverSheetPresentation;
@property(retain, nonatomic) FBDisplayLayoutElement *displayLayoutElement; // @synthesize displayLayoutElement=_displayLayoutElement;
@property(retain, nonatomic) SBHomeGrabberView *grabberView; // @synthesize grabberView=_grabberView;
@property(readonly, nonatomic) _Bool hasVisibleStatusBar;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) long long homeAffordanceSuppression;
@property(nonatomic) __weak id <SBIdleTimerCoordinating> idleTimerCoordinator; // @synthesize idleTimerCoordinator=_idleTimerCoordinator;
@property(readonly, nonatomic) long long idleTimerDuration;
@property(readonly, nonatomic) long long idleTimerMode;
@property(readonly, nonatomic) long long idleWarnMode;
@property(readonly, nonatomic) _Bool isIgnoringAppearanceUpdates;
@property(readonly, nonatomic) _Bool isIgnoringContentOverlayInsetUpdates;
@property(readonly, nonatomic) int pictureInPictureProcessIdentifier; // @synthesize pictureInPictureProcessIdentifier=_pictureInPictureProcessIdentifier;
@property(readonly, copy, nonatomic) NSString *preferredDisplayLayoutElementIdentifier;
@property(readonly, nonatomic) long long preferredLockedGestureDismissalStyle; // @synthesize preferredLockedGestureDismissalStyle=_preferredLockedGestureDismissalStyle;
@property(readonly, copy, nonatomic) NSNumber *preferredSceneDeactivationReasonValue;
@property(readonly, copy, nonatomic) _UILegibilitySettings *preferredStatusBarLegibilitySettings;
@property(readonly, nonatomic) int preferredStatusBarStyleOverridesToCancel; // @synthesize preferredStatusBarStyleOverridesToCancel=_preferredStatusBarStyleOverridesToCancel;
@property(readonly, nonatomic) long long preferredUnlockedGestureDismissalStyle; // @synthesize preferredUnlockedGestureDismissalStyle=_preferredUnlockedGestureDismissalStyle;
@property(readonly, nonatomic) _Bool prefersProximityDetectionEnabled; // @synthesize prefersProximityDetectionEnabled=_prefersProximityDetectionEnabled;
@property(readonly, nonatomic) _Bool prefersStatusBarActivityItemVisible; // @synthesize prefersStatusBarActivityItemVisible=_prefersStatusBarActivityItemVisible;
@property(readonly, nonatomic) _Bool prefersWindowHitTestingDisabled; // @synthesize prefersWindowHitTestingDisabled=_prefersWindowHitTestingDisabled;
@property(nonatomic) _Bool presentationAllowsHomeGrabberAutoHide; // @synthesize presentationAllowsHomeGrabberAutoHide=_presentationAllowsHomeGrabberAutoHide;
@property(nonatomic) double presentationContentCornerRadius; // @synthesize presentationContentCornerRadius=_presentationContentCornerRadius;
@property(nonatomic) struct CGAffineTransform presentationContentTransform; // @synthesize presentationContentTransform=_presentationContentTransform;
@property(nonatomic) double presentationHomeGrabberAdditionalEdgeSpacing; // @synthesize presentationHomeGrabberAdditionalEdgeSpacing=_presentationHomeGrabberAdditionalEdgeSpacing;
@property(nonatomic) double presentationHomeGrabberAlpha; // @synthesize presentationHomeGrabberAlpha=_presentationHomeGrabberAlpha;
@property(nonatomic) struct CGAffineTransform presentationHomeGrabberTransform; // @synthesize presentationHomeGrabberTransform=_presentationHomeGrabberTransform;
@property(readonly, nonatomic) _Bool presentationPrefersStatusBarHidden; // @synthesize presentationPrefersStatusBarHidden=_presentationPrefersStatusBarHidden;
@property(readonly, copy, nonatomic) SBDisplayItem *representedDisplayItem; // @synthesize representedDisplayItem=_representedDisplayItem;
@property(readonly, copy, nonatomic) CDUnknownBlockType sceneDeactivationPredicate;
@property(readonly, nonatomic) _Bool shouldDisableBanners; // @synthesize shouldDisableBanners=_shouldDisableBanners;
@property(readonly, nonatomic) _Bool shouldDisableControlCenter; // @synthesize shouldDisableControlCenter=_shouldDisableControlCenter;
@property(readonly, nonatomic) _Bool shouldDisableInteractiveScreenshotGesture; // @synthesize shouldDisableInteractiveScreenshotGesture=_shouldDisableInteractiveScreenshotGesture;
@property(readonly, nonatomic) _Bool shouldDisableOrientationUpdates; // @synthesize shouldDisableOrientationUpdates=_shouldDisableOrientationUpdates;
@property(readonly, nonatomic) _Bool shouldDisableReachability; // @synthesize shouldDisableReachability=_shouldDisableReachability;
@property(readonly, nonatomic) _Bool shouldDisableSiri; // @synthesize shouldDisableSiri=_shouldDisableSiri;
@property(readonly, nonatomic) _Bool shouldPendAlertItems; // @synthesize shouldPendAlertItems=_shouldPendAlertItems;
@property(readonly) Class superclass;
@property(nonatomic) __weak id <SBTransientOverlayViewControllerDelegate> transientOverlayDelegate; // @synthesize transientOverlayDelegate=_transientOverlayDelegate;
@end

