//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBButtonEventsHandler-Protocol.h>
#import <SpringBoard/SBHomeGestureParticipantDelegate-Protocol.h>
#import <SpringBoard/SBHomeGrabberPointerClickDelegate-Protocol.h>
#import <SpringBoard/SBIdleTimerCoordinating-Protocol.h>
#import <SpringBoard/SBIdleTimerProviding-Protocol.h>
#import <SpringBoard/SBTransientOverlayViewControllerDelegate-Protocol.h>

@class NSMapTable, NSMutableArray, NSNumber, NSString, SBAlertItemsController, SBAppStatusBarSettingsAssertion, SBBannerManager, SBCoverSheetPresentationManager, SBHomeGestureArbiter, SBHomeGestureParticipant, SBIdleTimerCoordinatorHelper, SBInAppStatusBarHiddenAssertion, SBLockStateAggregator, SBReachabilityManager, SBTransientOverlayViewController, UIScreen, UIStatusBarStyleRequest, UIWindow;
@protocol BSInvalidatable, CSExternalBehaviorProviding, SBIdleTimerCoordinating, SBTransientOverlayPresentationManagerDelegate;

@interface SBTransientOverlayPresentationManager : NSObject <SBHomeGestureParticipantDelegate, SBHomeGrabberPointerClickDelegate, SBIdleTimerCoordinating, SBTransientOverlayViewControllerDelegate, SBIdleTimerProviding, SBButtonEventsHandler>
{
    SBAlertItemsController *_alertItemsController;
    SBBannerManager *_bannerManager;
    id <BSInvalidatable> _bannerSuppressionAssertion;
    NSMutableArray *_contentStatusBarHiddenAssertions;
    id <CSExternalBehaviorProviding> _coverSheetExternalBehaviorProvider;
    id <BSInvalidatable> _deviceOrientationUpdateDeferralAssertion;
    NSMutableArray *_entities;
    NSMapTable *_entityToSceneDeactivationAssertion;
    SBHomeGestureArbiter *_homeGestureArbiter;
    SBHomeGestureParticipant *_homeGestureParticipant;
    SBIdleTimerCoordinatorHelper *_idleTimerCoordinatorHelper;
    UIWindow *_initialPresentationKeyWindow;
    id <BSInvalidatable> _interactiveScreenshotGestureDisabledAssertion;
    _Bool _isInitiatingEntityPresentation;
    _Bool _isPendingAlertItems;
    _Bool _isReachabilityTemporarilyDisabled;
    SBLockStateAggregator *_lockStateAggregator;
    SBReachabilityManager *_reachabilityManager;
    UIScreen *_screen;
    SBAppStatusBarSettingsAssertion *_globalStatusBarAssertion;
    SBInAppStatusBarHiddenAssertion *_appStatusBarAssertion;
    _Bool _prefersStatusBarActivityItemVisible;
    NSNumber *_preferredWhitePointAdaptivityStyleValue;
    long long _topmostViewControllerInterfaceOrientation;
    SBCoverSheetPresentationManager *_coverSheetPresentationManager;
    id <SBTransientOverlayPresentationManagerDelegate> _delegate;
}


// Remaining properties
@property(retain, nonatomic) SBBannerManager *bannerManager; // @synthesize bannerManager=_bannerManager;
@property(readonly, nonatomic) _Bool canHandleButtonEvents;
@property(retain, nonatomic) SBCoverSheetPresentationManager *coverSheetPresentationManager; // @synthesize coverSheetPresentationManager=_coverSheetPresentationManager;
@property(readonly, copy, nonatomic) UIStatusBarStyleRequest *currentStatusBarStyleRequest;
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <SBTransientOverlayPresentationManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) _Bool hasActivePresentation;
@property(readonly, nonatomic) _Bool hasIdleTimerBehaviors;
@property(readonly, nonatomic) _Bool hasVisibleStatusBar;
@property(readonly) unsigned long long hash;
@property(nonatomic) __weak id <SBIdleTimerCoordinating> idleTimerCoordinator;
@property(readonly, nonatomic) _Bool ownsHomeGesture;
@property(readonly, nonatomic) long long preferredGestureDismissalStyle;
@property(readonly, nonatomic) NSNumber *preferredWhitePointAdaptivityStyleValue; // @synthesize preferredWhitePointAdaptivityStyleValue=_preferredWhitePointAdaptivityStyleValue;
@property(readonly, nonatomic) _Bool prefersStatusBarActivityItemVisible; // @synthesize prefersStatusBarActivityItemVisible=_prefersStatusBarActivityItemVisible;
@property(readonly, nonatomic) long long presentedViewControllerCount;
@property(readonly, nonatomic) _Bool shouldDisableControlCenter;
@property(readonly, nonatomic) _Bool shouldDisableCoverSheetGesture;
@property(readonly, nonatomic) _Bool shouldDisableSiri;
@property(readonly) Class superclass;
@property(readonly, nonatomic) SBTransientOverlayViewController *topmostPresentedViewController;
@property(readonly, nonatomic) long long topmostViewControllerInterfaceOrientation; // @synthesize topmostViewControllerInterfaceOrientation=_topmostViewControllerInterfaceOrientation;
@property(readonly, nonatomic) double topmostWindowLevel;
@property(readonly, nonatomic) SBTransientOverlayViewController *viewControllerForGestureDismissal;
@end

