//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBToAppsWorkspaceTransaction.h>

@class NSArray, SBAutoPiPWorkspaceTransaction;
@protocol BSInvalidatable;

@interface SBTransientOverlayDismissAllToAppsWorkspaceTransaction : SBToAppsWorkspaceTransaction
{
    NSArray *_switcherTransitioningTransientOverlayViewControllers;
    SBAutoPiPWorkspaceTransaction *_autoPiPTransaction;
    id <BSInvalidatable> _pipWindowLevelOverrideAssertionInvalidatable;
    _Bool _isUsingSwitcherAnimation;
    _Bool _beganDismissingTransientOverlays;
}

@end

