//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/SBTransaction.h>

#import <SpringBoard/SBSceneHandleObserver-Protocol.h>
#import <SpringBoard/SBUIAnimationControllerCoordinating-Protocol.h>
#import <SpringBoard/SBUIAnimationStepping-Protocol.h>
#import <SpringBoard/SBViewControllerTransitionContextDelegate-Protocol.h>
#import <SpringBoard/UIViewControllerInteractiveTransitioning-Protocol.h>

@class BSAnimationSettings, BSBlockTransaction, BSTransaction, NSMutableArray, NSSet, NSString, SBAnimationStepper, SBApplicationSceneEntity, SBViewControllerTransitionContext, UIView, UIWindow;
@protocol SBUIAnimationControllerTransitionContextProvider, SBViewControllerTransitionCoordinator;

@interface SBUIAnimationController : SBTransaction <SBSceneHandleObserver, UIViewControllerInteractiveTransitioning, SBViewControllerTransitionContextDelegate, SBUIAnimationStepping, SBUIAnimationControllerCoordinating>
{
    id <SBUIAnimationControllerTransitionContextProvider> _transitionContextProvider;
    BSBlockTransaction *_animationTransaction;
    BSBlockTransaction *_notifyObserversTransaction;
    BSBlockTransaction *_cleanupTransaction;
    NSSet *_sceneHandlesBeingObserved;
    NSSet *_entitiesToObserve;
    NSSet *_startTransactionDependencies;
    NSMutableArray *_coordinatingChildRelationships;
    NSMutableArray *_steppedCoordinatingChildAnimations;
    SBAnimationStepper *_stepper;
    UIWindow *_transitionWindow;
    UIView *_transitionContainer;
    int _animationState;
    _Bool _didPostBeginAnimationNotification;
    _Bool _didNotifyObserversOfCompletion;
    _Bool _needsCATransactionActivate;
    SBViewControllerTransitionContext *_transition;
    CDUnknownBlockType _animationTransactionCompletion;
}


// Remaining properties
@property(readonly, nonatomic) BSAnimationSettings *animationSettings;
@property(readonly, nonatomic) BSTransaction *animationTransaction; // @synthesize animationTransaction=_animationTransaction;
@property(copy, nonatomic) CDUnknownBlockType animationTransactionCompletion; // @synthesize animationTransactionCompletion=_animationTransactionCompletion;
@property(readonly, nonatomic) BSTransaction *cleanupTransaction; // @synthesize cleanupTransaction=_cleanupTransaction;
@property(readonly, nonatomic) long long completionCurve;
@property(readonly, nonatomic) double completionSpeed;
@property(readonly, nonatomic) UIView *containerView; // @synthesize containerView=_transitionContainer;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, copy, nonatomic) NSSet *fromApplicationSceneEntities;
@property(readonly, nonatomic) SBApplicationSceneEntity *fromApplicationSceneEntity;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic, getter=isInteractive) _Bool interactive;
@property(nonatomic) _Bool needsCATransactionActivate; // @synthesize needsCATransactionActivate=_needsCATransactionActivate;
@property(readonly, nonatomic) BSTransaction *notifyObserversTransaction; // @synthesize notifyObserversTransaction=_notifyObserversTransaction;
@property(nonatomic) double stepPercentage;
@property(readonly, nonatomic, getter=isStepped) _Bool stepped;
@property(readonly) Class superclass;
@property(readonly, copy, nonatomic) NSSet *toApplicationSceneEntities;
@property(readonly, nonatomic) SBApplicationSceneEntity *toApplicationSceneEntity;
@property(retain, nonatomic) SBViewControllerTransitionContext *transition; // @synthesize transition=_transition;
@property(retain, nonatomic) id <SBUIAnimationControllerTransitionContextProvider> transitionContextProvider; // @synthesize transitionContextProvider=_transitionContextProvider;
@property(readonly, nonatomic) id <SBViewControllerTransitionCoordinator> transitionCoordinator;
@property(readonly, nonatomic) _Bool transitionSupportsCancelling;
@property(readonly, nonatomic) _Bool transitionSupportsRestarting;
@property(readonly, nonatomic) _Bool transitionWasCancelled;
@property(readonly, nonatomic) _Bool transitionWasRestarted;
@property(readonly, nonatomic) _Bool wantsInteractiveStart;
@end

