//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBLogoutProgressDataSource-Protocol.h>
#import <SpringBoard/SBLogoutProgressDelegate-Protocol.h>
#import <SpringBoard/UMCriticalUserSwitchStakeholder-Protocol.h>

@class LKLogoutSupport, NSDate, NSDictionary, NSMutableArray, NSMutableSet, NSString, SBLogoutProgressTransientOverlayViewController, SBMainDisplayPolicyAggregator, UMUser, UMUserManager, UMUserSwitchBlockingTask;

@interface SBUserSessionController : NSObject <SBLogoutProgressDataSource, SBLogoutProgressDelegate, UMCriticalUserSwitchStakeholder>
{
    UMUserManager *_userManager;
    UMUser *_lazy_user;
    SBMainDisplayPolicyAggregator *_lazy_policyAggregator;
    SBLogoutProgressTransientOverlayViewController *_progressTransientOverlayViewController;
    NSMutableArray *_displayApplications;
    NSMutableSet *_terminatingApplications;
    UMUserSwitchBlockingTask *_terminateApplicationsTask;
    NSDate *_terminateApplicationsStartDate;
    NSDictionary *_debugBlockingTasks;
    LKLogoutSupport *_logoutSupport;
    _Bool _loginSession;
    _Bool _loggingOut;
}


// Remaining properties
@property(readonly, nonatomic) _Bool canLogout;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isMultiUserSupported;
@property(nonatomic, getter=isLoggingOut) _Bool loggingOut; // @synthesize loggingOut=_loggingOut;
@property(readonly, nonatomic, getter=isLoginSession) _Bool loginSession; // @synthesize loginSession=_loginSession;
@property(retain, nonatomic, getter=_policyAggregator, setter=_setPolicyAggregator:) SBMainDisplayPolicyAggregator *policyAggregator; // @synthesize policyAggregator=_lazy_policyAggregator;
@property(readonly, nonatomic) long long sessionType;
@property(readonly) Class superclass;
@property(readonly, retain, nonatomic) UMUser *user;
@end

