//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/NSObject-Protocol.h>

@class UIColor, _UILegibilitySettings;

@protocol SBWallpaperLegibilityProviding <NSObject>
- (double)contrastInRect:(struct CGRect)arg1 forVariant:(long long)arg2;
- (double)contrastForVariant:(long long)arg1;
- (UIColor *)averageColorInRect:(struct CGRect)arg1 forVariant:(long long)arg2 withSmudgeRadius:(double)arg3;
- (UIColor *)averageColorInRect:(struct CGRect)arg1 forVariant:(long long)arg2;
- (UIColor *)averageColorForVariant:(long long)arg1;
- (_UILegibilitySettings *)legibilitySettingsForVariant:(long long)arg1;
@end

