//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/BSDescriptionProviding-Protocol.h>

@class NSString, SBWallpaperEffectViewBase;

@interface SBWallpaperStyleInfo : NSObject <BSDescriptionProviding>
{
    struct {
        _Bool valid;
        CDStruct_059c2b36 styleTransitionState;
    } _priorityInfo[12];
    SBWallpaperEffectViewBase *_wallpaperEffectView;
    CDStruct_059c2b36 _styleTransitionState;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) long long highestValidPriority;
@property(nonatomic) CDStruct_059c2b36 styleTransitionState; // @synthesize styleTransitionState=_styleTransitionState;
@property(readonly) Class superclass;
@property(retain, nonatomic) SBWallpaperEffectViewBase *wallpaperEffectView; // @synthesize wallpaperEffectView=_wallpaperEffectView;
@end

