//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIScenePresentationContext, UIView, UIWindow;
@protocol UIScenePresentation, UIScenePresenter;

@interface SBWindowSelfHostWrapper : NSObject
{
    UIWindow *_window;
    id <UIScenePresenter> _presenter;
    UIView<UIScenePresentation> *_hostView;
}


// Remaining properties
@property(readonly, nonatomic) UIView<UIScenePresentation> *hostView; // @synthesize hostView=_hostView;
@property(readonly, copy, nonatomic) UIScenePresentationContext *presentationContext;
@property(readonly, nonatomic) id <UIScenePresenter> presenter; // @synthesize presenter=_presenter;
@property(readonly, copy, nonatomic) NSString *requester;
@property(readonly, nonatomic) UIWindow *window; // @synthesize window=_window;
@end

