//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBWindowHideState : NSObject
{
    _Bool _hidden;
    double _desiredAlpha;
}


// Remaining properties
@property double desiredAlpha; // @synthesize desiredAlpha=_desiredAlpha;
@property(getter=isHidden) _Bool hidden; // @synthesize hidden=_hidden;
@end

