//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoard/NSObject-Protocol.h>

@class SBLayoutState, SBWorkspaceApplicationSceneTransitionContext, SBWorkspaceEntity;

@protocol SBWorkspaceApplicationSceneTransitionContextDelegate <NSObject>
- (struct CGRect)applicationTransitionContext:(SBWorkspaceApplicationSceneTransitionContext *)arg1 frameForApplicationSceneEntity:(SBWorkspaceEntity *)arg2;
- (SBLayoutState *)previousLayoutStateForApplicationTransitionContext:(SBWorkspaceApplicationSceneTransitionContext *)arg1;
- (SBLayoutState *)layoutStateForApplicationTransitionContext:(SBWorkspaceApplicationSceneTransitionContext *)arg1;
@end

