//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBIdleTimerCoordinating-Protocol.h>
#import <SpringBoard/SBIdleTimerProviding-Protocol.h>

@class FBWorkspaceEventQueue, NSString, SBWorkspaceTransaction;

@interface SBWorkspace : NSObject <SBIdleTimerProviding, SBIdleTimerCoordinating>
{
    FBWorkspaceEventQueue *_eventQueue;
    SBWorkspaceTransaction *_currentTransaction;
}


// Remaining properties
@property(readonly, nonatomic) SBWorkspaceTransaction *currentTransaction; // @synthesize currentTransaction=_currentTransaction;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) FBWorkspaceEventQueue *eventQueue; // @synthesize eventQueue=_eventQueue;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

