//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface UIGestureRecognizerTransformAnalyzerInfo : NSObject
{
    double _translationMagnitude;
    double _scale;
    double _rotation;
    struct CGPoint _translation;
    struct CGPoint _absoluteTranslation;
}


// Remaining properties
@property(nonatomic, setter=_setAbsoluteTranslation:) struct CGPoint absoluteTranslation; // @synthesize absoluteTranslation=_absoluteTranslation;
@property(nonatomic, setter=_setRotation:) double rotation; // @synthesize rotation=_rotation;
@property(nonatomic, setter=_setScale:) double scale; // @synthesize scale=_scale;
@property(nonatomic, setter=_setTranslation:) struct CGPoint translation; // @synthesize translation=_translation;
@property(nonatomic, setter=_setTranslationMagnitude:) double translationMagnitude; // @synthesize translationMagnitude=_translationMagnitude;
@end

