/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:48:33 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libMemoryResourceException.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@class NSArray;

@interface FPImageEnumerator : NSObject {

	NSArray* _images;
	unsigned long long _index;

}
-(id)initWithImages:(id)arg1 ;
-(id)nextImageForStart:(unsigned long long)arg1 end:(unsigned long long)arg2 ;
@end

