/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:48:33 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libMemoryResourceException.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@class NSMutableSet;

@interface FPProcessGroupMinimal : NSObject {

	NSMutableSet* _processes;
	unsigned long long _hashValue;

}

@property (nonatomic,retain) NSMutableSet * processes;                  //@synthesize processes=_processes - In the implementation block
@property (assign,nonatomic) unsigned long long hashValue;              //@synthesize hashValue=_hashValue - In the implementation block
-(id)immutableCopy;
-(unsigned long long)hashValue;
-(id)init;
-(void)setHashValue:(unsigned long long)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(BOOL)isEqual:(id)arg1 ;
-(void)addProcess:(id)arg1 ;
-(NSMutableSet *)processes;
-(void)setProcesses:(NSMutableSet *)arg1 ;
@end

