/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:48:33 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libMemoryResourceException.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@class NSDirectoryEnumerator, NSString;

@interface RMECacheEnumerator : NSObject {

	NSDirectoryEnumerator* _internalEnumerator;
	NSString* _volume;

}

@property (nonatomic,copy) NSDirectoryEnumerator * internalEnumerator;              //@synthesize internalEnumerator=_internalEnumerator - In the implementation block
@property (nonatomic,retain) NSString * volume;                                     //@synthesize volume=_volume - In the implementation block
+(id)getLogContainer:(BOOL)arg1 ;
+(id)getLogPathsSortedByTime;
+(id)getLogPathsForSystemDiagnostic;
+(id)getEPLProfilePath;
-(void)setVolume:(NSString *)arg1 ;
-(NSString *)volume;
-(id)initCacheEnumeratorWithVolume:(id)arg1 ;
-(id)initCacheEnumerator;
-(id)nextValidURL;
-(NSDirectoryEnumerator *)internalEnumerator;
-(void)setInternalEnumerator:(NSDirectoryEnumerator *)arg1 ;
@end

