/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:48:26 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libAWDSupportFramework.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSData;

@interface AWDMDNSResponderResolveStatsResult : PBCodable <NSCopying> {

	unsigned _count;
	NSData* _data;
	unsigned _serverID;
	int _type;
	SCD_Struct_AW4 _has;

}

@property (assign,nonatomic) BOOL hasType; 
@property (assign,nonatomic) int type;                       //@synthesize type=_type - In the implementation block
@property (assign,nonatomic) BOOL hasCount; 
@property (assign,nonatomic) unsigned count;                 //@synthesize count=_count - In the implementation block
@property (assign,nonatomic) BOOL hasServerID; 
@property (assign,nonatomic) unsigned serverID;              //@synthesize serverID=_serverID - In the implementation block
@property (nonatomic,readonly) BOOL hasData; 
@property (nonatomic,retain) NSData * data;                  //@synthesize data=_data - In the implementation block
-(void)mergeFrom:(id)arg1 ;
-(void)setCount:(unsigned)arg1 ;
-(BOOL)hasCount;
-(id)typeAsString:(int)arg1 ;
-(void)setData:(NSData *)arg1 ;
-(unsigned long long)hash;
-(void)setServerID:(unsigned)arg1 ;
-(int)StringAsType:(id)arg1 ;
-(id)dictionaryRepresentation;
-(unsigned)count;
-(BOOL)hasData;
-(void)setType:(int)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)setHasType:(BOOL)arg1 ;
-(id)description;
-(BOOL)isEqual:(id)arg1 ;
-(NSData *)data;
-(void)copyTo:(id)arg1 ;
-(BOOL)hasType;
-(int)type;
-(unsigned)serverID;
-(void)writeTo:(id)arg1 ;
-(void)setHasCount:(BOOL)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)dealloc;
-(void)setHasServerID:(BOOL)arg1 ;
-(BOOL)hasServerID;
@end

