/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:48:28 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libAWDSupportFramework.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface AWDSpringBoardBreadcrumb : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	NSString* _entityID;
	NSString* _type;
	BOOL _wasTapped;
	SCD_Struct_AW3 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasWasTapped; 
@property (assign,nonatomic) BOOL wasTapped;                            //@synthesize wasTapped=_wasTapped - In the implementation block
@property (nonatomic,readonly) BOOL hasType; 
@property (nonatomic,retain) NSString * type;                           //@synthesize type=_type - In the implementation block
@property (nonatomic,readonly) BOOL hasEntityID; 
@property (nonatomic,retain) NSString * entityID;                       //@synthesize entityID=_entityID - In the implementation block
-(NSString *)entityID;
-(void)mergeFrom:(id)arg1 ;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(unsigned long long)hash;
-(BOOL)hasTimestamp;
-(id)dictionaryRepresentation;
-(void)setType:(NSString *)arg1 ;
-(void)setEntityID:(NSString *)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(id)description;
-(BOOL)isEqual:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(BOOL)hasType;
-(NSString *)type;
-(void)writeTo:(id)arg1 ;
-(BOOL)wasTapped;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)dealloc;
-(void)setWasTapped:(BOOL)arg1 ;
-(void)setHasWasTapped:(BOOL)arg1 ;
-(BOOL)hasWasTapped;
-(BOOL)hasEntityID;
@end

