/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:48:28 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libAWDSupportFramework.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface AWDTuple : PBCodable <NSCopying> {

	unsigned long long _downDuration;
	unsigned long long _upDuration;
	SCD_Struct_AW3 _has;

}

@property (assign,nonatomic) BOOL hasUpDuration; 
@property (assign,nonatomic) unsigned long long upDuration;                //@synthesize upDuration=_upDuration - In the implementation block
@property (assign,nonatomic) BOOL hasDownDuration; 
@property (assign,nonatomic) unsigned long long downDuration;              //@synthesize downDuration=_downDuration - In the implementation block
-(void)mergeFrom:(id)arg1 ;
-(unsigned long long)hash;
-(id)dictionaryRepresentation;
-(BOOL)readFrom:(id)arg1 ;
-(id)description;
-(BOOL)isEqual:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setDownDuration:(unsigned long long)arg1 ;
-(void)setUpDuration:(unsigned long long)arg1 ;
-(void)setHasUpDuration:(BOOL)arg1 ;
-(BOOL)hasUpDuration;
-(void)setHasDownDuration:(BOOL)arg1 ;
-(BOOL)hasDownDuration;
-(unsigned long long)upDuration;
-(unsigned long long)downDuration;
@end

