/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:48:30 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libAWDSupportFramework.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSMutableArray, AWDSlowWiFiNotification;

@interface AWDWiFiSlowWiFiReport : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	NSMutableArray* _linkQualSamples;
	AWDSlowWiFiNotification* _slowNotice;
	SCD_Struct_AW5 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                      //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) BOOL hasSlowNotice; 
@property (nonatomic,retain) AWDSlowWiFiNotification * slowNotice;              //@synthesize slowNotice=_slowNotice - In the implementation block
@property (nonatomic,retain) NSMutableArray * linkQualSamples;                  //@synthesize linkQualSamples=_linkQualSamples - In the implementation block
+(Class)linkQualSampleType;
-(void)mergeFrom:(id)arg1 ;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(unsigned long long)hash;
-(BOOL)hasTimestamp;
-(id)dictionaryRepresentation;
-(BOOL)readFrom:(id)arg1 ;
-(id)description;
-(BOOL)isEqual:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)dealloc;
-(void)addLinkQualSample:(id)arg1 ;
-(void)setSlowNotice:(AWDSlowWiFiNotification *)arg1 ;
-(unsigned long long)linkQualSamplesCount;
-(void)clearLinkQualSamples;
-(id)linkQualSampleAtIndex:(unsigned long long)arg1 ;
-(BOOL)hasSlowNotice;
-(AWDSlowWiFiNotification *)slowNotice;
-(NSMutableArray *)linkQualSamples;
-(void)setLinkQualSamples:(NSMutableArray *)arg1 ;
@end

