/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:48:36 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libnfstorage.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <libnfstorage.dylib/NFStorageController.h>

@interface NFStorageControllerIcfExpress : NFStorageController
-(id)name;
-(id)dbProtectionType;
-(id)_deleteAllIcfExpressEntities;
-(id)fetchIcfExpressEntitiesWithError:(id*)arg1 ;
-(void)updateIcfExpressEntitiesWithConfig:(id)arg1 ;
-(void)deleteAllIcfExpressEntities;
@end

