/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:34:23 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libnetwork.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <libnetwork.dylib/NWConcrete_nw_endpoint.h>

@protocol OS_nw_txt_record;
@class NSObject;

@interface NWOSBonjourEndpoint : NWConcrete_nw_endpoint {

	char* service_name;
	char* service_type;
	char* service_domain;
	char* service_composite;
	NSObject*<OS_nw_txt_record> txt_record;

}
-(id)txtRecord;
-(BOOL)isEqualToEndpoint:(id)arg1 matchInterface:(BOOL)arg2 matchParent:(BOOL)arg3 ;
-(unsigned long long)getHash;
-(id)copyDictionary;
-(id)copyEndpoint;
-(void)setTxtRecord:(id)arg1 ;
-(unsigned)type;
-(char*)createDescription:(BOOL)arg1 ;
-(void)dealloc;
-(const char*)domainForPolicy;
@end

