/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:38:30 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libobjc.A.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

typedef struct _NSZone* NSZoneRef;

typedef struct __CFString* CFStringRef;

typedef struct {
	char* field1;
	unsigned long long field2;
} SCD_Struct_NS2;

typedef struct sqlite3_stmt* sqlite3_stmtRef;

typedef struct __IOHIDEvent* IOHIDEventRef;

