/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:44:22 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libBKDM1.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@class NSMutableArray;

@interface ADStorage : NSObject {

	NSMutableArray* _eventList;

}
+(id)storage;
-(void)clear;
-(id)init;
-(void)pushToAggregateDictionary:(long long)arg1 useCase:(int)arg2 prearmedApplePay:(BOOL)arg3 ;
-(void)addEvent:(id)arg1 ;
@end

