/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:44:22 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libBKDM1.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <libBKDM1.dylib/BioLogBase.h>

@protocol OS_dispatch_queue;
@class NSObject;

@interface BioLog : BioLogBase {

	NSObject*<OS_dispatch_queue> _logQueue;

}
-(void)logRemoveAllIdentitiesForUser:(unsigned)arg1 withOptions:(id)arg2 fromClient:(id)arg3 ;
-(void)logEnrollResultIdentity:(id)arg1 withTimestamp:(unsigned long long)arg2 forClients:(id)arg3 ;
-(void)logCancelFromClient:(id)arg1 ;
-(void)logRemoveIdentity:(id)arg1 withError:(int)arg2 ;
-(void)logEnrollStartForUser:(unsigned)arg1 fromClient:(id)arg2 ;
-(void)dispatchLogEventAsync:(/*^block*/id)arg1 withCurrentTimestamp:(BOOL)arg2 ;
-(id)init;
-(id)details;
-(void)logEnrollStartError:(int)arg1 ;
-(id)packCurrentLog;
-(void)logDisplayState:(BOOL)arg1 withTimestamp:(unsigned long long)arg2 ;
-(void)logTemplateListFromIdentities:(id)arg1 ;
-(void)logUpdateIdentity:(id)arg1 withError:(int)arg2 ;
-(void)logHomeButtonState:(BOOL)arg1 fromKernel:(BOOL)arg2 withTimestamp:(unsigned long long)arg3 ;
-(void)logDisconnectingClient:(id)arg1 ;
-(void)logGetIdentityFromUUID:(id)arg1 fromClient:(id)arg2 ;
-(void)logLogStart;
-(void)logCall:(SEL)arg1 withError:(int)arg2 ;
-(void)logCancelError:(int)arg1 ;
-(void)logMatchStartError:(int)arg1 ;
-(id)logQueue;
-(void)logFingerDetectStartWithOptions:(id)arg1 fromClient:(id)arg2 ;
-(void)logGetMaxIdentityCount:(int)arg1 fromClient:(id)arg2 ;
-(void)logRemoveIdentity:(id)arg1 withOptions:(id)arg2 fromClient:(id)arg3 withTimestamp:(unsigned long long)arg4 ;
-(void)logGetIdentities:(id)arg1 fromClient:(id)arg2 ;
-(void)logProtectedConfigurationError:(int)arg1 ;
-(void)logStatusMessage:(int)arg1 withData:(id)arg2 timestamp:(unsigned long long)arg3 forClients:(id)arg4 ;
-(void)logSKSLockState:(unsigned short)arg1 forUser:(unsigned)arg2 withTimestamp:(unsigned long long)arg3 ;
-(void)logSaveTemplateListWithDetails:(id)arg1 ;
-(id)attachmentsFromAllLogs;
-(void)logUnlockedStateWithIdentities:(id)arg1 ;
-(void)logFingerDetectStartError:(int)arg1 ;
-(id)attachmentsFromCurrentLog;
-(void)logMatchStart:(id)arg1 withOptions:(id)arg2 fromClient:(id)arg3 ;
-(void)logSensorRecoveryReason:(unsigned)arg1 withTimestamp:(unsigned long long)arg2 ;
-(void)logUpdateIdentity:(id)arg1 withOptions:(id)arg2 fromClient:(id)arg3 ;
-(void)logAsync:(id)arg1 withDetails:(id)arg2 timestamp:(unsigned long long)arg3 endingWithToken:(char*)arg4 ;
-(void)logMatchStartFromClient:(id)arg1 ;
-(void)logKernelMessage:(id)arg1 ;
-(void)logSaveTemplateListError:(int)arg1 ;
-(void)logCall:(SEL)arg1 withParameters:(id)arg2 fromClient:(id)arg3 ;
-(void)closeLogFile;
-(void)logThermalLevel:(unsigned char)arg1 ;
-(void)logProtectedConfiguration:(id)arg1 forUser:(unsigned)arg2 fromClient:(id)arg3 ;
-(id)packAllLogs;
-(void)logWakeGestureState:(long long)arg1 ;
-(void)logMatchResultIdentity:(id)arg1 withDetails:(id)arg2 timestamp:(unsigned long long)arg3 forClients:(id)arg4 ;
-(void)logSensorStatus:(id)arg1 ;
-(void)logDelegateRegistered:(BOOL)arg1 fromClient:(id)arg2 ;
-(void)logPowerState:(BOOL)arg1 withTimestamp:(unsigned long long)arg2 ;
@end

