/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:44:22 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libBKDM1.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <libBKDM1.dylib/MesaCoreAnalyticsEvent.h>

@class NSDate, NSNumber;

@interface MesaCoreAnalyticsFingerLiftTimeEvent : MesaCoreAnalyticsEvent {

	NSDate* _fingerOnDate;
	NSDate* _fingerOffDate;
	NSNumber* _fingerLiftTime;

}

@property (retain) NSNumber * fingerLiftTime;              //@synthesize fingerLiftTime=_fingerLiftTime - In the implementation block
-(id)init;
-(BOOL)postEvent;
-(void)reset;
-(void)handleStatusMessage:(unsigned)arg1 forOperation:(unsigned char)arg2 ;
-(NSNumber *)fingerLiftTime;
-(void)setFingerLiftTime:(NSNumber *)arg1 ;
@end

