/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:48:33 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/libThreadExternalCommissioner.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <libobjc.A.dylib/NSNetServiceBrowserDelegate.h>
#import <libobjc.A.dylib/NSNetServiceDelegate.h>

@protocol BorderAgentListener;
@class NSNetServiceBrowser, NSMutableArray, NSString;

@interface BorderAgentFinder : NSObject <NSNetServiceBrowserDelegate, NSNetServiceDelegate> {

	NSNetServiceBrowser* _browser;
	NSMutableArray* _borderAgents;
	id<BorderAgentListener> _delegate;

}

@property (__weak) id<BorderAgentListener> delegate;                //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)start;
-(id)init;
-(id<BorderAgentListener>)delegate;
-(void)netServiceBrowser:(id)arg1 didFindService:(id)arg2 moreComing:(BOOL)arg3 ;
-(void)netServiceDidResolveAddress:(id)arg1 ;
-(void)netServiceWillResolve:(id)arg1 ;
-(void)netServiceBrowser:(id)arg1 didRemoveService:(id)arg2 moreComing:(BOOL)arg3 ;
-(void)netService:(id)arg1 didNotResolve:(id)arg2 ;
-(void)setDelegate:(id<BorderAgentListener>)arg1 ;
-(void)netServiceBrowserDidStopSearch:(id)arg1 ;
-(void)stop;
-(unsigned long long)getNumberOfBorderAgents;
-(id)getBorderAgentAtIndex:(unsigned long long)arg1 ;
-(id)getAgentDescription:(unsigned long long)arg1 ;
-(void)netServiceBrowserWillSearch:(id)arg1 ;
@end

