/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:48:37 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/swift/libswiftCoreMedia.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@interface _TtCVE9CoreMediaaSo22CMFormatDescriptionRef22ParameterSetCollectionP33_B5107634416AF8266ECF5CD01992F6B819CachedParameterSets : _UKNOWN_SUPERCLASS_ {

	 parameterSets;

}
@end

