//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardFoundation/SBAbstractSpringBoardDefaultDomain.h>

@class NSDictionary, NSString;

@interface SBBootDefaults : SBAbstractSpringBoardDefaultDomain
{
}


// Remaining properties
@property(nonatomic) NSDictionary *bootTransitionContext; // @dynamic bootTransitionContext;
@property(readonly, nonatomic) _Bool dontLockAfterCrash; // @dynamic dontLockAfterCrash;
@property(nonatomic) _Bool hasCompletedSynchronizingCloudCriticalData; // @dynamic hasCompletedSynchronizingCloudCriticalData;
@property(retain, nonatomic) NSString *lastRestoreIdentifier; // @dynamic lastRestoreIdentifier;
@property(retain, nonatomic) NSString *lastSystemBuildVersion; // @dynamic lastSystemBuildVersion;
@property(readonly, nonatomic) _Bool recordBootTimeTillDidFinishLaunching; // @dynamic recordBootTimeTillDidFinishLaunching;
@end

