//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardFoundation/NSObject-Protocol.h>

@class SBSAnalyticsState;

@protocol SBFAnalyticsBackendEventContextProviding <NSObject>
@property(readonly, nonatomic) SBSAnalyticsState *eventPayload;
- (void)stateForQueryName:(unsigned long long)arg1 completion:(void (^)(SBSAnalyticsState *))arg2;
@end

