//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardFoundation/SBFWallpaperView.h>

@class UIColor, UIImage;

@interface SBFColorWallpaperView : SBFWallpaperView
{
    UIImage *_cachedSnapshotImage;
}


// Remaining properties
@property(retain, nonatomic) UIImage *cachedSnapshotImage; // @synthesize cachedSnapshotImage=_cachedSnapshotImage;
@property(readonly, nonatomic) UIColor *wallpaperColor;
@end

