//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoardFoundation/SBDateTimeOverrideObserver-Protocol.h>
#import <SpringBoardFoundation/SBFDateProviding-Protocol.h>

@class NSDate, NSMutableDictionary, NSString, SBFDateTimeController;
@protocol SBFDateProviding;

@interface SBFOverridableDateProvider : NSObject <SBDateTimeOverrideObserver, SBFDateProviding>
{
    SBFDateTimeController *_dateTimeController;
    id <SBFDateProviding> _underlyingProvider;
    NSMutableDictionary *_minuteHandlers;
    unsigned long long _nextToken;
    id _underlyingToken;
    NSDate *_overrideDate;
    double _overrideDateOffset;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

