//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <BaseBoardUI/BSUIScrollView.h>

@class NSArray;

@interface SBFPagedScrollView : BSUIScrollView
{
    _Bool _changingScrollViewLayout;
    _Bool _gestureEnabled;
    NSArray *_pageViews;
    unsigned long long _currentPageIndex;
    struct _NSRange _visiblePageRange;
}


// Remaining properties
@property(nonatomic) unsigned long long currentPageIndex; // @synthesize currentPageIndex=_currentPageIndex;
@property(nonatomic) _Bool gestureEnabled; // @synthesize gestureEnabled=_gestureEnabled;
@property(copy, nonatomic) NSArray *pageViews; // @synthesize pageViews=_pageViews;
@property(nonatomic) struct _NSRange visiblePageRange; // @synthesize visiblePageRange=_visiblePageRange;
@end

