//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import <SpringBoardFoundation/SBUILegibility-Protocol.h>

@class NSString, UIImageView, _UILegibilitySettings;

@interface SBFStatusBarLegibilityView : UIView <SBUILegibility>
{
    _Bool _forceLegibilityGradientHidden;
    _UILegibilitySettings *_legibilitySettings;
    UIView *_statusBarGradientView;
    UIView *_overallGradientView;
    UIImageView *_leftCornerView;
    UIImageView *_rightCornerView;
}


// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) _Bool forceLegibilityGradientHidden; // @synthesize forceLegibilityGradientHidden=_forceLegibilityGradientHidden;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) UIImageView *leftCornerView; // @synthesize leftCornerView=_leftCornerView;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
@property(retain, nonatomic) UIView *overallGradientView; // @synthesize overallGradientView=_overallGradientView;
@property(retain, nonatomic) UIImageView *rightCornerView; // @synthesize rightCornerView=_rightCornerView;
@property(retain, nonatomic) UIView *statusBarGradientView; // @synthesize statusBarGradientView=_statusBarGradientView;
@property(nonatomic) double strength; // @dynamic strength;
@property(readonly) Class superclass;
@end

