//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSError, UIWebClip;

@interface SBFWebClipSanitationReport : NSObject
{
    UIWebClip *_webClip;
    long long _result;
    NSError *_error;
}


// Remaining properties
@property(readonly, copy, nonatomic) NSError *error; // @synthesize error=_error;
@property(readonly, nonatomic) long long result; // @synthesize result=_result;
@property(readonly, nonatomic) UIWebClip *webClip; // @synthesize webClip=_webClip;
@end

