//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, SBFMappedImageCache;
@protocol OS_dispatch_queue;

@interface SBFWallpaperCache : NSObject
{
    NSString *_path;
    NSObject<OS_dispatch_queue> *_queue;
    SBFMappedImageCache *_imageCache;
}


// Remaining properties
@property(readonly, nonatomic) SBFMappedImageCache *imageCache; // @synthesize imageCache=_imageCache;
@end

