//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSDictionary, NSString;

@interface SBFWallpaperDefaultsWrapper : NSObject
{
    _Bool _supportsCropping;
    _Bool _magnifyEnabled;
    _Bool _portrait;
    _Bool _hasVideo;
    _Bool _wallpaperWasUserSet;
    double _parallaxFactor;
    double _zoomScale;
    NSString *_wallpaperName;
    NSData *_imageHashData;
    long long _wallpaperMode;
    NSDictionary *_wallpaperKitData;
    double _stillTimeInVideo;
    NSString *_wallpaperIdentifier;
    NSDictionary *_wallpaperOptions;
    NSData *_colorData;
    NSString *_colorName;
    NSData *_gradientData;
    struct CGRect _cropRect;
}


// Remaining properties
@property(retain, nonatomic) NSData *colorData; // @synthesize colorData=_colorData;
@property(retain, nonatomic) NSString *colorName; // @synthesize colorName=_colorName;
@property(nonatomic) struct CGRect cropRect; // @synthesize cropRect=_cropRect;
@property(retain, nonatomic) NSData *gradientData; // @synthesize gradientData=_gradientData;
@property(nonatomic) _Bool hasVideo; // @synthesize hasVideo=_hasVideo;
@property(retain, nonatomic) NSData *imageHashData; // @synthesize imageHashData=_imageHashData;
@property(nonatomic) _Bool magnifyEnabled; // @synthesize magnifyEnabled=_magnifyEnabled;
@property(nonatomic) double parallaxFactor; // @synthesize parallaxFactor=_parallaxFactor;
@property(nonatomic) _Bool portrait; // @synthesize portrait=_portrait;
@property(nonatomic) double stillTimeInVideo; // @synthesize stillTimeInVideo=_stillTimeInVideo;
@property(nonatomic) _Bool supportsCropping; // @synthesize supportsCropping=_supportsCropping;
@property(retain, nonatomic) NSString *wallpaperIdentifier; // @synthesize wallpaperIdentifier=_wallpaperIdentifier;
@property(retain, nonatomic) NSDictionary *wallpaperKitData; // @synthesize wallpaperKitData=_wallpaperKitData;
@property(nonatomic) long long wallpaperMode; // @synthesize wallpaperMode=_wallpaperMode;
@property(retain, nonatomic) NSString *wallpaperName; // @synthesize wallpaperName=_wallpaperName;
@property(retain, nonatomic) NSDictionary *wallpaperOptions; // @synthesize wallpaperOptions=_wallpaperOptions;
@property(nonatomic) _Bool wallpaperWasUserSet; // @synthesize wallpaperWasUserSet=_wallpaperWasUserSet;
@property(nonatomic) double zoomScale; // @synthesize zoomScale=_zoomScale;
@end

