//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardFoundation/SBAbstractSpringBoardDefaultDomain.h>

@interface SBSoftwareUpdateDefaults : SBAbstractSpringBoardDefaultDomain
{
}


// Remaining properties
@property(nonatomic, getter=hasDeveloperInstallBrickAlertShown3DayWarning) _Bool developerInstallBrickAlertShown3DayWarning; // @dynamic developerInstallBrickAlertShown3DayWarning;
@property(nonatomic, getter=hasDeveloperInstallBrickAlertShown7DayWarning) _Bool developerInstallBrickAlertShown7DayWarning; // @dynamic developerInstallBrickAlertShown7DayWarning;
@property(nonatomic, getter=hasDeveloperInstallBrickAlertShownTomorrowWarning) _Bool developerInstallBrickAlertShownTomorrowWarning; // @dynamic developerInstallBrickAlertShownTomorrowWarning;
@end

