//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardFoundation/SBAbstractSpringBoardDefaultDomain.h>

@class NSString;

@interface SBTestingDefaults : SBAbstractSpringBoardDefaultDomain
{
}


// Remaining properties
@property(copy, nonatomic) NSString *testRunnerRecoveryApplicationBundleIdentifier; // @dynamic testRunnerRecoveryApplicationBundleIdentifier;
@end

