/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, November 11, 2020 at 12:48:38 PM Eastern Standard Time
                       * Operating System: Version 14.2 (Build 18B92)
                       * Image Source: /usr/lib/system/libsystem_blocks.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <libsystem_blocks.dylib/libsystem_blocks.dylib-Structs.h>
#import <CoreFoundation/NSBlock.h>

@interface __NSGlobalBlock__ : NSBlock
-(oneway void)release;
-(id)retain;
-(unsigned long long)retainCount;
-(BOOL)_tryRetain;
-(BOOL)_isDeallocating;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)copy;
@end

