//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SpringBoardServices/NSObject-Protocol.h>

@protocol BSXPCDecoding, BSXPCEncoding;

@protocol BSXPCSecureCoding <NSObject>
+ (_Bool)supportsBSXPCSecureCoding;
- (id)initWithBSXPCCoder:(id <BSXPCDecoding>)arg1;
- (void)encodeWithBSXPCCoder:(id <BSXPCEncoding>)arg1;
@end

