//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FrontBoardServices/FBSDisplayLayoutElement.h>

@interface SBSExternalDisplayLayoutElement : FBSDisplayLayoutElement
{
}


// Remaining properties
@property(readonly, nonatomic, getter=isPresenting) _Bool presenting;
@end

