//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoardServices/SBSHomeScreenServiceServerToClientInterface-Protocol.h>

@class BSServiceConnection, NSArray;
@protocol OS_dispatch_queue;

@interface SBSHomeScreenService : NSObject <SBSHomeScreenServiceServerToClientInterface>
{
    BSServiceConnection *_connection;
    NSObject<OS_dispatch_queue> *_connectionQueue;
}


// Remaining properties
@property(nonatomic) _Bool addsNewIconsToHomeScreen;
@property(readonly, copy, nonatomic) NSArray *allHomeScreenApplicationBundleIdentifiers;
@property(readonly, copy, nonatomic) NSArray *allHomeScreenApplicationPlaceholderBundleIdentifiers;
@property(nonatomic, getter=isLowDensityIconLayoutEnabled) _Bool lowDensityIconLayoutEnabled;
@property(nonatomic) _Bool showsBadgesInAppLibrary;
@end

