//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <FrontBoardServices/BSAction.h>

@class NSString;

@interface SBSLockScreenContentAction : BSAction
{
    unsigned long long _type;
    NSString *_slot;
    unsigned long long _secureAppType;
    id _configurationObject;
}


// Remaining properties
@property(retain, nonatomic) id configurationObject; // @synthesize configurationObject=_configurationObject;
@property(readonly, nonatomic) NSString *identifier;
@property(nonatomic) unsigned long long secureAppType; // @synthesize secureAppType=_secureAppType;
@property(retain, nonatomic) NSString *slot; // @synthesize slot=_slot;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@end

