//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoardServices/BSXPCCoding-Protocol.h>
#import <SpringBoardServices/NSSecureCoding-Protocol.h>

@class NSDictionary, NSSet, NSString;
@protocol OS_xpc_object;

@interface SBSRemoteAlertConfigurationContext : NSObject <BSXPCCoding, NSSecureCoding>
{
    NSDictionary *_userInfo;
    NSObject<OS_xpc_object> *_xpcEndpoint;
    NSSet *_actions;
    NSDictionary *_legacyAlertOptions;
}


// Remaining properties
@property(copy, nonatomic) NSSet *actions; // @synthesize actions=_actions;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, copy, nonatomic) NSDictionary *legacyAlertOptions; // @synthesize legacyAlertOptions=_legacyAlertOptions;
@property(readonly) Class superclass;
@property(copy, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(retain, nonatomic) NSObject<OS_xpc_object> *xpcEndpoint; // @synthesize xpcEndpoint=_xpcEndpoint;
@end

