//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 22 2020 21:25:24).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoardServices/NSSecureCoding-Protocol.h>

@interface SBSRemoteContentPreferences : NSObject <NSSecureCoding>
{
    long long _dateTimeStyle;
    long long _backgroundStyle;
    _Bool _restrictsHomeGesture;
    long long _homeGestureMode;
    _Bool _reducesWhitePoint;
    _Bool _suppressesNotifications;
    _Bool _suppressesBottomEdgeContent;
}

@end

